// Generated by Framer (ca8ceca)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle1 from "https://framerusercontent.com/modules/wabWwlCwE0d1kRNmT2Nz/QrVP0NrAm8yrx5SvHaC3/miauGmWjN.js";
import * as sharedStyle from "https://framerusercontent.com/modules/sLUDmEC7eXk9IPzkWbhb/YhEzpCmK6YrFhA6Ch9m5/ubMZRhUD0.js";
const enabledGestures = { yRtUOlRrn: { hover: true } };
const serializationHash = "framer-gfH7F";
const variantClassNames = { yRtUOlRrn: "framer-v-aw7ey0" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const Lj_GWxxRQ = undefined;
const UHgttF2ZR = undefined;
const OtyT0gRza = undefined;
const transition1 = { bounce: 0, delay: 0, duration: 0.4, type: "spring" };
const animation = {
  opacity: 1,
  rotate: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 60,
};
const transition2 = { bounce: 0, delay: 0.025, duration: 0.8, type: "spring" };
const textEffect = {
  effect: animation,
  repeat: false,
  startDelay: 0,
  tokenization: "character",
  transition: transition2,
  trigger: "onMount",
  type: "appear",
};
const animation1 = {
  opacity: 1,
  rotate: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 220,
};
const textEffect1 = {
  effect: animation1,
  tokenization: "character",
  transition: transition2,
  trigger: "onMount",
  type: "appear",
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
  category,
  height,
  id,
  projectName,
  width,
  year,
  ...props
}) => {
  return {
    ...props,
    Lj_GWxxRQ: category ?? props.Lj_GWxxRQ ?? "Category",
    OtyT0gRza: year ?? props.OtyT0gRza ?? "2026",
    UHgttF2ZR: projectName ?? props.UHgttF2ZR ?? "Project Name",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    UHgttF2ZR,
    OtyT0gRza,
    Lj_GWxxRQ,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "yRtUOlRrn",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (gestureVariant === "yRtUOlRrn-hover") return true;
    return false;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-aw7ey0",
            className,
            classNames
          ),
          "data-framer-name": "Variant 1",
          layoutDependency: layoutDependency,
          layoutId: "yRtUOlRrn",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            { "yRtUOlRrn-hover": { "data-framer-name": undefined } },
            baseVariant,
            gestureVariant
          ),
          children: [
            isDisplayed() &&
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-7iqzml",
                "data-framer-name": "Category Container",
                layoutDependency: layoutDependency,
                layoutId: "x_ZPnHBXP",
                children: /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      className: "framer-styles-preset-1t3p7eg",
                      "data-styles-preset": "ubMZRhUD0",
                      dir: "auto",
                      style: {
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, rgb(0, 0, 0)))",
                      },
                      children: "Category",
                    }),
                  }),
                  className: "framer-99w712",
                  effect: textEffect,
                  fonts: ["Inter"],
                  layoutDependency: layoutDependency,
                  layoutId: "efMVJZ8cX",
                  style: {
                    "--extracted-r6o4lv":
                      "var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, rgb(0, 0, 0))",
                  },
                  text: Lj_GWxxRQ,
                  verticalAlignment: "top",
                  withExternalLayout: true,
                }),
              }),
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-jejbyx",
              "data-framer-name": "Name Container",
              layoutDependency: layoutDependency,
              layoutId: "vFNUUyICs",
              children: /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-fhvjey",
                    "data-styles-preset": "miauGmWjN",
                    dir: "auto",
                    style: {
                      "--framer-text-color":
                        "var(--extracted-r6o4lv, var(--token-15d9932d-74d4-4021-b23d-e56deea4c505, rgb(229, 229, 229)))",
                    },
                    children: "Project Name",
                  }),
                }),
                className: "framer-ard5jd",
                effect: textEffect1,
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "S03BZBjGt",
                style: {
                  "--extracted-r6o4lv":
                    "var(--token-15d9932d-74d4-4021-b23d-e56deea4c505, rgb(229, 229, 229))",
                },
                text: UHgttF2ZR,
                variants: {
                  "yRtUOlRrn-hover": {
                    "--extracted-r6o4lv":
                      "var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, rgb(0, 0, 0))",
                  },
                },
                verticalAlignment: "top",
                withExternalLayout: true,
                ...addPropertyOverrides(
                  {
                    "yRtUOlRrn-hover": {
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                          className: "framer-styles-preset-fhvjey",
                          "data-styles-preset": "miauGmWjN",
                          dir: "auto",
                          style: {
                            "--framer-text-color":
                              "var(--extracted-r6o4lv, var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, rgb(0, 0, 0)))",
                          },
                          children: "Project Name",
                        }),
                      }),
                    },
                  },
                  baseVariant,
                  gestureVariant
                ),
              }),
            }),
            isDisplayed() &&
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-16vheno",
                "data-framer-name": "Year Container",
                layoutDependency: layoutDependency,
                layoutId: "QTu2m3Om6",
                children: /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      className: "framer-styles-preset-1t3p7eg",
                      "data-styles-preset": "ubMZRhUD0",
                      dir: "auto",
                      style: {
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, rgb(0, 0, 0)))",
                      },
                      children: "2026",
                    }),
                  }),
                  className: "framer-ps3s3n",
                  effect: textEffect,
                  fonts: ["Inter"],
                  layoutDependency: layoutDependency,
                  layoutId: "cxcKc35NZ",
                  style: {
                    "--extracted-r6o4lv":
                      "var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, rgb(0, 0, 0))",
                  },
                  text: OtyT0gRza,
                  verticalAlignment: "top",
                  withExternalLayout: true,
                }),
              }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-gfH7F.framer-em0wof, .framer-gfH7F .framer-em0wof { display: block; }",
  ".framer-gfH7F.framer-aw7ey0 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 120px; height: min-content; justify-content: center; overflow: visible; padding: 24px 4px 24px 4px; position: relative; width: 859px; }",
  ".framer-gfH7F .framer-7iqzml { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: min-content; }",
  ".framer-gfH7F .framer-99w712, .framer-gfH7F .framer-ard5jd, .framer-gfH7F .framer-ps3s3n { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
  ".framer-gfH7F .framer-jejbyx { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: min-content; }",
  ".framer-gfH7F .framer-16vheno { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: min-content; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 192
 * @framerIntrinsicWidth 859
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"SDNWwEcGi":{"layout":["fixed","auto"]}}}
 * @framerVariables {"UHgttF2ZR":"projectName","OtyT0gRza":"year","Lj_GWxxRQ":"category"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerACx_WmG6E = withCSS(Component, css, "framer-gfH7F");
export default FramerACx_WmG6E;
FramerACx_WmG6E.displayName = "Project Info (List View)";
FramerACx_WmG6E.defaultProps = { height: 192, width: 859 };
addPropertyControls(FramerACx_WmG6E, {
  UHgttF2ZR: {
    defaultValue: "Project Name",
    title: "Project Name",
    type: ControlType.String,
  },
  onUHgttF2ZRChange: { changes: "UHgttF2ZR", type: ControlType.ChangeHandler },
  OtyT0gRza: {
    defaultValue: "2026",
    displayTextArea: false,
    title: "Year",
    type: ControlType.String,
  },
  onOtyT0gRzaChange: { changes: "OtyT0gRza", type: ControlType.ChangeHandler },
  Lj_GWxxRQ: {
    defaultValue: "Category",
    displayTextArea: false,
    title: "Category",
    type: ControlType.String,
  },
  onLj_GWxxRQChange: { changes: "Lj_GWxxRQ", type: ControlType.ChangeHandler },
});
addFonts(
  FramerACx_WmG6E,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerACx_WmG6E",
      slots: [],
      annotations: {
        framerIntrinsicHeight: "192",
        framerComponentViewportWidth: "true",
        framerColorSyntax: "true",
        framerDisplayContentsDiv: "false",
        framerImmutableVariables: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"SDNWwEcGi":{"layout":["fixed","auto"]}}}',
        framerIntrinsicWidth: "859",
        framerVariables:
          '{"UHgttF2ZR":"projectName","OtyT0gRza":"year","Lj_GWxxRQ":"category"}',
        framerAutoSizeImages: "true",
        framerContractVersion: "1",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
