// Generated by Framer (e0e363b)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  forwardLoader,
  getFonts,
  getFontsFromSharedStyle,
  Link,
  RichText,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCodeBoundaryForOverrides,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import { AutoCopyrightStatement } from "https://framerusercontent.com/modules/zm0UyAzfV4IYbQ5dF1C3/uPlM2qqPEoSui8gUjGpp/CurrentYear.js";
import * as sharedStyle from "https://framerusercontent.com/modules/GgteY8irBGfUzh8z4mh2/NzDgB7DilEKK0dJEeHtg/mMKAraaKM.js";
import * as sharedStyle1 from "https://framerusercontent.com/modules/kICQBgc7e5zUwiKdhF6P/ujkMYgogUnlWPxBynzgd/qxloupasW.js";
import ContactInfo from "https://framerusercontent.com/modules/yqm3MJ8iySkx1bdDGy5k/C7TMdwv58zCYPJgUrj68/RoyacsNdv.js";
const ContactInfoFonts = getFonts(ContactInfo);
const RichTextAutoCopyrightStatementq6k1mq = withCodeBoundaryForOverrides(
  RichText,
  {
    nodeId: "IBrkunLSn",
    override: AutoCopyrightStatement,
    scopeId: "xNVv5vbzH",
  }
);
const cycleOrder = ["SHYUAibwl", "Y4qJMr6hn", "zLkwbJJ3P"];
const serializationHash = "framer-l3pwO";
const variantClassNames = {
  SHYUAibwl: "framer-v-1hqskz8",
  Y4qJMr6hn: "framer-v-14nr59m",
  zLkwbJJ3P: "framer-v-mfcq8v",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const TtemKiaS7 = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  Desktop: "SHYUAibwl",
  Phone: "zLkwbJJ3P",
  Tablet: "Y4qJMr6hn",
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, hideCursor, id, width, ...props }) => {
  return {
    ...props,
    TtemKiaS7: hideCursor ?? props.TtemKiaS7,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "SHYUAibwl",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, TtemKiaS7, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "SHYUAibwl",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.footer, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1hqskz8",
            className,
            classNames
          ),
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "SHYUAibwl",
          ref: refBinding,
          style: {
            backgroundColor:
              "var(--token-280bd9a0-bf37-41b4-a3c3-9a122b679a65, rgb(255, 255, 255))",
            ...style,
          },
          ...addPropertyOverrides(
            {
              Y4qJMr6hn: { "data-framer-name": "Tablet" },
              zLkwbJJ3P: { "data-framer-name": "Phone" },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-1haa6xn",
              "data-framer-name": "Footer section",
              layoutDependency: layoutDependency,
              layoutId: "XjGs_k1iN",
              children: [
                /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-1x6fvk5",
                  "data-framer-name": "Section",
                  layoutDependency: layoutDependency,
                  layoutId: "rmEBnjWep",
                  children: /*#__PURE__*/ _jsx(motion.div, {
                    className: "framer-3efy5k",
                    "data-framer-name": "Container",
                    layoutDependency: layoutDependency,
                    layoutId: "AvoLuB76o",
                    children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      height: 230,
                      width: `calc(max((${
                        componentViewport?.width || "100vw"
                      } - 40px) / 2, 1px) - 40px)`,
                      y:
                        (componentViewport?.y || 0) +
                        120 +
                        (((componentViewport?.height || 485) - 152 - 422) / 2 +
                          0 +
                          0) +
                        0 +
                        0 +
                        0 +
                        0 +
                        0,
                      ...addPropertyOverrides(
                        {
                          Y4qJMr6hn: {
                            width: `calc(max((${
                              componentViewport?.width || "100vw"
                            } - 30px) / 2, 1px) - 30px)`,
                            y:
                              (componentViewport?.y || 0) +
                              120 +
                              (((componentViewport?.height || 573) -
                                240 -
                                422) /
                                2 +
                                0 +
                                0) +
                              0 +
                              0 +
                              0 +
                              0 +
                              0,
                          },
                          zLkwbJJ3P: {
                            width: `calc(${
                              componentViewport?.width || "100vw"
                            } - 40px)`,
                            y:
                              (componentViewport?.y || 0) +
                              80 +
                              (((componentViewport?.height || 954.5) -
                                200 -
                                910.8) /
                                2 +
                                0 +
                                0) +
                              0 +
                              0 +
                              0 +
                              0 +
                              0 +
                              0,
                          },
                        },
                        baseVariant,
                        gestureVariant
                      ),
                      children: /*#__PURE__*/ _jsx(
                        SmartComponentScopedContainer,
                        {
                          className: "framer-1mhnee9-container",
                          layoutDependency: layoutDependency,
                          layoutId: "nXQqt1nWK-container",
                          nodeId: "nXQqt1nWK",
                          rendersWithMotion: true,
                          scopeId: "xNVv5vbzH",
                          children: /*#__PURE__*/ _jsx(ContactInfo, {
                            height: "100%",
                            id: "nXQqt1nWK",
                            layoutId: "nXQqt1nWK",
                            rjCb_ICSr: TtemKiaS7,
                            style: { width: "100%" },
                            width: "100%",
                          }),
                        }
                      ),
                    }),
                  }),
                }),
                /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-jinp0w",
                  "data-framer-name": "Section",
                  layoutDependency: layoutDependency,
                  layoutId: "kHLBzH5DA",
                  children: /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-c742n6",
                    "data-framer-cursor": TtemKiaS7,
                    "data-framer-name": "Container",
                    layoutDependency: layoutDependency,
                    layoutId: "x9XUF65Zm",
                    children: [
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            className: "framer-styles-preset-1rymzzk",
                            "data-styles-preset": "mMKAraaKM",
                            dir: "auto",
                            children: /*#__PURE__*/ _jsx(Link, {
                              href: { webPageId: "augiA20Il" },
                              motionChild: true,
                              nodeId: "Ds0bd3j6j",
                              openInNewTab: false,
                              relValues: [],
                              scopeId: "xNVv5vbzH",
                              smoothScroll: false,
                              children: /*#__PURE__*/ _jsx(motion.a, {
                                className: "framer-styles-preset-17pmv6x",
                                "data-styles-preset": "qxloupasW",
                                children: "Work",
                              }),
                            }),
                          }),
                        }),
                        className: "framer-104ded4",
                        "data-framer-cursor": TtemKiaS7,
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "Ds0bd3j6j",
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }),
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            className: "framer-styles-preset-1rymzzk",
                            "data-styles-preset": "mMKAraaKM",
                            dir: "auto",
                            children: /*#__PURE__*/ _jsx(Link, {
                              href: { webPageId: "ybNXXBVS7" },
                              motionChild: true,
                              nodeId: "S58luyeW2",
                              openInNewTab: false,
                              relValues: [],
                              scopeId: "xNVv5vbzH",
                              smoothScroll: false,
                              children: /*#__PURE__*/ _jsx(motion.a, {
                                className: "framer-styles-preset-17pmv6x",
                                "data-styles-preset": "qxloupasW",
                                children: "Studio",
                              }),
                            }),
                          }),
                        }),
                        className: "framer-6i7spf",
                        "data-framer-cursor": TtemKiaS7,
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "S58luyeW2",
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }),
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            className: "framer-styles-preset-1rymzzk",
                            "data-styles-preset": "mMKAraaKM",
                            dir: "auto",
                            children: /*#__PURE__*/ _jsx(Link, {
                              href: { webPageId: "CtAwHCE4u" },
                              motionChild: true,
                              nodeId: "ImwfkDr7v",
                              openInNewTab: false,
                              relValues: [],
                              scopeId: "xNVv5vbzH",
                              smoothScroll: false,
                              children: /*#__PURE__*/ _jsx(motion.a, {
                                className: "framer-styles-preset-17pmv6x",
                                "data-styles-preset": "qxloupasW",
                                children: "Insights",
                              }),
                            }),
                          }),
                        }),
                        className: "framer-1vr0gsf",
                        "data-framer-cursor": TtemKiaS7,
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "ImwfkDr7v",
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }),
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            className: "framer-styles-preset-1rymzzk",
                            "data-styles-preset": "mMKAraaKM",
                            dir: "auto",
                            children: /*#__PURE__*/ _jsx(Link, {
                              href: { webPageId: "qaPx9BLEM" },
                              motionChild: true,
                              nodeId: "yErxfMCGq",
                              openInNewTab: false,
                              relValues: [],
                              scopeId: "xNVv5vbzH",
                              smoothScroll: false,
                              children: /*#__PURE__*/ _jsx(motion.a, {
                                className: "framer-styles-preset-17pmv6x",
                                "data-styles-preset": "qxloupasW",
                                children: "Contact",
                              }),
                            }),
                          }),
                        }),
                        className: "framer-13h3ara",
                        "data-framer-cursor": TtemKiaS7,
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "yErxfMCGq",
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }),
                    ],
                  }),
                }),
                /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-aucqqm",
                  "data-framer-name": "Section",
                  layoutDependency: layoutDependency,
                  layoutId: "AQxvpbcMy",
                  children: /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-1je8oxk",
                    "data-framer-cursor": TtemKiaS7,
                    "data-framer-name": "Container",
                    layoutDependency: layoutDependency,
                    layoutId: "KPbRpd2cc",
                    children: [
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            className: "framer-styles-preset-1rymzzk",
                            "data-styles-preset": "mMKAraaKM",
                            dir: "auto",
                            children: /*#__PURE__*/ _jsx(Link, {
                              href: {
                                pathVariables: { iVONskd1W: "privacy-policy" },
                                unresolvedPathSlugs: {
                                  iVONskd1W: {
                                    collectionId: "TBKkMyqX4",
                                    collectionItemId: "imkKDo9_b",
                                  },
                                },
                                webPageId: "H9RqptdtI",
                              },
                              motionChild: true,
                              nodeId: "Q8htiogj6",
                              openInNewTab: false,
                              relValues: [],
                              scopeId: "xNVv5vbzH",
                              smoothScroll: false,
                              children: /*#__PURE__*/ _jsx(motion.a, {
                                className: "framer-styles-preset-17pmv6x",
                                "data-styles-preset": "qxloupasW",
                                children: "Privacy Policy",
                              }),
                            }),
                          }),
                        }),
                        className: "framer-g47mc6",
                        "data-framer-cursor": TtemKiaS7,
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "Q8htiogj6",
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }),
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            className: "framer-styles-preset-1rymzzk",
                            "data-styles-preset": "mMKAraaKM",
                            dir: "auto",
                            children: /*#__PURE__*/ _jsx(Link, {
                              href: {
                                pathVariables: {
                                  iVONskd1W: "terms-of-service",
                                },
                                unresolvedPathSlugs: {
                                  iVONskd1W: {
                                    collectionId: "TBKkMyqX4",
                                    collectionItemId: "hbta4cJBG",
                                  },
                                },
                                webPageId: "H9RqptdtI",
                              },
                              motionChild: true,
                              nodeId: "ouI4A_9Nw",
                              openInNewTab: false,
                              relValues: [],
                              scopeId: "xNVv5vbzH",
                              smoothScroll: false,
                              children: /*#__PURE__*/ _jsx(motion.a, {
                                className: "framer-styles-preset-17pmv6x",
                                "data-styles-preset": "qxloupasW",
                                children: "Terms of service",
                              }),
                            }),
                          }),
                        }),
                        className: "framer-177epsx",
                        "data-framer-cursor": TtemKiaS7,
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "ouI4A_9Nw",
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }),
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            className: "framer-styles-preset-1rymzzk",
                            "data-styles-preset": "mMKAraaKM",
                            dir: "auto",
                            children: /*#__PURE__*/ _jsx(Link, {
                              href: { webPageId: "DdnmDa6XO" },
                              motionChild: true,
                              nodeId: "FfqwaJPLJ",
                              openInNewTab: false,
                              relValues: [],
                              scopeId: "xNVv5vbzH",
                              smoothScroll: false,
                              children: /*#__PURE__*/ _jsx(motion.a, {
                                className: "framer-styles-preset-17pmv6x",
                                "data-styles-preset": "qxloupasW",
                                children: "404",
                              }),
                            }),
                          }),
                        }),
                        className: "framer-1s1i1ad",
                        "data-framer-cursor": TtemKiaS7,
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "FfqwaJPLJ",
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }),
                    ],
                  }),
                }),
              ],
            }),
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-147t904",
              "data-framer-name": "Footer section",
              layoutDependency: layoutDependency,
              layoutId: "xWYTDaTct",
              children: [
                /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-1jyjq70",
                  "data-framer-name": "Section",
                  layoutDependency: layoutDependency,
                  layoutId: "F3sh_5KfZ",
                  children: /*#__PURE__*/ _jsx(motion.div, {
                    className: "framer-1vmp5p2",
                    "data-framer-name": "Container",
                    layoutDependency: layoutDependency,
                    layoutId: "ZQW472obA",
                    children: /*#__PURE__*/ _jsx(RichText, {
                      __fromCanvasComponent: true,
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsxs(motion.p, {
                          className: "framer-styles-preset-1rymzzk",
                          "data-styles-preset": "mMKAraaKM",
                          dir: "auto",
                          children: [
                            /*#__PURE__*/ _jsx(Link, {
                              href: "#",
                              motionChild: true,
                              nodeId: "aV3moyi6X",
                              openInNewTab: false,
                              preserveParams: false,
                              relValues: [],
                              scopeId: "xNVv5vbzH",
                              smoothScroll: false,
                              children: /*#__PURE__*/ _jsx(motion.a, {
                                className: "framer-styles-preset-17pmv6x",
                                "data-styles-preset": "qxloupasW",
                                children: "Framer",
                              }),
                            }),
                            " Template handcrafted by\xa0",
                            /*#__PURE__*/ _jsx(Link, {
                              href: "#",
                              motionChild: true,
                              nodeId: "aV3moyi6X",
                              openInNewTab: true,
                              relValues: [],
                              scopeId: "xNVv5vbzH",
                              smoothScroll: false,
                              children: /*#__PURE__*/ _jsx(motion.a, {
                                className: "framer-styles-preset-17pmv6x",
                                "data-styles-preset": "qxloupasW",
                                children: "Avataar\xa0Visora",
                              }),
                            }),
                          ],
                        }),
                      }),
                      className: "framer-13g8imz",
                      "data-framer-cursor": TtemKiaS7,
                      fonts: ["Inter"],
                      layoutDependency: layoutDependency,
                      layoutId: "aV3moyi6X",
                      verticalAlignment: "top",
                      withExternalLayout: true,
                    }),
                  }),
                }),
                /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-b3md50",
                  "data-framer-name": "Section",
                  layoutDependency: layoutDependency,
                  layoutId: "wyX8LTmLw",
                  children: /*#__PURE__*/ _jsx(motion.div, {
                    className: "framer-cyld6i",
                    "data-framer-name": "Container",
                    layoutDependency: layoutDependency,
                    layoutId: "gDG3OpPjd",
                    children: /*#__PURE__*/ _jsx(
                      RichTextAutoCopyrightStatementq6k1mq,
                      {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            className: "framer-styles-preset-1rymzzk",
                            "data-styles-preset": "mMKAraaKM",
                            dir: "auto",
                            children:
                              "\xa9YYYY Avataar Visora. All\xa0rights\xa0reserved.",
                          }),
                        }),
                        className: "framer-q6k1mq",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "IBrkunLSn",
                        style: { "--framer-paragraph-spacing": "8px" },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }
                    ),
                  }),
                }),
              ],
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-l3pwO.framer-7a80y8, .framer-l3pwO .framer-7a80y8 { display: block; }",
  ".framer-l3pwO.framer-1hqskz8 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: center; overflow: visible; padding: 120px 20px 32px 20px; position: relative; width: 1200px; }",
  ".framer-l3pwO .framer-1haa6xn, .framer-l3pwO .framer-147t904 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
  ".framer-l3pwO .framer-1x6fvk5 { align-content: center; align-items: center; display: flex; flex: 2 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1px; }",
  ".framer-l3pwO .framer-3efy5k, .framer-l3pwO .framer-1vmp5p2 { -webkit-user-select: auto; align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: visible; padding: 0px 20px 0px 20px; pointer-events: auto; position: relative; user-select: auto; width: 100%; }",
  ".framer-l3pwO .framer-1mhnee9-container { flex: none; height: auto; position: relative; width: 100%; }",
  ".framer-l3pwO .framer-jinp0w, .framer-l3pwO .framer-aucqqm, .framer-l3pwO .framer-1jyjq70, .framer-l3pwO .framer-b3md50 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1px; }",
  ".framer-l3pwO .framer-c742n6, .framer-l3pwO .framer-1je8oxk, .framer-l3pwO .framer-cyld6i { -webkit-user-select: auto; align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px 20px 0px 20px; pointer-events: auto; position: relative; user-select: auto; width: 100%; }",
  ".framer-l3pwO .framer-104ded4, .framer-l3pwO .framer-6i7spf, .framer-l3pwO .framer-1vr0gsf, .framer-l3pwO .framer-13h3ara, .framer-l3pwO .framer-g47mc6, .framer-l3pwO .framer-177epsx, .framer-l3pwO .framer-1s1i1ad { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-l3pwO .framer-13g8imz, .framer-l3pwO .framer-q6k1mq { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-l3pwO.framer-v-14nr59m.framer-1hqskz8 { padding: 120px 15px 120px 15px; width: 810px; }",
  ".framer-l3pwO.framer-v-14nr59m .framer-3efy5k, .framer-l3pwO.framer-v-14nr59m .framer-c742n6, .framer-l3pwO.framer-v-14nr59m .framer-1je8oxk, .framer-l3pwO.framer-v-14nr59m .framer-1vmp5p2, .framer-l3pwO.framer-v-14nr59m .framer-cyld6i { padding: 0px 15px 0px 15px; }",
  ".framer-l3pwO.framer-v-14nr59m .framer-1jyjq70, .framer-l3pwO.framer-v-14nr59m .framer-b3md50 { flex: 2 0 0px; }",
  ".framer-l3pwO.framer-v-mfcq8v.framer-1hqskz8 { padding: 80px 10px 120px 10px; width: 390px; }",
  ".framer-l3pwO.framer-v-mfcq8v .framer-1haa6xn { flex-direction: column; gap: 60px; }",
  ".framer-l3pwO.framer-v-mfcq8v .framer-1x6fvk5, .framer-l3pwO.framer-v-mfcq8v .framer-jinp0w, .framer-l3pwO.framer-v-mfcq8v .framer-aucqqm, .framer-l3pwO.framer-v-mfcq8v .framer-1jyjq70, .framer-l3pwO.framer-v-mfcq8v .framer-b3md50 { flex: none; width: 100%; }",
  ".framer-l3pwO.framer-v-mfcq8v .framer-3efy5k, .framer-l3pwO.framer-v-mfcq8v .framer-c742n6, .framer-l3pwO.framer-v-mfcq8v .framer-1je8oxk, .framer-l3pwO.framer-v-mfcq8v .framer-1vmp5p2, .framer-l3pwO.framer-v-mfcq8v .framer-cyld6i { padding: 0px 10px 0px 10px; }",
  ".framer-l3pwO.framer-v-mfcq8v .framer-147t904 { flex-direction: column; gap: 20px; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 485
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"Y4qJMr6hn":{"layout":["fixed","auto"]},"zLkwbJJ3P":{"layout":["fixed","auto"]}}}
 * @framerVariables {"TtemKiaS7":"hideCursor"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerxNVv5vbzH = withCSS(Component, css, "framer-l3pwO");
export default FramerxNVv5vbzH;
FramerxNVv5vbzH.displayName = "Footer";
FramerxNVv5vbzH.defaultProps = { height: 485, width: 1200 };
addPropertyControls(FramerxNVv5vbzH, {
  variant: {
    options: ["SHYUAibwl", "Y4qJMr6hn", "zLkwbJJ3P"],
    optionTitles: ["Desktop", "Tablet", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  TtemKiaS7: { title: "Hide Cursor", type: ControlType.CustomCursor },
});
addFonts(
  FramerxNVv5vbzH,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...ContactInfoFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
FramerxNVv5vbzH.loader = {
  load: (props, context) => {
    const locale = context.locale;
    return Promise.allSettled([forwardLoader(ContactInfo, {}, context)]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerxNVv5vbzH",
      slots: [],
      annotations: {
        framerDisplayContentsDiv: "false",
        framerVariables: '{"TtemKiaS7":"hideCursor"}',
        framerImmutableVariables: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"Y4qJMr6hn":{"layout":["fixed","auto"]},"zLkwbJJ3P":{"layout":["fixed","auto"]}}}',
        framerComponentViewportWidth: "true",
        framerIntrinsicHeight: "485",
        framerContractVersion: "1",
        framerAutoSizeImages: "true",
        framerIntrinsicWidth: "1200",
        framerColorSyntax: "true",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./xNVv5vbzH.map
