// Generated by Framer (36277c8)
import { fontStore } from "framer";
fontStore.loadFonts(["FS;Anton-regular"]);
export const fonts = [
  {
    explicitInter: true,
    fonts: [
      {
        cssFamilyName: "Anton",
        source: "fontshare",
        style: "normal",
        uiFamilyName: "Anton",
        url: "https://framerusercontent.com/third-party-assets/fontshare/wf/TPY5PBRHOSXJ53WNSUYZQYX4FZUMAYNF/YHKM2QXXZHS7MS6DJUZXTGRXMIGWH7K5/PCXT6E5YCQO6SSVLT6UZPPGT7QKGXOUS.woff2",
        weight: "400",
      },
    ],
  },
];
export const css = [
  ".framer-sj711 .framer-styles-preset-cliz78:not(.rich-text-wrapper), .framer-sj711 .framer-styles-preset-cliz78.rich-text-wrapper h2 { --framer-font-family: \"Anton\", \"Anton Placeholder\", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv03' on, 'cv04' on, 'cv09' on, 'cv11' on; --framer-font-size: 80px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-letter-spacing: -0.01em; --framer-line-height: 100%; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; }",
  "@media (max-width: 1599px) and (min-width: 1200px) { .framer-sj711 .framer-styles-preset-cliz78:not(.rich-text-wrapper), .framer-sj711 .framer-styles-preset-cliz78.rich-text-wrapper h2 { --framer-font-family: \"Anton\", \"Anton Placeholder\", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv03' on, 'cv04' on, 'cv09' on, 'cv11' on; --framer-font-size: 64px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-letter-spacing: -0.01em; --framer-line-height: 100%; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; } }",
  "@media (max-width: 1199px) and (min-width: 810px) { .framer-sj711 .framer-styles-preset-cliz78:not(.rich-text-wrapper), .framer-sj711 .framer-styles-preset-cliz78.rich-text-wrapper h2 { --framer-font-family: \"Anton\", \"Anton Placeholder\", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv03' on, 'cv04' on, 'cv09' on, 'cv11' on; --framer-font-size: 48px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-letter-spacing: -0.01em; --framer-line-height: 100%; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; } }",
  "@media (max-width: 809px) and (min-width: 0px) { .framer-sj711 .framer-styles-preset-cliz78:not(.rich-text-wrapper), .framer-sj711 .framer-styles-preset-cliz78.rich-text-wrapper h2 { --framer-font-family: \"Anton\", \"Anton Placeholder\", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv03' on, 'cv04' on, 'cv09' on, 'cv11' on; --framer-font-size: 40px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-letter-spacing: -0.01em; --framer-line-height: 100%; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; } }",
];
export const className = "framer-sj711";
export const __FramerMetadata__ = {
  exports: {
    fonts: { type: "variable", annotations: { framerContractVersion: "1" } },
    css: { type: "variable", annotations: { framerContractVersion: "1" } },
    className: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
