// Generated by Framer (6ca3d35)
import {
  addPropertyControls as e,
  ControlType as t,
  QueryEngine as l,
} from "framer";
import { DatabaseCollection as i } from "./q1cG32MQr-0.js";
import { getRichTextJsonResolver as a } from "./q1cG32MQr-1.js";
let r = {
    createdAt: { isNullable: !0, type: t.Date },
    HFBfDhvAA: { isNullable: !0, type: t.String },
    id: { isNullable: !1, type: t.String },
    L0oL4wrwP: { isNullable: !0, type: t.Link },
    nextItemId: { isNullable: !0, type: t.String },
    previousItemId: { isNullable: !0, type: t.String },
    sjWMWJ_Pd: { isNullable: !0, type: t.ResponsiveImage },
    uNZJRc4c1: { isNullable: !0, type: t.String },
    updatedAt: { isNullable: !0, type: t.Date },
    Xs_7TXzZF: { isNullable: !0, type: t.Link },
    YDhikg44Y: { isNullable: !0, type: t.String },
    zHDJZqEC3: { isNullable: !0, type: t.Link },
  },
  n = [],
  u = (e) => {
    let t = n[e];
    if (t) return t().then((e) => e.default);
  },
  p = {},
  o = a(p),
  d = new l(),
  c = {
    collectionByLocaleId: {
      default: new i({
        chunks: [
          new URL(
            "./q1cG32MQr-chunk-default-0.framercms",
            import.meta.url
          ).href.replace("/modules/", "/cms/"),
        ],
        id: "2f176c59-511f-48f0-90d4-e986b3775930default",
        indexes: [],
        resolveRichText: o,
        resolveVectorSetItem: u,
        schema: r,
      }),
    },
    displayName: "Team",
    id: "2f176c59-511f-48f0-90d4-e986b3775930",
  };
export default c;
e(c, {
  YDhikg44Y: { defaultValue: "", title: "Name", type: t.String },
  HFBfDhvAA: { defaultValue: "", title: "Role", type: t.String },
  sjWMWJ_Pd: { title: "image", type: t.ResponsiveImage },
  zHDJZqEC3: { title: "LinkedIn", type: t.Link },
  Xs_7TXzZF: { title: "X(Twitter)", type: t.Link },
  L0oL4wrwP: { title: "Instagram", type: t.Link },
  uNZJRc4c1: { preventLocalization: !1, title: "Slug", type: t.String },
  createdAt: { title: "Created", type: t.Date },
  updatedAt: { title: "Updated", type: t.Date },
  previousItemId: {
    dataIdentifier: "local-module:collection/q1cG32MQr:default",
    title: "Previous",
    type: t.CollectionReference,
  },
  nextItemId: {
    dataIdentifier: "local-module:collection/q1cG32MQr:default",
    title: "Next",
    type: t.CollectionReference,
  },
});
export const enumToDisplayNameFunctions = {};
export const utils = {
  async getSlugByRecordId(e, t) {
    let [l] = await d.query(
      {
        from: { data: c, type: "Collection" },
        limit: { type: "LiteralValue", value: 1 },
        select: [{ name: "uNZJRc4c1", type: "Identifier" }],
        where: {
          left: { name: "id", type: "Identifier" },
          operator: "==",
          right: { type: "LiteralValue", value: e },
          type: "BinaryOperation",
        },
      },
      t
    );
    return l?.uNZJRc4c1;
  },
  async getRecordIdBySlug(e, t) {
    let [l] = await d.query(
      {
        from: { data: c, type: "Collection" },
        limit: { type: "LiteralValue", value: 1 },
        select: [{ name: "id", type: "Identifier" }],
        where: {
          left: { name: "uNZJRc4c1", type: "Identifier" },
          operator: "==",
          right: { type: "LiteralValue", value: e },
          type: "BinaryOperation",
        },
      },
      t
    );
    return l?.id;
  },
};
export const __FramerMetadata__ = {
  exports: {
    utils: { type: "variable", annotations: { framerContractVersion: "1" } },
    default: {
      type: "data",
      name: "data",
      annotations: {
        framerContractVersion: "1",
        framerCollectionId: "q1cG32MQr",
        framerRecordIdKey: "id",
        framerColorSyntax: "false",
        framerCollectionUtils: "1",
        framerAutoSizeImages: "true",
        framerEnumToDisplayNameUtils: "2",
        framerData: "true",
        framerSlug: "uNZJRc4c1",
      },
    },
    enumToDisplayNameFunctions: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
