// Generated by Framer (7bfce40)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  RichText,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useOnVariantChange,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/1IHOpfVySljoH91lcVB1/nnpziJQhgF6L8qGUCrDP/pTInn5AJN.js";
const cycleOrder = [
  "MK9Jya3Fv",
  "W342zinWp",
  "QWSe9SFqm",
  "m3qHudAWE",
  "Cwt9qyux_",
];
const serializationHash = "framer-kTfZl";
const variantClassNames = {
  Cwt9qyux_: "framer-v-1pc4ctg",
  m3qHudAWE: "framer-v-tow6cp",
  MK9Jya3Fv: "framer-v-7m0p9j",
  QWSe9SFqm: "framer-v-1p7vx61",
  W342zinWp: "framer-v-hs2d82",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const iLm7yzzbn = undefined;
const QzeYYZ4xt = undefined;
const Z5Mx1XAqD = undefined;
const SveIgQnV4 = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const animation = {
  opacity: 1,
  rotate: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 200,
};
const transition2 = { bounce: 0, delay: 0.025, duration: 0.8, type: "spring" };
const textEffect = {
  effect: animation,
  startDelay: 0.3,
  tokenization: "character",
  transition: transition2,
  trigger: "onMount",
  type: "appear",
};
const transition3 = { bounce: 0, delay: 0.075, duration: 0.8, type: "spring" };
const textEffect1 = {
  effect: animation,
  repeat: false,
  startDelay: 0,
  tokenization: "character",
  transition: transition3,
  trigger: "onMount",
  type: "appear",
};
const textEffect2 = {
  effect: animation,
  startDelay: 0,
  tokenization: "character",
  transition: transition3,
  trigger: "onMount",
  type: "appear",
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  B: "W342zinWp",
  C: "QWSe9SFqm",
  D: "m3qHudAWE",
  End: "Cwt9qyux_",
  Start: "MK9Jya3Fv",
};
const Variants = motion.create(React.Fragment);
const getProps = ({ a, b, c, d, height, id, width, ...props }) => {
  return {
    ...props,
    iLm7yzzbn: a ?? props.iLm7yzzbn ?? "Avataar Visora",
    QzeYYZ4xt: b ?? props.QzeYYZ4xt ?? "Brave",
    SveIgQnV4: d ?? props.SveIgQnV4 ?? "sharp",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "MK9Jya3Fv",
    Z5Mx1XAqD: c ?? props.Z5Mx1XAqD ?? "Loud",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    iLm7yzzbn,
    QzeYYZ4xt,
    Z5Mx1XAqD,
    SveIgQnV4,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "MK9Jya3Fv",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onAppear1kppw80 = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("W342zinWp", true), 1200);
  });
  const onAppear1gdttz7 = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("QWSe9SFqm", true), 1e3);
  });
  const onAppear1b0pufb = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("m3qHudAWE", true), 1e3);
  });
  const onAppearuqp0h1 = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("Cwt9qyux_", true), 1e3);
  });
  const onAppear2lonid = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("W342zinWp", true), 4e3);
  });
  useOnVariantChange(baseVariant, {
    Cwt9qyux_: onAppear2lonid,
    default: onAppear1kppw80,
    m3qHudAWE: onAppearuqp0h1,
    QWSe9SFqm: onAppear1b0pufb,
    W342zinWp: onAppear1gdttz7,
  });
  const sharedStyleClassNames = [sharedStyle.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (
      ["W342zinWp", "QWSe9SFqm", "m3qHudAWE", "Cwt9qyux_"].includes(baseVariant)
    )
      return false;
    return true;
  };
  const isDisplayed1 = () => {
    if (baseVariant === "W342zinWp") return true;
    return false;
  };
  const isDisplayed2 = () => {
    if (baseVariant === "QWSe9SFqm") return true;
    return false;
  };
  const isDisplayed3 = () => {
    if (baseVariant === "m3qHudAWE") return true;
    return false;
  };
  const isDisplayed4 = () => {
    if (baseVariant === "Cwt9qyux_") return true;
    return false;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-7m0p9j",
            className,
            classNames
          ),
          "data-framer-name": "Start",
          "data-highlight": true,
          layoutDependency: layoutDependency,
          layoutId: "MK9Jya3Fv",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            {
              Cwt9qyux_: { "data-framer-name": "End" },
              m3qHudAWE: { "data-framer-name": "D" },
              QWSe9SFqm: { "data-framer-name": "C" },
              W342zinWp: { "data-framer-name": "B" },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  className: "framer-styles-preset-1o5m3vt",
                  "data-styles-preset": "pTInn5AJN",
                  dir: "auto",
                  children: "0",
                }),
              }),
              className: "framer-1lp4uv4",
              "data-framer-name": "Placeholder",
              fonts: ["Inter"],
              layoutDependency: layoutDependency,
              layoutId: "ZuFO4hA7D",
              style: {
                "--framer-link-text-color": "rgb(0, 153, 255)",
                "--framer-link-text-decoration": "underline",
                opacity: 0,
              },
              verticalAlignment: "top",
              withExternalLayout: true,
            }),
            isDisplayed() &&
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-1o5m3vt",
                    "data-styles-preset": "pTInn5AJN",
                    dir: "auto",
                    children: "Avataar Visora",
                  }),
                }),
                className: "framer-4l5no3",
                "data-framer-name": "A In",
                effect: textEffect,
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "gNyCsXVHj",
                style: {
                  "--framer-link-text-color": "rgb(0, 153, 255)",
                  "--framer-link-text-decoration": "underline",
                },
                text: iLm7yzzbn,
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
            isDisplayed1() &&
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-1o5m3vt",
                    "data-styles-preset": "pTInn5AJN",
                    dir: "auto",
                    children: "Avataar Visora",
                  }),
                }),
                className: "framer-1uob31e",
                "data-framer-name": "A Out",
                effect: textEffect1,
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "xhGLreiTC",
                style: {
                  "--framer-link-text-color": "rgb(0, 153, 255)",
                  "--framer-link-text-decoration": "underline",
                },
                text: iLm7yzzbn,
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
            isDisplayed1() &&
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-1o5m3vt",
                    "data-styles-preset": "pTInn5AJN",
                    dir: "auto",
                    children: "Brave",
                  }),
                }),
                className: "framer-y7gupf",
                "data-framer-name": "B In",
                effect: textEffect2,
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "F0UoNY_ef",
                style: {
                  "--framer-link-text-color": "rgb(0, 153, 255)",
                  "--framer-link-text-decoration": "underline",
                },
                text: QzeYYZ4xt,
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
            isDisplayed2() &&
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-1o5m3vt",
                    "data-styles-preset": "pTInn5AJN",
                    dir: "auto",
                    children: "Brave",
                  }),
                }),
                className: "framer-104qcn4",
                "data-framer-name": "B Out",
                effect: textEffect1,
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "vCJIEQNNc",
                style: {
                  "--framer-link-text-color": "rgb(0, 153, 255)",
                  "--framer-link-text-decoration": "underline",
                },
                text: QzeYYZ4xt,
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
            isDisplayed2() &&
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-1o5m3vt",
                    "data-styles-preset": "pTInn5AJN",
                    dir: "auto",
                    children: "Loud",
                  }),
                }),
                className: "framer-729j3p",
                "data-framer-name": "C In",
                effect: textEffect2,
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "rVfK4UFJl",
                style: {
                  "--framer-link-text-color": "rgb(0, 153, 255)",
                  "--framer-link-text-decoration": "underline",
                },
                text: Z5Mx1XAqD,
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
            isDisplayed3() &&
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-1o5m3vt",
                    "data-styles-preset": "pTInn5AJN",
                    dir: "auto",
                    children: "Loud",
                  }),
                }),
                className: "framer-1qte9fv",
                "data-framer-name": "C Out",
                effect: textEffect1,
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "krqZf6Mqd",
                style: {
                  "--framer-link-text-color": "rgb(0, 153, 255)",
                  "--framer-link-text-decoration": "underline",
                },
                text: Z5Mx1XAqD,
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
            isDisplayed3() &&
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-1o5m3vt",
                    "data-styles-preset": "pTInn5AJN",
                    dir: "auto",
                    children: "sharp",
                  }),
                }),
                className: "framer-1ehsr98",
                "data-framer-name": "D In",
                effect: textEffect2,
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "kXIU8v7uI",
                style: {
                  "--framer-link-text-color": "rgb(0, 153, 255)",
                  "--framer-link-text-decoration": "underline",
                },
                text: SveIgQnV4,
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
            isDisplayed4() &&
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-1o5m3vt",
                    "data-styles-preset": "pTInn5AJN",
                    dir: "auto",
                    children: "sharp",
                  }),
                }),
                className: "framer-txw6ge",
                "data-framer-name": "D Out",
                effect: textEffect1,
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "PA8vRGqCT",
                style: {
                  "--framer-link-text-color": "rgb(0, 153, 255)",
                  "--framer-link-text-decoration": "underline",
                },
                text: SveIgQnV4,
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
            isDisplayed4() &&
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-1o5m3vt",
                    "data-styles-preset": "pTInn5AJN",
                    dir: "auto",
                    children: "Avataar Visora",
                  }),
                }),
                className: "framer-1h0hdp3",
                "data-framer-name": "A In",
                effect: textEffect2,
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "DLYe8giF3",
                style: {
                  "--framer-link-text-color": "rgb(0, 153, 255)",
                  "--framer-link-text-decoration": "underline",
                },
                text: iLm7yzzbn,
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-kTfZl.framer-1f9zd0n, .framer-kTfZl .framer-1f9zd0n { display: block; }",
  ".framer-kTfZl.framer-7m0p9j { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 758px; }",
  ".framer-kTfZl .framer-1lp4uv4 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
  ".framer-kTfZl .framer-4l5no3, .framer-kTfZl .framer-y7gupf, .framer-kTfZl .framer-729j3p, .framer-kTfZl .framer-1ehsr98, .framer-kTfZl .framer-1h0hdp3 { flex: none; height: auto; left: 0px; position: absolute; top: 0px; white-space: pre; width: auto; z-index: 1; }",
  ".framer-kTfZl .framer-1uob31e, .framer-kTfZl .framer-104qcn4, .framer-kTfZl .framer-1qte9fv, .framer-kTfZl .framer-txw6ge { flex: none; height: auto; left: 0px; position: absolute; top: -200px; white-space: pre; width: auto; z-index: 1; }",
  ...sharedStyle.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 178
 * @framerIntrinsicWidth 758
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"W342zinWp":{"layout":["fixed","auto"]},"QWSe9SFqm":{"layout":["fixed","auto"]},"m3qHudAWE":{"layout":["fixed","auto"]},"Cwt9qyux_":{"layout":["fixed","auto"]}}}
 * @framerVariables {"iLm7yzzbn":"a","QzeYYZ4xt":"b","Z5Mx1XAqD":"c","SveIgQnV4":"d"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerBhI04XdHE = withCSS(Component, css, "framer-kTfZl");
export default FramerBhI04XdHE;
FramerBhI04XdHE.displayName = "Rolling Title";
FramerBhI04XdHE.defaultProps = { height: 178, width: 758 };
addPropertyControls(FramerBhI04XdHE, {
  variant: {
    options: ["MK9Jya3Fv", "W342zinWp", "QWSe9SFqm", "m3qHudAWE", "Cwt9qyux_"],
    optionTitles: ["Start", "B", "C", "D", "End"],
    title: "Variant",
    type: ControlType.Enum,
  },
  iLm7yzzbn: {
    defaultValue: "Avataar Visora",
    displayTextArea: false,
    title: "A",
    type: ControlType.String,
  },
  oniLm7yzzbnChange: { changes: "iLm7yzzbn", type: ControlType.ChangeHandler },
  QzeYYZ4xt: {
    defaultValue: "Brave",
    displayTextArea: false,
    title: "B",
    type: ControlType.String,
  },
  onQzeYYZ4xtChange: { changes: "QzeYYZ4xt", type: ControlType.ChangeHandler },
  Z5Mx1XAqD: {
    defaultValue: "Loud",
    displayTextArea: false,
    title: "C",
    type: ControlType.String,
  },
  onZ5Mx1XAqDChange: { changes: "Z5Mx1XAqD", type: ControlType.ChangeHandler },
  SveIgQnV4: {
    defaultValue: "sharp",
    displayTextArea: false,
    title: "D",
    type: ControlType.String,
  },
  onSveIgQnV4Change: { changes: "SveIgQnV4", type: ControlType.ChangeHandler },
});
addFonts(
  FramerBhI04XdHE,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...getFontsFromSharedStyle(sharedStyle.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerBhI04XdHE",
      slots: [],
      annotations: {
        framerIntrinsicWidth: "758",
        framerDisplayContentsDiv: "false",
        framerColorSyntax: "true",
        framerComponentViewportWidth: "true",
        framerContractVersion: "1",
        framerImmutableVariables: "true",
        framerIntrinsicHeight: "178",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"W342zinWp":{"layout":["fixed","auto"]},"QWSe9SFqm":{"layout":["fixed","auto"]},"m3qHudAWE":{"layout":["fixed","auto"]},"Cwt9qyux_":{"layout":["fixed","auto"]}}}',
        framerVariables:
          '{"iLm7yzzbn":"a","QzeYYZ4xt":"b","Z5Mx1XAqD":"c","SveIgQnV4":"d"}',
        framerAutoSizeImages: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./BhI04XdHE.map
