// Generated by Framer (7bfce40)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  forwardLoader,
  getFonts,
  getFontsFromSharedStyle,
  ResolveLinks,
  RichText,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useRouter,
  useVariantState,
  withCodeBoundaryForOverrides,
  withCSS,
  withFX,
  withOptimizedAppearEffect,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import { withBottomStickyScroll } from "https://framerusercontent.com/modules/70Ki8AmEPymD1gT8CDTr/bA4yDZF7SXRUbvxOjqH7/StyckyBottom.js";
import * as sharedStyle1 from "https://framerusercontent.com/modules/GgteY8irBGfUzh8z4mh2/NzDgB7DilEKK0dJEeHtg/mMKAraaKM.js";
import * as sharedStyle from "https://framerusercontent.com/modules/1IHOpfVySljoH91lcVB1/nnpziJQhgF6L8qGUCrDP/pTInn5AJN.js";
import HR from "https://framerusercontent.com/modules/jN6RM4ZT8n8DNQNGfUB9/QR965Wc6dTBsr7GqaKuU/E_eUSw7wp.js";
import MainButton from "https://framerusercontent.com/modules/LCVE0KtQYdb2UTyP4r8C/w2m6bInrHbLrgSQ8kXEv/TOMRBfQdf.js";
import Footer from "https://framerusercontent.com/modules/66AxJh7zrzBmc7TgjyN9/EkS0uQTmR8bqmNSvbjOA/xNVv5vbzH.js";
const MainButtonFonts = getFonts(MainButton);
const SmartComponentScopedContainerWithFXWithOptimizedAppearEffect =
  withOptimizedAppearEffect(withFX(SmartComponentScopedContainer));
const HRFonts = getFonts(HR);
const FooterFonts = getFonts(Footer);
const MotionDivWithBottomStickyScroll14s3pwn = withCodeBoundaryForOverrides(
  motion.div,
  {
    nodeId: "EJhbFZedG",
    override: withBottomStickyScroll,
    scopeId: "HjCqDEKvH",
  }
);
const cycleOrder = ["c2r5LdRrQ", "JbzXxdoSX", "F81V8jesk"];
const serializationHash = "framer-6NbPn";
const variantClassNames = {
  c2r5LdRrQ: "framer-v-1xzscxt",
  F81V8jesk: "framer-v-177d5rx",
  JbzXxdoSX: "framer-v-1ck8edd",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const WVdLsyu8b = undefined;
const transition1 = { bounce: 0, delay: 0, duration: 0.6, type: "spring" };
const animation = {
  opacity: 1,
  rotate: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 240,
};
const transition2 = { bounce: 0, delay: 0.025, duration: 0.8, type: "spring" };
const textEffect = {
  effect: animation,
  tokenization: "character",
  transition: transition2,
  trigger: "onMount",
  type: "appear",
};
const textEffect1 = {
  effect: animation,
  startDelay: 0.1,
  tokenization: "character",
  transition: transition2,
  trigger: "onMount",
  type: "appear",
};
const animation1 = {
  opacity: 0.001,
  rotate: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 10,
};
const transition3 = { bounce: 0, delay: 0.025, duration: 0.4, type: "spring" };
const textEffect2 = {
  effect: animation1,
  tokenization: "word",
  transition: transition3,
  trigger: "onMount",
  type: "appear",
};
const transition4 = { bounce: 0, delay: 0.1, duration: 0.8, type: "spring" };
const animation2 = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition4,
  x: 0,
  y: 0,
};
const animation3 = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 22,
};
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  Desktop: "c2r5LdRrQ",
  Phone: "F81V8jesk",
  Tablet: "JbzXxdoSX",
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, hideCursor, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "c2r5LdRrQ",
    WVdLsyu8b: hideCursor ?? props.WVdLsyu8b,
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, WVdLsyu8b, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "c2r5LdRrQ",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const router = useRouter();
  const isDisplayed = () => {
    if (["JbzXxdoSX", "F81V8jesk"].includes(baseVariant)) return false;
    return true;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1xzscxt",
            className,
            classNames
          ),
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "c2r5LdRrQ",
          ref: refBinding,
          style: {
            backgroundColor:
              "var(--token-280bd9a0-bf37-41b4-a3c3-9a122b679a65, rgb(255, 255, 255))",
            ...style,
          },
          ...addPropertyOverrides(
            {
              F81V8jesk: { "data-framer-name": "Phone" },
              JbzXxdoSX: { "data-framer-name": "Tablet" },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-y4r32f",
              "data-framer-name": "Main Container",
              layoutDependency: layoutDependency,
              layoutId: "PxvkWppo9",
              style: {
                backgroundColor:
                  "var(--token-280bd9a0-bf37-41b4-a3c3-9a122b679a65, rgb(255, 255, 255))",
              },
              children: [
                /*#__PURE__*/ _jsxs(motion.div, {
                  className: "framer-1ok469l",
                  "data-framer-name": "Text Container",
                  layoutDependency: layoutDependency,
                  layoutId: "NtgsGAzSu",
                  children: [
                    /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-15h2bxs",
                      "data-framer-name": "Text Container",
                      layoutDependency: layoutDependency,
                      layoutId: "BcHTtY9gF",
                      children: /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h1, {
                            className: "framer-styles-preset-1o5m3vt",
                            "data-styles-preset": "pTInn5AJN",
                            dir: "auto",
                            children: "404",
                          }),
                        }),
                        className: "framer-lklu7s",
                        effect: textEffect,
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "T2EHfcZu1",
                        style: {
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }),
                    }),
                    /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-kpapwe",
                      "data-framer-name": "Text Container",
                      layoutDependency: layoutDependency,
                      layoutId: "Oj_qoEQ6t",
                      children: /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h2, {
                            className: "framer-styles-preset-1o5m3vt",
                            "data-styles-preset": "pTInn5AJN",
                            dir: "auto",
                            children: "Not Found",
                          }),
                        }),
                        className: "framer-x0iqr3",
                        effect: textEffect1,
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "ht7cW64aU",
                        style: {
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }),
                    }),
                  ],
                }),
                /*#__PURE__*/ _jsxs(motion.div, {
                  className: "framer-1k7gs0k",
                  "data-framer-name": "Container",
                  layoutDependency: layoutDependency,
                  layoutId: "QJCIA2Lt6",
                  children: [
                    /*#__PURE__*/ _jsx(RichText, {
                      __fromCanvasComponent: true,
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsxs(motion.p, {
                          className: "framer-styles-preset-1rymzzk",
                          "data-styles-preset": "mMKAraaKM",
                          dir: "auto",
                          children: [
                            /*#__PURE__*/ _jsxs(motion.strong, {
                              children: [
                                "This page doesn’t exist,",
                                /*#__PURE__*/ _jsx(motion.br, {}),
                              ],
                            }),
                            "but the rest of the site does.",
                          ],
                        }),
                      }),
                      className: "framer-tphrbz",
                      effect: textEffect2,
                      fonts: ["Inter", "Inter-Bold"],
                      layoutDependency: layoutDependency,
                      layoutId: "NAfoh_nX1",
                      style: {
                        "--framer-link-text-color": "rgb(0, 153, 255)",
                        "--framer-link-text-decoration": "underline",
                      },
                      verticalAlignment: "top",
                      withExternalLayout: true,
                    }),
                    /*#__PURE__*/ _jsx(ResolveLinks, {
                      links: [
                        {
                          href: { webPageId: "augiA20Il" },
                          implicitPathVariables: undefined,
                        },
                        {
                          href: { webPageId: "augiA20Il" },
                          implicitPathVariables: undefined,
                        },
                        {
                          href: { webPageId: "augiA20Il" },
                          implicitPathVariables: undefined,
                        },
                      ],
                      children: (resolvedLinks) =>
                        /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                          height: 20,
                          y:
                            (componentViewport?.y || 0) +
                            0 +
                            (((componentViewport?.height || 1286) - 0 - 1486) /
                              2 +
                              0 +
                              0) +
                            32 +
                            624 +
                            0 +
                            292,
                          ...addPropertyOverrides(
                            {
                              F81V8jesk: {
                                y:
                                  (componentViewport?.y || 0) +
                                  0 +
                                  (((componentViewport?.height || 200) -
                                    0 -
                                    1290) /
                                    2 +
                                    0 +
                                    0) +
                                  120 +
                                  440 +
                                  0 +
                                  144,
                              },
                              JbzXxdoSX: {
                                y:
                                  (componentViewport?.y || 0) +
                                  0 +
                                  (((componentViewport?.height || 1311.5) -
                                    0 -
                                    1330) /
                                    2 +
                                    0 +
                                    0) +
                                  120 +
                                  440 +
                                  0 +
                                  144,
                              },
                            },
                            baseVariant,
                            gestureVariant
                          ),
                          children: /*#__PURE__*/ _jsx(
                            SmartComponentScopedContainerWithFXWithOptimizedAppearEffect,
                            {
                              __perspectiveFX: false,
                              __smartComponentFX: true,
                              __targetOpacity: 1,
                              animate: animation2,
                              className: "framer-hoabko-container",
                              "data-framer-appear-id": "hoabko",
                              "data-framer-cursor": WVdLsyu8b,
                              initial: animation3,
                              layoutDependency: layoutDependency,
                              layoutId: "VdOVQxKnh-container",
                              nodeId: "VdOVQxKnh",
                              optimized: true,
                              rendersWithMotion: true,
                              scopeId: "HjCqDEKvH",
                              children: /*#__PURE__*/ _jsx(MainButton, {
                                BhFmKI_CC: resolvedLinks[0],
                                height: "100%",
                                id: "VdOVQxKnh",
                                KKXBGp3Wv:
                                  "var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, rgb(0, 0, 0))",
                                layoutId: "VdOVQxKnh",
                                nhudf0dmF: false,
                                u6m8yRtDy: "Go back Home",
                                variant: matchVariant("vVLd8CW0_"),
                                width: "100%",
                                ...addPropertyOverrides(
                                  {
                                    F81V8jesk: { BhFmKI_CC: resolvedLinks[2] },
                                    JbzXxdoSX: { BhFmKI_CC: resolvedLinks[1] },
                                  },
                                  baseVariant,
                                  gestureVariant
                                ),
                              }),
                            }
                          ),
                        }),
                    }),
                  ],
                }),
              ],
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 1,
              width: componentViewport?.width || "100vw",
              y:
                (componentViewport?.y || 0) +
                0 +
                (((componentViewport?.height || 1286) - 0 - 1486) / 2 +
                  1e3 +
                  0),
              ...addPropertyOverrides(
                {
                  F81V8jesk: {
                    y:
                      (componentViewport?.y || 0) +
                      0 +
                      (((componentViewport?.height || 200) - 0 - 1290) / 2 +
                        804 +
                        0),
                  },
                  JbzXxdoSX: {
                    y:
                      (componentViewport?.y || 0) +
                      0 +
                      (((componentViewport?.height || 1311.5) - 0 - 1330) / 2 +
                        844 +
                        0),
                  },
                },
                baseVariant,
                gestureVariant
              ),
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-fqdcd-container",
                layoutDependency: layoutDependency,
                layoutId: "LoeAUxrov-container",
                nodeId: "LoeAUxrov",
                rendersWithMotion: true,
                scopeId: "HjCqDEKvH",
                children: /*#__PURE__*/ _jsx(HR, {
                  height: "100%",
                  id: "LoeAUxrov",
                  layoutId: "LoeAUxrov",
                  style: { width: "100%" },
                  variant: matchVariant("EloeDt_Av"),
                  width: "100%",
                  ...addPropertyOverrides(
                    {
                      F81V8jesk: { variant: matchVariant("bDu_rpRlI") },
                      JbzXxdoSX: { variant: matchVariant("gYcI3A2jy") },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
              }),
            }),
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-obve1i",
              "data-framer-name": "Footer Container",
              layoutDependency: layoutDependency,
              layoutId: "H7k2J5X8R",
              children: [
                /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                  height: 485,
                  width: `max(${componentViewport?.width || "100vw"}, 1px)`,
                  y:
                    (componentViewport?.y || 0) +
                    0 +
                    (((componentViewport?.height || 1286) - 0 - 1486) / 2 +
                      1001 +
                      0) +
                    0,
                  ...addPropertyOverrides(
                    {
                      F81V8jesk: {
                        y:
                          (componentViewport?.y || 0) +
                          0 +
                          (((componentViewport?.height || 200) - 0 - 1290) / 2 +
                            805 +
                            0) +
                          0,
                      },
                      JbzXxdoSX: {
                        y:
                          (componentViewport?.y || 0) +
                          0 +
                          (((componentViewport?.height || 1311.5) - 0 - 1330) /
                            2 +
                            845 +
                            0) +
                          0,
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                  children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                    className: "framer-28ujvt-container",
                    "data-framer-name": "Footer",
                    layoutDependency: layoutDependency,
                    layoutId: "zIk0JPn16-container",
                    name: "Footer",
                    nodeId: "zIk0JPn16",
                    rendersWithMotion: true,
                    scopeId: "HjCqDEKvH",
                    children: /*#__PURE__*/ _jsx(Footer, {
                      height: "100%",
                      id: "zIk0JPn16",
                      layoutId: "zIk0JPn16",
                      name: "Footer",
                      style: { width: "100%" },
                      TtemKiaS7: WVdLsyu8b,
                      variant: matchVariant("SHYUAibwl"),
                      width: "100%",
                      ...addPropertyOverrides(
                        {
                          F81V8jesk: { variant: matchVariant("zLkwbJJ3P") },
                          JbzXxdoSX: { variant: matchVariant("Y4qJMr6hn") },
                        },
                        baseVariant,
                        gestureVariant
                      ),
                    }),
                  }),
                }),
                isDisplayed() &&
                  /*#__PURE__*/ _jsx(motion.div, {
                    className: "framer-q6g3h1",
                    "data-framer-name": "Sticky Footer Container",
                    layoutDependency: layoutDependency,
                    layoutId: "i2o4xpgMZ",
                    children: /*#__PURE__*/ _jsx(
                      MotionDivWithBottomStickyScroll14s3pwn,
                      {
                        className: "framer-14s3pwn",
                        "data-framer-name": "Footer Container",
                        layoutDependency: layoutDependency,
                        layoutId: "EJhbFZedG",
                        children: /*#__PURE__*/ _jsx(
                          ComponentViewportProvider,
                          {
                            height: 485,
                            width: `max(${
                              componentViewport?.width || "100vw"
                            }, 1px)`,
                            y:
                              (componentViewport?.y || 0) +
                              0 +
                              (((componentViewport?.height || 1286) -
                                0 -
                                1486) /
                                2 +
                                1001 +
                                0) +
                              485 -
                              970 +
                              0 +
                              0,
                            children: /*#__PURE__*/ _jsx(
                              SmartComponentScopedContainer,
                              {
                                className: "framer-gcn2vi-container",
                                "data-framer-name": "Footer",
                                layoutDependency: layoutDependency,
                                layoutId: "YsKrWp3nB-container",
                                name: "Footer",
                                nodeId: "YsKrWp3nB",
                                rendersWithMotion: true,
                                scopeId: "HjCqDEKvH",
                                children: /*#__PURE__*/ _jsx(Footer, {
                                  height: "100%",
                                  id: "YsKrWp3nB",
                                  layoutId: "YsKrWp3nB",
                                  name: "Footer",
                                  style: { width: "100%" },
                                  TtemKiaS7: WVdLsyu8b,
                                  variant: matchVariant("SHYUAibwl"),
                                  width: "100%",
                                }),
                              }
                            ),
                          }
                        ),
                      }
                    ),
                  }),
              ],
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-6NbPn.framer-a19bhd, .framer-6NbPn .framer-a19bhd { display: block; }",
  ".framer-6NbPn.framer-1xzscxt { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1200px; }",
  ".framer-6NbPn .framer-y4r32f { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: calc(var(--framer-viewport-height, 100vh) * 1); justify-content: center; overflow: visible; padding: 32px 40px 32px 40px; position: relative; width: 100%; z-index: 2; }",
  ".framer-6NbPn .framer-1ok469l { align-content: center; align-items: center; display: flex; flex: 2 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: 1px; justify-content: flex-end; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
  ".framer-6NbPn .framer-15h2bxs, .framer-6NbPn .framer-kpapwe { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
  ".framer-6NbPn .framer-lklu7s { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-6NbPn .framer-x0iqr3 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-6NbPn .framer-1k7gs0k { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: 1px; justify-content: flex-end; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
  ".framer-6NbPn .framer-tphrbz { --framer-text-wrap-override: balance; -webkit-user-select: auto; flex: none; height: auto; max-width: 280px; position: relative; user-select: auto; width: 100%; z-index: 1; }",
  ".framer-6NbPn .framer-hoabko-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-6NbPn .framer-fqdcd-container { flex: none; height: auto; position: relative; width: 100%; z-index: 2; }",
  ".framer-6NbPn .framer-obve1i { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 0; }",
  ".framer-6NbPn .framer-28ujvt-container, .framer-6NbPn .framer-gcn2vi-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
  ".framer-6NbPn .framer-q6g3h1 { align-content: flex-start; align-items: flex-start; bottom: 0px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 200%; justify-content: center; left: 0px; overflow: visible; padding: 0px; position: absolute; right: 0px; }",
  ".framer-6NbPn .framer-14s3pwn { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
  ".framer-6NbPn.framer-v-1ck8edd.framer-1xzscxt { width: 810px; }",
  ".framer-6NbPn.framer-v-1ck8edd .framer-y4r32f { gap: 80px; height: min-content; padding: 120px 30px 120px 30px; }",
  ".framer-6NbPn.framer-v-1ck8edd .framer-1ok469l, .framer-6NbPn.framer-v-1ck8edd .framer-1k7gs0k, .framer-6NbPn.framer-v-177d5rx .framer-1ok469l, .framer-6NbPn.framer-v-177d5rx .framer-1k7gs0k { flex: none; height: min-content; }",
  ".framer-6NbPn.framer-v-177d5rx.framer-1xzscxt { width: 390px; }",
  ".framer-6NbPn.framer-v-177d5rx .framer-y4r32f { gap: 80px; height: min-content; padding: 120px 20px 80px 20px; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 1286
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"JbzXxdoSX":{"layout":["fixed","auto"]},"F81V8jesk":{"layout":["fixed","auto"]}}}
 * @framerVariables {"WVdLsyu8b":"hideCursor"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerHjCqDEKvH = withCSS(Component, css, "framer-6NbPn");
export default FramerHjCqDEKvH;
FramerHjCqDEKvH.displayName = "404 Page";
FramerHjCqDEKvH.defaultProps = { height: 1286, width: 1200 };
addPropertyControls(FramerHjCqDEKvH, {
  variant: {
    options: ["c2r5LdRrQ", "JbzXxdoSX", "F81V8jesk"],
    optionTitles: ["Desktop", "Tablet", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  WVdLsyu8b: { title: "Hide Cursor", type: ControlType.CustomCursor },
});
addFonts(
  FramerHjCqDEKvH,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
          weight: "700",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
          weight: "700",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
          weight: "700",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
          weight: "700",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
          weight: "700",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/syRNPWzAMIrcJ3wIlPIP43KjQs.woff2",
          weight: "700",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
          weight: "700",
        },
      ],
    },
    ...MainButtonFonts,
    ...HRFonts,
    ...FooterFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
FramerHjCqDEKvH.loader = {
  load: (props, context) => {
    const locale = context.locale;
    return Promise.allSettled([
      forwardLoader(MainButton, {}, context),
      forwardLoader(HR, {}, context),
      forwardLoader(Footer, {}, context),
    ]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerHjCqDEKvH",
      slots: [],
      annotations: {
        framerDisplayContentsDiv: "false",
        framerAutoSizeImages: "true",
        framerImmutableVariables: "true",
        framerContractVersion: "1",
        framerIntrinsicHeight: "1286",
        framerIntrinsicWidth: "1200",
        framerColorSyntax: "true",
        framerComponentViewportWidth: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"JbzXxdoSX":{"layout":["fixed","auto"]},"F81V8jesk":{"layout":["fixed","auto"]}}}',
        framerVariables: '{"WVdLsyu8b":"hideCursor"}',
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
