// Generated by Framer (b354274)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  RichText,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Clipboard from "https://framerusercontent.com/modules/Hj20QU19p80mpYsvesiZ/r7KU3d0jY4jnUQG5z44O/Clipboard.js";
import * as sharedStyle from "https://framerusercontent.com/modules/GgteY8irBGfUzh8z4mh2/NzDgB7DilEKK0dJEeHtg/mMKAraaKM.js";
const ClipboardFonts = getFonts(Clipboard);
const enabledGestures = { PSoUFcguU: { hover: true } };
const cycleOrder = ["PSoUFcguU", "XKzYnHcII"];
const serializationHash = "framer-O8xrf";
const variantClassNames = {
  PSoUFcguU: "framer-v-1tcyn71",
  XKzYnHcII: "framer-v-19l3cef",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const xqkK9bvTR = undefined;
const gaDQBDyGh = undefined;
const transition1 = { bounce: 0, delay: 0, duration: 0.6, type: "spring" };
const transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = { Copied: "XKzYnHcII", Copy: "PSoUFcguU" };
const Variants = motion.create(React.Fragment);
const getProps = ({ emailAddress, height, iconFill, id, width, ...props }) => {
  return {
    ...props,
    gaDQBDyGh: emailAddress ?? props.gaDQBDyGh ?? "hello@world.com",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "PSoUFcguU",
    xqkK9bvTR:
      iconFill ??
      props.xqkK9bvTR ??
      "var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, rgb(0, 0, 0))",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    gaDQBDyGh,
    xqkK9bvTR,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "PSoUFcguU",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTapj77prl = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    setVariant("XKzYnHcII");
  });
  const onMouseLeaveg1of9l = activeVariantCallback(async (...args) => {
    setGestureState({ isHovered: false });
    setVariant("PSoUFcguU");
  });
  const sharedStyleClassNames = [sharedStyle.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1tcyn71",
            className,
            classNames
          ),
          "data-framer-name": "Copy",
          "data-highlight": true,
          layoutDependency: layoutDependency,
          layoutId: "PSoUFcguU",
          onTap: onTapj77prl,
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            {
              "PSoUFcguU-hover": { "data-framer-name": undefined },
              XKzYnHcII: {
                "data-framer-name": "Copied",
                onMouseLeave: onMouseLeaveg1of9l,
              },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-148omz6",
              "data-framer-name": "Icon",
              layoutDependency: layoutDependency,
              layoutId: "qkbAC9uWe",
              children: [
                /*#__PURE__*/ _jsx(motion.section, {
                  className: "framer-uptisk",
                  layoutDependency: layoutDependency,
                  layoutId: "DXcK8O1vQ",
                  style: { backgroundColor: xqkK9bvTR },
                }),
                /*#__PURE__*/ _jsx(motion.section, {
                  className: "framer-osobar",
                  layoutDependency: layoutDependency,
                  layoutId: "o64guKbmV",
                  style: { backgroundColor: xqkK9bvTR },
                }),
                /*#__PURE__*/ _jsx(motion.section, {
                  className: "framer-ck976w",
                  layoutDependency: layoutDependency,
                  layoutId: "uAr0s3mgc",
                  style: { backgroundColor: xqkK9bvTR },
                }),
                /*#__PURE__*/ _jsx(motion.section, {
                  className: "framer-k21c1v",
                  layoutDependency: layoutDependency,
                  layoutId: "bsdbbtbsC",
                  style: { backgroundColor: xqkK9bvTR },
                }),
                /*#__PURE__*/ _jsx(motion.section, {
                  className: "framer-pvb1vq",
                  layoutDependency: layoutDependency,
                  layoutId: "tI8KRIL4z",
                  style: { backgroundColor: xqkK9bvTR },
                }),
                /*#__PURE__*/ _jsx(motion.section, {
                  className: "framer-1w5h3fy",
                  layoutDependency: layoutDependency,
                  layoutId: "KapB8tCG0",
                  style: { backgroundColor: xqkK9bvTR },
                }),
              ],
            }),
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  className: "framer-styles-preset-1rymzzk",
                  "data-styles-preset": "mMKAraaKM",
                  dir: "auto",
                  style: {
                    "--framer-text-color":
                      "var(--extracted-r6o4lv, var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, rgb(0, 0, 0)))",
                  },
                  children: "copy address",
                }),
              }),
              className: "framer-1flba38",
              fonts: ["Inter"],
              layoutDependency: layoutDependency,
              layoutId: "PV6bUFPDR",
              style: {
                "--extracted-r6o4lv":
                  "var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, rgb(0, 0, 0))",
                "--framer-link-text-color": "rgb(0, 153, 255)",
                "--framer-link-text-decoration": "underline",
                opacity: 0,
              },
              transformTemplate: transformTemplate1,
              variants: { "PSoUFcguU-hover": { opacity: 1 } },
              verticalAlignment: "top",
              withExternalLayout: true,
            }),
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  className: "framer-styles-preset-1rymzzk",
                  "data-styles-preset": "mMKAraaKM",
                  dir: "auto",
                  style: {
                    "--framer-text-color":
                      "var(--extracted-r6o4lv, var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, rgb(0, 0, 0)))",
                  },
                  children: "copied",
                }),
              }),
              className: "framer-1rx7txo",
              fonts: ["Inter"],
              layoutDependency: layoutDependency,
              layoutId: "otXrsvPta",
              style: {
                "--extracted-r6o4lv":
                  "var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, rgb(0, 0, 0))",
                "--framer-link-text-color": "rgb(0, 153, 255)",
                "--framer-link-text-decoration": "underline",
                opacity: 0,
              },
              transformTemplate: transformTemplate1,
              variants: { XKzYnHcII: { opacity: 1 } },
              verticalAlignment: "top",
              withExternalLayout: true,
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-1js0rt9-container",
                isAuthoredByUser: true,
                isModuleExternal: true,
                layoutDependency: layoutDependency,
                layoutId: "F46r_Pa0f-container",
                nodeId: "F46r_Pa0f",
                rendersWithMotion: true,
                scopeId: "iZ6645930",
                children: /*#__PURE__*/ _jsx(Clipboard, {
                  borderRadius: 0,
                  bottomLeftRadius: 0,
                  bottomRightRadius: 0,
                  color: "rgba(255, 255, 255, 0)",
                  content: gaDQBDyGh,
                  fill: "rgba(0, 102, 255, 0)",
                  font: {},
                  height: "100%",
                  id: "F46r_Pa0f",
                  isMixedBorderRadius: false,
                  label: "",
                  layoutId: "F46r_Pa0f",
                  padding: 0,
                  paddingBottom: 0,
                  paddingLeft: 0,
                  paddingPerSide: false,
                  paddingRight: 0,
                  paddingTop: 0,
                  style: { height: "100%", width: "100%" },
                  success: "Copied!",
                  topLeftRadius: 0,
                  topRightRadius: 0,
                  width: "100%",
                }),
              }),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-O8xrf.framer-1sgopp8, .framer-O8xrf .framer-1sgopp8 { display: block; }",
  ".framer-O8xrf.framer-1tcyn71 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-O8xrf .framer-148omz6 { flex: none; height: 16px; overflow: visible; position: relative; width: 14px; }",
  ".framer-O8xrf .framer-uptisk { flex: none; height: 1px; overflow: visible; position: absolute; right: 0px; top: 0px; width: 11px; }",
  ".framer-O8xrf .framer-osobar { flex: none; height: 12px; overflow: visible; position: absolute; right: 0px; top: 1px; width: 1px; }",
  ".framer-O8xrf .framer-ck976w { flex: none; height: 12px; left: 3px; overflow: visible; position: absolute; top: 1px; width: 1px; }",
  ".framer-O8xrf .framer-k21c1v { bottom: 3px; flex: none; height: 1px; overflow: visible; position: absolute; right: 1px; width: 9px; }",
  ".framer-O8xrf .framer-pvb1vq { bottom: 0px; flex: none; height: 13px; left: 0px; overflow: visible; position: absolute; width: 1px; }",
  ".framer-O8xrf .framer-1w5h3fy { bottom: 0px; flex: none; height: 1px; left: 1px; overflow: visible; position: absolute; width: 10px; }",
  ".framer-O8xrf .framer-1flba38, .framer-O8xrf .framer-1rx7txo { flex: none; height: auto; left: 19px; position: absolute; top: 50%; white-space: pre; width: auto; z-index: 1; }",
  ".framer-O8xrf .framer-1js0rt9-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; z-index: 1; }",
  ...sharedStyle.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 16
 * @framerIntrinsicWidth 14
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"XKzYnHcII":{"layout":["auto","auto"]},"Gl42qu2DG":{"layout":["auto","auto"]}}}
 * @framerVariables {"gaDQBDyGh":"emailAddress","xqkK9bvTR":"iconFill"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FrameriZ6645930 = withCSS(Component, css, "framer-O8xrf");
export default FrameriZ6645930;
FrameriZ6645930.displayName = "Copy Email Button";
FrameriZ6645930.defaultProps = { height: 16, width: 14 };
addPropertyControls(FrameriZ6645930, {
  variant: {
    options: ["PSoUFcguU", "XKzYnHcII"],
    optionTitles: ["Copy", "Copied"],
    title: "Variant",
    type: ControlType.Enum,
  },
  gaDQBDyGh: {
    defaultValue: "hello@world.com",
    displayTextArea: true,
    title: "Email Address",
    type: ControlType.String,
  },
  ongaDQBDyGhChange: { changes: "gaDQBDyGh", type: ControlType.ChangeHandler },
  xqkK9bvTR: {
    defaultValue:
      'var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, rgb(0, 0, 0)) /* {"name":"Black"} */',
    title: "Icon Fill",
    type: ControlType.Color,
  },
});
addFonts(
  FrameriZ6645930,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...ClipboardFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FrameriZ6645930",
      slots: [],
      annotations: {
        framerImmutableVariables: "true",
        framerComponentViewportWidth: "true",
        framerDisplayContentsDiv: "false",
        framerContractVersion: "1",
        framerAutoSizeImages: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"XKzYnHcII":{"layout":["auto","auto"]},"Gl42qu2DG":{"layout":["auto","auto"]}}}',
        framerColorSyntax: "true",
        framerIntrinsicHeight: "16",
        framerIntrinsicWidth: "14",
        framerVariables: '{"gaDQBDyGh":"emailAddress","xqkK9bvTR":"iconFill"}',
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./iZ6645930.map
