// Generated by Framer (7bfce40)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  forwardLoader,
  getFonts,
  getFontsFromSharedStyle,
  getPropertyControls,
  Link,
  RichText,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle1 from "https://framerusercontent.com/modules/uIco2kI3WESUlPt0mCzh/RjW3AJ9aakkpVtAmJli5/AUSpdMA0k.js";
import * as sharedStyle from "https://framerusercontent.com/modules/GgteY8irBGfUzh8z4mh2/NzDgB7DilEKK0dJEeHtg/mMKAraaKM.js";
import * as sharedStyle2 from "https://framerusercontent.com/modules/THYeR8PBM8qSAWWrHig9/7uCPEdDQZVF6VyKKTgWa/QeY5Itq9g.js";
import CMSMediaComponent from "https://framerusercontent.com/modules/tvZ2VnsLoWdBWVhzcqSb/oCgi9Q25qR1smsUqFzB1/GFSuRgwr2.js";
import MainButton from "https://framerusercontent.com/modules/LCVE0KtQYdb2UTyP4r8C/w2m6bInrHbLrgSQ8kXEv/TOMRBfQdf.js";
const CMSMediaComponentFonts = getFonts(CMSMediaComponent);
const MainButtonFonts = getFonts(MainButton);
const CMSMediaComponentControls = getPropertyControls(CMSMediaComponent);
const cycleOrder = ["rc9OhqS3b", "cRhL61I0a", "gHBLOWCuj", "QAWLMrsYo"];
const serializationHash = "framer-Hi4jK";
const variantClassNames = {
  cRhL61I0a: "framer-v-8hpb4g",
  gHBLOWCuj: "framer-v-irvxdn",
  QAWLMrsYo: "framer-v-hd5w20",
  rc9OhqS3b: "framer-v-xvjtxm",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const OuW36Qsbp = undefined;
const mlA3cUpG9 = undefined;
const hNNMA1w9T = undefined;
const DlhhthLy6 = undefined;
const O6VZxtSZX = undefined;
const DsuUSgSpS = undefined;
const ua5NLrebe = undefined;
const AfzyTYgJw = undefined;
const iwztgPJCj = undefined;
const transition1 = { duration: 0, type: "tween" };
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  "Desktop A": "rc9OhqS3b",
  "Desktop B": "cRhL61I0a",
  Mobile: "QAWLMrsYo",
  Tablet: "gHBLOWCuj",
};
const Variants = motion.create(React.Fragment);
const humanReadableEnumMap = { Image: "hsLovB1mn", Video: "dGJeCPINe" };
const getProps = ({
  articleTitle,
  height,
  hideCursor,
  id,
  intro,
  link,
  mainImage,
  mainVideo,
  mediaType,
  publishDate,
  tag,
  width,
  ...props
}) => {
  return {
    ...props,
    AfzyTYgJw: articleTitle ?? props.AfzyTYgJw ?? "Article Title",
    DlhhthLy6:
      humanReadableEnumMap[mediaType] ??
      mediaType ??
      props.DlhhthLy6 ??
      "hsLovB1mn",
    DsuUSgSpS: mainVideo ?? props.DsuUSgSpS,
    hNNMA1w9T: tag ?? props.hNNMA1w9T ?? "Tag",
    iwztgPJCj: intro ?? props.iwztgPJCj ?? "Intro",
    mlA3cUpG9: link ?? props.mlA3cUpG9,
    O6VZxtSZX: mainImage ?? props.O6VZxtSZX,
    OuW36Qsbp: hideCursor ?? props.OuW36Qsbp,
    ua5NLrebe: publishDate ?? props.ua5NLrebe ?? "Publish Date",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "rc9OhqS3b",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    hNNMA1w9T,
    ua5NLrebe,
    AfzyTYgJw,
    iwztgPJCj,
    DlhhthLy6,
    O6VZxtSZX,
    DsuUSgSpS,
    mlA3cUpG9,
    OuW36Qsbp,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "rc9OhqS3b",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [
    sharedStyle.className,
    sharedStyle1.className,
    sharedStyle2.className,
  ];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-xvjtxm",
            className,
            classNames
          ),
          "data-framer-name": "Desktop A",
          layoutDependency: layoutDependency,
          layoutId: "rc9OhqS3b",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            {
              cRhL61I0a: { "data-framer-name": "Desktop B" },
              gHBLOWCuj: { "data-framer-name": "Tablet" },
              QAWLMrsYo: { "data-framer-name": "Mobile" },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-16o7xyj",
              "data-framer-name": "Section",
              layoutDependency: layoutDependency,
              layoutId: "R20_h5Clv",
              children: /*#__PURE__*/ _jsx(Link, {
                href: mlA3cUpG9,
                motionChild: true,
                nodeId: "Oiqi1y7Yl",
                openInNewTab: false,
                scopeId: "YbnDYbxmS",
                children: /*#__PURE__*/ _jsxs(motion.a, {
                  className: "framer-1x8p6d5 framer-15mui1k",
                  "data-framer-cursor": OuW36Qsbp,
                  "data-framer-name": "Media Container",
                  layoutDependency: layoutDependency,
                  layoutId: "Oiqi1y7Yl",
                  children: [
                    /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-1rp9qnv",
                      "data-framer-name": "Tag",
                      layoutDependency: layoutDependency,
                      layoutId: "po73dMYmU",
                      style: {
                        backgroundColor:
                          "var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, rgb(0, 0, 0))",
                      },
                      children: /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            className: "framer-styles-preset-1rymzzk",
                            "data-styles-preset": "mMKAraaKM",
                            dir: "auto",
                            style: {
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, var(--token-280bd9a0-bf37-41b4-a3c3-9a122b679a65, rgb(255, 255, 255)))",
                            },
                            children: "Tag",
                          }),
                        }),
                        className: "framer-1uwyufs",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "DB1qJEz8p",
                        style: {
                          "--extracted-r6o4lv":
                            "var(--token-280bd9a0-bf37-41b4-a3c3-9a122b679a65, rgb(255, 255, 255))",
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                        },
                        text: hNNMA1w9T,
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }),
                    }),
                    /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      height: 300,
                      width: `calc(${
                        componentViewport?.width || "100vw"
                      } - 40px)`,
                      y:
                        (componentViewport?.y || 0) +
                        0 +
                        (((componentViewport?.height || 690) - 0 - 668) / 2 +
                          0 +
                          0) +
                        0 +
                        0 +
                        0 +
                        0,
                      ...addPropertyOverrides(
                        {
                          cRhL61I0a: {
                            width: `calc(max(${
                              componentViewport?.width || "100vw"
                            } / 2, 1px) - 40px)`,
                            y: (componentViewport?.y || 0) + 0 + 0 + 0 + 0 + 0,
                          },
                          QAWLMrsYo: {
                            width: `calc(${
                              componentViewport?.width || "100vw"
                            } - 20px)`,
                            y:
                              (componentViewport?.y || 0) +
                              0 +
                              (((componentViewport?.height || 710) - 0 - 668) /
                                2 +
                                0 +
                                0) +
                              0 +
                              0 +
                              0 +
                              0,
                          },
                        },
                        baseVariant,
                        gestureVariant
                      ),
                      children: /*#__PURE__*/ _jsx(
                        SmartComponentScopedContainer,
                        {
                          className: "framer-hrnvuq-container",
                          layoutDependency: layoutDependency,
                          layoutId: "NpPg9n6pf-container",
                          nodeId: "NpPg9n6pf",
                          rendersWithMotion: true,
                          scopeId: "YbnDYbxmS",
                          children: /*#__PURE__*/ _jsx(CMSMediaComponent, {
                            Cuimim1um: 16,
                            height: "100%",
                            id: "NpPg9n6pf",
                            layoutId: "NpPg9n6pf",
                            style: { width: "100%" },
                            variant: matchVariant(DlhhthLy6),
                            vUNPVSzaR: toResponsiveImage(O6VZxtSZX),
                            width: "100%",
                            ybORcgyou: DsuUSgSpS,
                            ...addPropertyOverrides(
                              { cRhL61I0a: { Cuimim1um: 8 } },
                              baseVariant,
                              gestureVariant
                            ),
                          }),
                        }
                      ),
                    }),
                  ],
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-puf0u",
              "data-framer-name": "Section",
              layoutDependency: layoutDependency,
              layoutId: "mz68kWBpM",
              children: /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-odghx5",
                "data-framer-name": "Text Container",
                layoutDependency: layoutDependency,
                layoutId: "rVOnG4Th1",
                children: [
                  /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-1rbsyii",
                    "data-framer-name": "Container",
                    layoutDependency: layoutDependency,
                    layoutId: "F42CGbqqm",
                    children: [
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            className: "framer-styles-preset-1rymzzk",
                            "data-styles-preset": "mMKAraaKM",
                            dir: "auto",
                            style: {
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, rgb(0, 0, 0)))",
                            },
                            children: "Publishe Date",
                          }),
                        }),
                        className: "framer-1r3ymr4",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "XAl6KDCla",
                        style: {
                          "--extracted-r6o4lv":
                            "var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, rgb(0, 0, 0))",
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                        },
                        text: ua5NLrebe,
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }),
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-1yu8w39",
                        "data-framer-name": "Text Container",
                        layoutDependency: layoutDependency,
                        layoutId: "ufrnJ_qjC",
                        children: [
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.h3, {
                                className: "framer-styles-preset-179n8gy",
                                "data-styles-preset": "AUSpdMA0k",
                                dir: "auto",
                                style: {
                                  "--framer-text-color":
                                    "var(--extracted-a0htzi, var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, rgb(0, 0, 0)))",
                                },
                                children: /*#__PURE__*/ _jsx(Link, {
                                  href: mlA3cUpG9,
                                  motionChild: true,
                                  nodeId: "KG2Slt5Tj",
                                  openInNewTab: false,
                                  relValues: [],
                                  scopeId: "YbnDYbxmS",
                                  smoothScroll: false,
                                  children: /*#__PURE__*/ _jsx(motion.a, {
                                    className: "framer-styles-preset-11v4o1l",
                                    "data-styles-preset": "QeY5Itq9g",
                                    children: "Article Title",
                                  }),
                                }),
                              }),
                            }),
                            className: "framer-1j7zjxp",
                            "data-framer-cursor": OuW36Qsbp,
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "KG2Slt5Tj",
                            style: {
                              "--extracted-a0htzi":
                                "var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, rgb(0, 0, 0))",
                            },
                            text: AfzyTYgJw,
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                          /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-1rymzzk",
                                "data-styles-preset": "mMKAraaKM",
                                dir: "auto",
                                style: {
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, rgb(0, 0, 0)))",
                                },
                                children: "Intro",
                              }),
                            }),
                            className: "framer-tx4smw",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "LszaQofy1",
                            style: {
                              "--extracted-r6o4lv":
                                "var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, rgb(0, 0, 0))",
                              "--framer-link-text-color": "rgb(0, 153, 255)",
                              "--framer-link-text-decoration": "underline",
                            },
                            text: iwztgPJCj,
                            verticalAlignment: "top",
                            withExternalLayout: true,
                          }),
                        ],
                      }),
                    ],
                  }),
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 20,
                    y:
                      (componentViewport?.y || 0) +
                      0 +
                      (((componentViewport?.height || 690) - 0 - 668) / 2 +
                        300 +
                        24) +
                      0 +
                      0 +
                      0 +
                      324,
                    ...addPropertyOverrides(
                      {
                        cRhL61I0a: {
                          y: (componentViewport?.y || 0) + 0 + 0 + 0 + 0 + 324,
                        },
                        QAWLMrsYo: {
                          y:
                            (componentViewport?.y || 0) +
                            0 +
                            (((componentViewport?.height || 710) - 0 - 668) /
                              2 +
                              300 +
                              24) +
                            0 +
                            0 +
                            0 +
                            324,
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainer,
                      {
                        className: "framer-9k97a8-container",
                        "data-framer-cursor": OuW36Qsbp,
                        layoutDependency: layoutDependency,
                        layoutId: "u6s1TK1Qo-container",
                        nodeId: "u6s1TK1Qo",
                        rendersWithMotion: true,
                        scopeId: "YbnDYbxmS",
                        children: /*#__PURE__*/ _jsx(MainButton, {
                          BhFmKI_CC: mlA3cUpG9,
                          height: "100%",
                          id: "u6s1TK1Qo",
                          KKXBGp3Wv:
                            "var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, rgb(0, 0, 0))",
                          layoutId: "u6s1TK1Qo",
                          nhudf0dmF: false,
                          u6m8yRtDy: "Read more",
                          variant: matchVariant("vVLd8CW0_"),
                          width: "100%",
                        }),
                      }
                    ),
                  }),
                ],
              }),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-Hi4jK.framer-15mui1k, .framer-Hi4jK .framer-15mui1k { display: block; }",
  ".framer-Hi4jK.framer-xvjtxm { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 0px 20px 0px 20px; position: relative; width: 540px; }",
  ".framer-Hi4jK .framer-16o7xyj, .framer-Hi4jK .framer-puf0u { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-Hi4jK .framer-1x8p6d5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: 100%; }",
  ".framer-Hi4jK .framer-1rp9qnv { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; left: 0px; overflow: visible; padding: 0px 8px 0px 8px; position: absolute; top: 0px; width: min-content; z-index: 2; }",
  ".framer-Hi4jK .framer-1uwyufs { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-Hi4jK .framer-hrnvuq-container { flex: none; height: auto; position: relative; width: 100%; }",
  ".framer-Hi4jK .framer-odghx5 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-Hi4jK .framer-1rbsyii { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
  ".framer-Hi4jK .framer-1r3ymr4 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-Hi4jK .framer-1yu8w39 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
  ".framer-Hi4jK .framer-1j7zjxp { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: 100%; }",
  ".framer-Hi4jK .framer-tx4smw { flex: none; height: auto; max-width: 640px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-Hi4jK .framer-9k97a8-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-Hi4jK.framer-v-8hpb4g.framer-xvjtxm { align-content: flex-start; align-items: flex-start; flex-direction: row; gap: 0px; padding: 0px; }",
  ".framer-Hi4jK.framer-v-8hpb4g .framer-16o7xyj, .framer-Hi4jK.framer-v-8hpb4g .framer-puf0u { flex: 3 0 0px; width: 1px; }",
  ".framer-Hi4jK.framer-v-8hpb4g .framer-1x8p6d5, .framer-Hi4jK.framer-v-8hpb4g .framer-odghx5 { padding: 0px 20px 0px 20px; }",
  ".framer-Hi4jK.framer-v-8hpb4g .framer-1rp9qnv { left: 20px; }",
  ".framer-Hi4jK.framer-v-hd5w20.framer-xvjtxm { padding: 0px 10px 0px 10px; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  ...sharedStyle2.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 690
 * @framerIntrinsicWidth 540
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"cRhL61I0a":{"layout":["fixed","auto"]},"gHBLOWCuj":{"layout":["fixed","auto"]},"QAWLMrsYo":{"layout":["fixed","auto"]}}}
 * @framerVariables {"hNNMA1w9T":"tag","ua5NLrebe":"publishDate","AfzyTYgJw":"articleTitle","iwztgPJCj":"intro","DlhhthLy6":"mediaType","O6VZxtSZX":"mainImage","DsuUSgSpS":"mainVideo","mlA3cUpG9":"link","OuW36Qsbp":"hideCursor"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerYbnDYbxmS = withCSS(Component, css, "framer-Hi4jK");
export default FramerYbnDYbxmS;
FramerYbnDYbxmS.displayName = "Insight Card";
FramerYbnDYbxmS.defaultProps = { height: 690, width: 540 };
addPropertyControls(FramerYbnDYbxmS, {
  variant: {
    options: ["rc9OhqS3b", "cRhL61I0a", "gHBLOWCuj", "QAWLMrsYo"],
    optionTitles: ["Desktop A", "Desktop B", "Tablet", "Mobile"],
    title: "Variant",
    type: ControlType.Enum,
  },
  hNNMA1w9T: {
    defaultValue: "Tag",
    displayTextArea: false,
    title: "Tag",
    type: ControlType.String,
  },
  onhNNMA1w9TChange: { changes: "hNNMA1w9T", type: ControlType.ChangeHandler },
  ua5NLrebe: {
    defaultValue: "Publish Date",
    displayTextArea: false,
    title: "Publish Date",
    type: ControlType.String,
  },
  onua5NLrebeChange: { changes: "ua5NLrebe", type: ControlType.ChangeHandler },
  AfzyTYgJw: {
    defaultValue: "Article Title",
    displayTextArea: false,
    title: "Article Title",
    type: ControlType.String,
  },
  onAfzyTYgJwChange: { changes: "AfzyTYgJw", type: ControlType.ChangeHandler },
  iwztgPJCj: {
    defaultValue: "Intro",
    displayTextArea: false,
    title: "Intro",
    type: ControlType.String,
  },
  oniwztgPJCjChange: { changes: "iwztgPJCj", type: ControlType.ChangeHandler },
  DlhhthLy6: CMSMediaComponentControls?.["variant"] && {
    ...CMSMediaComponentControls["variant"],
    defaultValue: "hsLovB1mn",
    description: undefined,
    hidden: undefined,
    optional: undefined,
    title: "Media Type",
  },
  onDlhhthLy6Change: { changes: "DlhhthLy6", type: ControlType.ChangeHandler },
  O6VZxtSZX: { title: "Main Image", type: ControlType.ResponsiveImage },
  DsuUSgSpS: CMSMediaComponentControls?.["ybORcgyou"] && {
    ...CMSMediaComponentControls["ybORcgyou"],
    __defaultAssetReference: "",
    description: undefined,
    hidden: undefined,
    title: "Main Video",
  },
  onDsuUSgSpSChange: { changes: "DsuUSgSpS", type: ControlType.ChangeHandler },
  mlA3cUpG9: { title: "Link", type: ControlType.Link },
  OuW36Qsbp: { title: "Hide Cursor", type: ControlType.CustomCursor },
});
addFonts(
  FramerYbnDYbxmS,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...CMSMediaComponentFonts,
    ...MainButtonFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
    ...getFontsFromSharedStyle(sharedStyle2.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
FramerYbnDYbxmS.loader = {
  load: (props, context) => {
    const locale = context.locale;
    return Promise.allSettled([
      forwardLoader(CMSMediaComponent, {}, context),
      forwardLoader(MainButton, {}, context),
    ]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerYbnDYbxmS",
      slots: [],
      annotations: {
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"cRhL61I0a":{"layout":["fixed","auto"]},"gHBLOWCuj":{"layout":["fixed","auto"]},"QAWLMrsYo":{"layout":["fixed","auto"]}}}',
        framerColorSyntax: "true",
        framerIntrinsicWidth: "540",
        framerIntrinsicHeight: "690",
        framerAutoSizeImages: "true",
        framerDisplayContentsDiv: "false",
        framerComponentViewportWidth: "true",
        framerVariables:
          '{"hNNMA1w9T":"tag","ua5NLrebe":"publishDate","AfzyTYgJw":"articleTitle","iwztgPJCj":"intro","DlhhthLy6":"mediaType","O6VZxtSZX":"mainImage","DsuUSgSpS":"mainVideo","mlA3cUpG9":"link","OuW36Qsbp":"hideCursor"}',
        framerImmutableVariables: "true",
        framerContractVersion: "1",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
