// Generated by Framer (7bfce40)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  forwardLoader,
  getFonts,
  getFontsFromSharedStyle,
  getPropertyControls,
  Link,
  RichText,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle1 from "https://framerusercontent.com/modules/dSS1uCijisiz782U0cUU/zMXDU1j1zPTUQWAUrlk2/L1o6YCuI3.js";
import * as sharedStyle from "https://framerusercontent.com/modules/GgteY8irBGfUzh8z4mh2/NzDgB7DilEKK0dJEeHtg/mMKAraaKM.js";
import * as sharedStyle2 from "https://framerusercontent.com/modules/THYeR8PBM8qSAWWrHig9/7uCPEdDQZVF6VyKKTgWa/QeY5Itq9g.js";
import CMSMediaComponent from "https://framerusercontent.com/modules/tvZ2VnsLoWdBWVhzcqSb/oCgi9Q25qR1smsUqFzB1/GFSuRgwr2.js";
import MainButton from "https://framerusercontent.com/modules/LCVE0KtQYdb2UTyP4r8C/w2m6bInrHbLrgSQ8kXEv/TOMRBfQdf.js";
const CMSMediaComponentFonts = getFonts(CMSMediaComponent);
const MainButtonFonts = getFonts(MainButton);
const CMSMediaComponentControls = getPropertyControls(CMSMediaComponent);
const cycleOrder = ["yzaUP78SW", "SY2YydBWK", "leo_gN_mK"];
const serializationHash = "framer-6xu3z";
const variantClassNames = {
  leo_gN_mK: "framer-v-i21d65",
  SY2YydBWK: "framer-v-1xgvjrv",
  yzaUP78SW: "framer-v-1yp2pbr",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const MzU_Jhs40 = undefined;
const fKIpRrs43 = undefined;
const FrTmFIWcS = undefined;
const HHmhhNYyI = undefined;
const Zm9RL8LP_ = undefined;
const C7gEsuH7p = undefined;
const s7sA37fcd = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  Desktop: "yzaUP78SW",
  Phone: "leo_gN_mK",
  Tablet: "SY2YydBWK",
};
const Variants = motion.create(React.Fragment);
const humanReadableEnumMap = { Image: "hsLovB1mn", Video: "dGJeCPINe" };
const getProps = ({
  coverImage,
  coverVideo,
  height,
  hideCursor,
  id,
  link,
  mediaType,
  projectIntro,
  projectTitle,
  width,
  ...props
}) => {
  return {
    ...props,
    C7gEsuH7p: projectTitle ?? props.C7gEsuH7p ?? "Project Title",
    fKIpRrs43: link ?? props.fKIpRrs43,
    FrTmFIWcS:
      humanReadableEnumMap[mediaType] ??
      mediaType ??
      props.FrTmFIWcS ??
      "hsLovB1mn",
    HHmhhNYyI: coverImage ?? props.HHmhhNYyI,
    MzU_Jhs40: hideCursor ?? props.MzU_Jhs40,
    s7sA37fcd: projectIntro ?? props.s7sA37fcd ?? "Project Intro",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "yzaUP78SW",
    Zm9RL8LP_: coverVideo ?? props.Zm9RL8LP_,
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    C7gEsuH7p,
    s7sA37fcd,
    FrTmFIWcS,
    HHmhhNYyI,
    Zm9RL8LP_,
    fKIpRrs43,
    MzU_Jhs40,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "yzaUP78SW",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [
    sharedStyle.className,
    sharedStyle1.className,
    sharedStyle2.className,
  ];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (["SY2YydBWK", "leo_gN_mK"].includes(baseVariant)) return false;
    return true;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1yp2pbr",
            className,
            classNames
          ),
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "yzaUP78SW",
          ref: refBinding,
          style: {
            backgroundColor:
              "var(--token-280bd9a0-bf37-41b4-a3c3-9a122b679a65, rgb(255, 255, 255))",
            ...style,
          },
          ...addPropertyOverrides(
            {
              leo_gN_mK: { "data-framer-name": "Phone" },
              SY2YydBWK: { "data-framer-name": "Tablet" },
            },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsxs(motion.div, {
            className: "framer-q01crt",
            "data-framer-name": "Featured Project",
            layoutDependency: layoutDependency,
            layoutId: "iYiFWezWI",
            children: [
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-1a3usy5",
                "data-framer-name": "Section",
                layoutDependency: layoutDependency,
                layoutId: "oZPdzh7v6",
                children: /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-1owq8cd",
                  "data-framer-name": "Container",
                  layoutDependency: layoutDependency,
                  layoutId: "WayP5Rr6H",
                  children: /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        className: "framer-styles-preset-1rymzzk",
                        "data-styles-preset": "mMKAraaKM",
                        dir: "auto",
                        children: /*#__PURE__*/ _jsx(motion.strong, {
                          children: "Featured Project",
                        }),
                      }),
                    }),
                    className: "framer-igox2t",
                    fonts: ["Inter", "Inter-Bold"],
                    layoutDependency: layoutDependency,
                    layoutId: "P0x0wtxWS",
                    style: {
                      "--framer-link-text-color": "rgb(0, 153, 255)",
                      "--framer-link-text-decoration": "underline",
                    },
                    verticalAlignment: "top",
                    withExternalLayout: true,
                  }),
                }),
              }),
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-n5e256",
                "data-framer-name": "Media",
                layoutDependency: layoutDependency,
                layoutId: "x4trnTyIi",
                children: /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-aiwowv",
                  "data-framer-name": "Container",
                  layoutDependency: layoutDependency,
                  layoutId: "Ti0EF5l0L",
                  children: /*#__PURE__*/ _jsx(Link, {
                    href: fKIpRrs43,
                    motionChild: true,
                    nodeId: "QrPEyXuhc",
                    openInNewTab: false,
                    scopeId: "db9m_4glV",
                    children: /*#__PURE__*/ _jsx(motion.a, {
                      className: "framer-1wuygyj framer-pk33w2",
                      "data-framer-cursor": MzU_Jhs40,
                      "data-framer-name": "Media Container",
                      layoutDependency: layoutDependency,
                      layoutId: "QrPEyXuhc",
                      children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 300,
                        width: `max(max((${
                          componentViewport?.width || "100vw"
                        } - 40px) / 4, 1px) - 40px, 1px)`,
                        y:
                          (componentViewport?.y || 0) +
                          200 +
                          (((componentViewport?.height || 459.5) - 200 - 300) /
                            2 +
                            0 +
                            0) +
                          0 +
                          0 +
                          0 +
                          0 +
                          0 +
                          0,
                        ...addPropertyOverrides(
                          {
                            leo_gN_mK: {
                              width: `max(${
                                componentViewport?.width || "100vw"
                              } - 40px, 1px)`,
                              y:
                                (componentViewport?.y || 0) +
                                120 +
                                (((componentViewport?.height || 200) -
                                  120 -
                                  744) /
                                  2 +
                                  0 +
                                  0) +
                                0 +
                                144 +
                                0 +
                                0 +
                                0 +
                                0 +
                                0,
                            },
                            SY2YydBWK: {
                              width: `max(max((${
                                componentViewport?.width || "100vw"
                              } - 30px) / 3, 1px) - 30px, 1px)`,
                              y:
                                (componentViewport?.y || 0) +
                                160 +
                                (((componentViewport?.height || 419.5) -
                                  160 -
                                  300) /
                                  2 +
                                  0 +
                                  0) +
                                0 +
                                0 +
                                0 +
                                0 +
                                0 +
                                0,
                            },
                          },
                          baseVariant,
                          gestureVariant
                        ),
                        children: /*#__PURE__*/ _jsx(
                          SmartComponentScopedContainer,
                          {
                            className: "framer-4lnb1h-container",
                            layoutDependency: layoutDependency,
                            layoutId: "lZTR_cMuo-container",
                            nodeId: "lZTR_cMuo",
                            rendersWithMotion: true,
                            scopeId: "db9m_4glV",
                            children: /*#__PURE__*/ _jsx(CMSMediaComponent, {
                              Cuimim1um: 8,
                              height: "100%",
                              id: "lZTR_cMuo",
                              layoutId: "lZTR_cMuo",
                              style: { width: "100%" },
                              variant: matchVariant(FrTmFIWcS),
                              vUNPVSzaR: toResponsiveImage(HHmhhNYyI),
                              width: "100%",
                              ybORcgyou: Zm9RL8LP_,
                              ...addPropertyOverrides(
                                { leo_gN_mK: { Cuimim1um: 16 } },
                                baseVariant,
                                gestureVariant
                              ),
                            }),
                          }
                        ),
                      }),
                    }),
                  }),
                }),
              }),
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-1t5sq4b",
                "data-framer-name": "Text",
                layoutDependency: layoutDependency,
                layoutId: "fFW4HiRpa",
                children: /*#__PURE__*/ _jsxs(motion.div, {
                  className: "framer-fwx88",
                  "data-framer-name": "Container",
                  layoutDependency: layoutDependency,
                  layoutId: "zvkkfNKwt",
                  children: [
                    /*#__PURE__*/ _jsxs(motion.div, {
                      className: "framer-12i5luz",
                      "data-framer-name": "Text Container",
                      layoutDependency: layoutDependency,
                      layoutId: "eZl5LWAKN",
                      children: [
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.h2, {
                              className: "framer-styles-preset-cliz78",
                              "data-styles-preset": "L1o6YCuI3",
                              dir: "auto",
                              children: /*#__PURE__*/ _jsx(Link, {
                                href: fKIpRrs43,
                                motionChild: true,
                                nodeId: "Y4LW4ksSF",
                                openInNewTab: false,
                                relValues: [],
                                scopeId: "db9m_4glV",
                                smoothScroll: false,
                                children: /*#__PURE__*/ _jsx(motion.a, {
                                  className: "framer-styles-preset-11v4o1l",
                                  "data-styles-preset": "QeY5Itq9g",
                                  children: "Project Title",
                                }),
                              }),
                            }),
                          }),
                          className: "framer-1h6ewnc",
                          "data-framer-cursor": MzU_Jhs40,
                          fonts: ["Inter"],
                          layoutDependency: layoutDependency,
                          layoutId: "Y4LW4ksSF",
                          text: C7gEsuH7p,
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-1rymzzk",
                              "data-styles-preset": "mMKAraaKM",
                              dir: "auto",
                              children: "Insight Intro",
                            }),
                          }),
                          className: "framer-2bmt15",
                          fonts: ["Inter"],
                          layoutDependency: layoutDependency,
                          layoutId: "ivujYru6y",
                          style: {
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline",
                          },
                          text: s7sA37fcd,
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                      ],
                    }),
                    /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      height: 20,
                      y:
                        (componentViewport?.y || 0) +
                        200 +
                        (((componentViewport?.height || 459.5) - 200 - 300) /
                          2 +
                          0 +
                          0) +
                        0 +
                        0 +
                        0 +
                        0 +
                        248,
                      ...addPropertyOverrides(
                        {
                          leo_gN_mK: {
                            y:
                              (componentViewport?.y || 0) +
                              120 +
                              (((componentViewport?.height || 200) -
                                120 -
                                744) /
                                2 +
                                0 +
                                0) +
                              0 +
                              476 +
                              0 +
                              0 +
                              0 +
                              248,
                          },
                          SY2YydBWK: {
                            y:
                              (componentViewport?.y || 0) +
                              160 +
                              (((componentViewport?.height || 419.5) -
                                160 -
                                300) /
                                2 +
                                0 +
                                0) +
                              0 +
                              0 +
                              0 +
                              0 +
                              248,
                          },
                        },
                        baseVariant,
                        gestureVariant
                      ),
                      children: /*#__PURE__*/ _jsx(
                        SmartComponentScopedContainer,
                        {
                          className: "framer-qu1ojz-container",
                          "data-framer-cursor": MzU_Jhs40,
                          layoutDependency: layoutDependency,
                          layoutId: "HQ16eu1Uc-container",
                          nodeId: "HQ16eu1Uc",
                          rendersWithMotion: true,
                          scopeId: "db9m_4glV",
                          children: /*#__PURE__*/ _jsx(MainButton, {
                            BhFmKI_CC: fKIpRrs43,
                            height: "100%",
                            id: "HQ16eu1Uc",
                            KKXBGp3Wv:
                              "var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, rgb(0, 0, 0))",
                            layoutId: "HQ16eu1Uc",
                            nhudf0dmF: false,
                            u6m8yRtDy: "View Project",
                            variant: matchVariant("vVLd8CW0_"),
                            width: "100%",
                          }),
                        }
                      ),
                    }),
                  ],
                }),
              }),
              isDisplayed() &&
                /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-70gcuk",
                  "data-framer-name": "Section",
                  layoutDependency: layoutDependency,
                  layoutId: "jWuE3sD9c",
                }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-6xu3z.framer-pk33w2, .framer-6xu3z .framer-pk33w2 { display: block; }",
  ".framer-6xu3z.framer-1yp2pbr { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 200px 20px 0px 20px; position: relative; width: 1200px; }",
  ".framer-6xu3z .framer-q01crt { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
  ".framer-6xu3z .framer-1a3usy5 { align-content: center; align-items: center; align-self: stretch; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: auto; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1px; }",
  ".framer-6xu3z .framer-1owq8cd { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 30px; height: 1px; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px 20px 0px 20px; position: relative; width: 100%; }",
  ".framer-6xu3z .framer-igox2t { flex: 1 0 0px; height: auto; position: sticky; top: 240px; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; z-index: 1; }",
  ".framer-6xu3z .framer-n5e256, .framer-6xu3z .framer-1t5sq4b { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1px; }",
  ".framer-6xu3z .framer-aiwowv { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px 20px 0px 20px; position: relative; width: 100%; }",
  ".framer-6xu3z .framer-1wuygyj { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; text-decoration: none; width: 100%; }",
  ".framer-6xu3z .framer-4lnb1h-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
  ".framer-6xu3z .framer-fwx88 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px 20px 0px 20px; position: relative; width: 100%; }",
  ".framer-6xu3z .framer-12i5luz { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
  ".framer-6xu3z .framer-1h6ewnc, .framer-6xu3z .framer-2bmt15 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-6xu3z .framer-qu1ojz-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-6xu3z .framer-70gcuk { align-self: stretch; flex: 1 0 0px; gap: 0px; height: auto; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1px; }",
  ".framer-6xu3z.framer-v-1xgvjrv.framer-1yp2pbr { padding: 160px 15px 0px 15px; width: 810px; }",
  ".framer-6xu3z.framer-v-1xgvjrv .framer-1owq8cd, .framer-6xu3z.framer-v-1xgvjrv .framer-aiwowv, .framer-6xu3z.framer-v-1xgvjrv .framer-fwx88 { padding: 0px 15px 0px 15px; }",
  ".framer-6xu3z.framer-v-i21d65.framer-1yp2pbr { padding: 120px 10px 0px 10px; width: 390px; }",
  ".framer-6xu3z.framer-v-i21d65 .framer-q01crt { flex-direction: column; gap: 32px; }",
  ".framer-6xu3z.framer-v-i21d65 .framer-1a3usy5 { align-self: unset; flex: none; height: min-content; width: 100%; }",
  ".framer-6xu3z.framer-v-i21d65 .framer-1owq8cd { flex: none; height: min-content; padding: 0px 10px 0px 10px; }",
  ".framer-6xu3z.framer-v-i21d65 .framer-n5e256, .framer-6xu3z.framer-v-i21d65 .framer-1t5sq4b { flex: none; width: 100%; }",
  ".framer-6xu3z.framer-v-i21d65 .framer-aiwowv, .framer-6xu3z.framer-v-i21d65 .framer-fwx88 { padding: 0px 10px 0px 10px; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  ...sharedStyle2.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 459.5
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"SY2YydBWK":{"layout":["fixed","auto"]},"leo_gN_mK":{"layout":["fixed","auto"]}}}
 * @framerVariables {"C7gEsuH7p":"projectTitle","s7sA37fcd":"projectIntro","FrTmFIWcS":"mediaType","HHmhhNYyI":"coverImage","Zm9RL8LP_":"coverVideo","fKIpRrs43":"link","MzU_Jhs40":"hideCursor"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const Framerdb9m_4glV = withCSS(Component, css, "framer-6xu3z");
export default Framerdb9m_4glV;
Framerdb9m_4glV.displayName = "Featured Project";
Framerdb9m_4glV.defaultProps = { height: 459.5, width: 1200 };
addPropertyControls(Framerdb9m_4glV, {
  variant: {
    options: ["yzaUP78SW", "SY2YydBWK", "leo_gN_mK"],
    optionTitles: ["Desktop", "Tablet", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  C7gEsuH7p: {
    defaultValue: "Project Title",
    displayTextArea: false,
    title: "Project Title",
    type: ControlType.String,
  },
  onC7gEsuH7pChange: { changes: "C7gEsuH7p", type: ControlType.ChangeHandler },
  s7sA37fcd: {
    defaultValue: "Project Intro",
    displayTextArea: false,
    title: "Project Intro",
    type: ControlType.String,
  },
  ons7sA37fcdChange: { changes: "s7sA37fcd", type: ControlType.ChangeHandler },
  FrTmFIWcS: CMSMediaComponentControls?.["variant"] && {
    ...CMSMediaComponentControls["variant"],
    defaultValue: "hsLovB1mn",
    description: undefined,
    hidden: undefined,
    optional: undefined,
    title: "Media Type",
  },
  onFrTmFIWcSChange: { changes: "FrTmFIWcS", type: ControlType.ChangeHandler },
  HHmhhNYyI: { title: "Cover Image", type: ControlType.ResponsiveImage },
  Zm9RL8LP_: CMSMediaComponentControls?.["ybORcgyou"] && {
    ...CMSMediaComponentControls["ybORcgyou"],
    __defaultAssetReference: "",
    description: undefined,
    hidden: undefined,
    title: "Cover Video",
  },
  onZm9RL8LP_Change: { changes: "Zm9RL8LP_", type: ControlType.ChangeHandler },
  fKIpRrs43: { title: "Link", type: ControlType.Link },
  MzU_Jhs40: { title: "Hide Cursor", type: ControlType.CustomCursor },
});
addFonts(
  Framerdb9m_4glV,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
          weight: "700",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
          weight: "700",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
          weight: "700",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
          weight: "700",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
          weight: "700",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/syRNPWzAMIrcJ3wIlPIP43KjQs.woff2",
          weight: "700",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
          weight: "700",
        },
      ],
    },
    ...CMSMediaComponentFonts,
    ...MainButtonFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
    ...getFontsFromSharedStyle(sharedStyle2.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
Framerdb9m_4glV.loader = {
  load: (props, context) => {
    const locale = context.locale;
    return Promise.allSettled([
      forwardLoader(CMSMediaComponent, {}, context),
      forwardLoader(MainButton, {}, context),
    ]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "Framerdb9m_4glV",
      slots: [],
      annotations: {
        framerColorSyntax: "true",
        framerContractVersion: "1",
        framerIntrinsicHeight: "459.5",
        framerDisplayContentsDiv: "false",
        framerVariables:
          '{"C7gEsuH7p":"projectTitle","s7sA37fcd":"projectIntro","FrTmFIWcS":"mediaType","HHmhhNYyI":"coverImage","Zm9RL8LP_":"coverVideo","fKIpRrs43":"link","MzU_Jhs40":"hideCursor"}',
        framerAutoSizeImages: "true",
        framerComponentViewportWidth: "true",
        framerImmutableVariables: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"SY2YydBWK":{"layout":["fixed","auto"]},"leo_gN_mK":{"layout":["fixed","auto"]}}}',
        framerIntrinsicWidth: "1200",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
