// Generated by Framer (d22cd96)
import { fontStore } from "framer";
fontStore.loadFonts([
  "GF;Geist Mono-regular",
  "GF;Geist Mono-700",
  "GF;Geist Mono-700italic",
  "GF;Geist Mono-italic",
]);
export const fonts = [
  {
    explicitInter: true,
    fonts: [
      {
        cssFamilyName: "Geist Mono",
        source: "google",
        style: "normal",
        uiFamilyName: "Geist Mono",
        url: "https://fonts.gstatic.com/s/geistmono/v6/or3yQ6H-1_WfwkMZI_qYPLs1a-t7PU0AbeE9KJ5W7ihaO_CS.woff2",
        weight: "400",
      },
      {
        cssFamilyName: "Geist Mono",
        source: "google",
        style: "normal",
        uiFamilyName: "Geist Mono",
        url: "https://fonts.gstatic.com/s/geistmono/v6/or3yQ6H-1_WfwkMZI_qYPLs1a-t7PU0AbeHaL55W7ihaO_CS.woff2",
        weight: "700",
      },
      {
        cssFamilyName: "Geist Mono",
        source: "google",
        style: "italic",
        uiFamilyName: "Geist Mono",
        url: "https://fonts.gstatic.com/s/geistmono/v6/or3wQ6H-1_WfwkMZI_qYFrIHlDMSVteuavT1a5EX5Cl4PuCSdNg.woff2",
        weight: "700",
      },
      {
        cssFamilyName: "Geist Mono",
        source: "google",
        style: "italic",
        uiFamilyName: "Geist Mono",
        url: "https://fonts.gstatic.com/s/geistmono/v6/or3wQ6H-1_WfwkMZI_qYFrIHlDMSVteuavT1a3YQ5Cl4PuCSdNg.woff2",
        weight: "400",
      },
    ],
  },
];
export const css = [
  '.framer-ZJMq0 .framer-styles-preset-1rymzzk:not(.rich-text-wrapper), .framer-ZJMq0 .framer-styles-preset-1rymzzk.rich-text-wrapper p { --framer-font-family: "Geist Mono", monospace; --framer-font-family-bold: "Geist Mono", monospace; --framer-font-family-bold-italic: "Geist Mono", monospace; --framer-font-family-italic: "Geist Mono", monospace; --framer-font-open-type-features: normal; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.03em; --framer-line-height: 160%; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; }',
];
export const className = "framer-ZJMq0";
export const __FramerMetadata__ = {
  exports: {
    className: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    css: { type: "variable", annotations: { framerContractVersion: "1" } },
    fonts: { type: "variable", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
