// Generated by Framer (ca8ceca)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  Link,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import RollingLetters from "https://framerusercontent.com/modules/r3Ndwtz4n0zMUMLt9Xy6/i4GV9vC0bGTsafskoTk7/RollingLetters.js";
const RollingLettersFonts = getFonts(RollingLetters);
const cycleOrder = ["BaMYFEKZm", "hnpGEkAvo"];
const serializationHash = "framer-vW3n5";
const variantClassNames = {
  BaMYFEKZm: "framer-v-4zzvq1",
  hnpGEkAvo: "framer-v-xg4yau",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const BhFmKI_CC = undefined;
const nhudf0dmF = undefined;
const u6m8yRtDy = undefined;
const KKXBGp3Wv = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = { Mobile: "hnpGEkAvo", Primary: "BaMYFEKZm" };
const Variants = motion.create(React.Fragment);
const getProps = ({
  color,
  height,
  id,
  link,
  menuItem,
  newTab,
  width,
  ...props
}) => {
  return {
    ...props,
    BhFmKI_CC: link ?? props.BhFmKI_CC,
    KKXBGp3Wv:
      color ??
      props.KKXBGp3Wv ??
      "var(--token-280bd9a0-bf37-41b4-a3c3-9a122b679a65, rgb(255, 255, 255))",
    nhudf0dmF: newTab ?? props.nhudf0dmF,
    u6m8yRtDy: menuItem ?? props.u6m8yRtDy ?? "Menu Item",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "BaMYFEKZm",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    u6m8yRtDy,
    BhFmKI_CC,
    nhudf0dmF,
    KKXBGp3Wv,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "BaMYFEKZm",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(Link, {
          href: BhFmKI_CC,
          motionChild: true,
          nodeId: "BaMYFEKZm",
          openInNewTab: nhudf0dmF,
          scopeId: "BbJbheibI",
          children: /*#__PURE__*/ _jsx(motion.a, {
            ...restProps,
            ...gestureHandlers,
            className: `${cx(
              scopingClassNames,
              "framer-4zzvq1",
              className,
              classNames
            )} framer-l52q44`,
            "data-framer-name": "Primary",
            layoutDependency: layoutDependency,
            layoutId: "BaMYFEKZm",
            ref: refBinding,
            style: { ...style },
            ...addPropertyOverrides(
              { hnpGEkAvo: { "data-framer-name": "Mobile" } },
              baseVariant,
              gestureVariant
            ),
            children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-2959zb-container",
                "data-code-component-plugin-id": "84d4c1",
                isAuthoredByUser: true,
                isModuleExternal: true,
                layoutDependency: layoutDependency,
                layoutId: "skkO7bMMr-container",
                nodeId: "skkO7bMMr",
                rendersWithMotion: true,
                scopeId: "BbJbheibI",
                children: /*#__PURE__*/ _jsx(RollingLetters, {
                  color: KKXBGp3Wv,
                  enableRolling: true,
                  enableVariableWeight: false,
                  font: {
                    fontFamily: '"Anton", "Anton Placeholder", sans-serif',
                    fontSize: "96px",
                    fontStyle: "normal",
                    fontWeight: 400,
                    letterSpacing: "0em",
                    lineHeight: "100%",
                  },
                  height: "100%",
                  iconGap: 8,
                  iconName: "star",
                  iconPosition: "before",
                  iconSize: 24,
                  iconStyle: "outlined",
                  id: "skkO7bMMr",
                  layoutId: "skkO7bMMr",
                  reverse: false,
                  showIcon: false,
                  stagger: 0.03,
                  tag: "p",
                  text: u6m8yRtDy,
                  transform: "uppercase",
                  transition: {
                    delay: 0,
                    duration: 0.4,
                    ease: [0.8, 0, 0.4, 1],
                    type: "tween",
                  },
                  variableWeight: 400,
                  verticalAlign: "center",
                  width: "100%",
                  ...addPropertyOverrides(
                    {
                      hnpGEkAvo: {
                        font: {
                          fontFamily:
                            '"Anton", "Anton Placeholder", sans-serif',
                          fontSize: "64px",
                          fontStyle: "normal",
                          fontWeight: 400,
                          letterSpacing: "0em",
                          lineHeight: "100%",
                        },
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
              }),
            }),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-vW3n5.framer-l52q44, .framer-vW3n5 .framer-l52q44 { display: block; }",
  ".framer-vW3n5.framer-4zzvq1 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
  ".framer-vW3n5 .framer-2959zb-container { flex: none; height: auto; position: relative; width: auto; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 96
 * @framerIntrinsicWidth 398
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"hnpGEkAvo":{"layout":["auto","auto"]}}}
 * @framerVariables {"u6m8yRtDy":"menuItem","BhFmKI_CC":"link","nhudf0dmF":"newTab","KKXBGp3Wv":"color"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerBbJbheibI = withCSS(Component, css, "framer-vW3n5");
export default FramerBbJbheibI;
FramerBbJbheibI.displayName = "Menu Button";
FramerBbJbheibI.defaultProps = { height: 96, width: 398 };
addPropertyControls(FramerBbJbheibI, {
  variant: {
    options: ["BaMYFEKZm", "hnpGEkAvo"],
    optionTitles: ["Primary", "Mobile"],
    title: "Variant",
    type: ControlType.Enum,
  },
  u6m8yRtDy: {
    defaultValue: "Menu Item",
    title: "Menu Item",
    type: ControlType.String,
  },
  onu6m8yRtDyChange: { changes: "u6m8yRtDy", type: ControlType.ChangeHandler },
  BhFmKI_CC: { title: "Link", type: ControlType.Link },
  nhudf0dmF: {
    defaultValue: false,
    title: "New Tab",
    type: ControlType.Boolean,
  },
  onnhudf0dmFChange: { changes: "nhudf0dmF", type: ControlType.ChangeHandler },
  KKXBGp3Wv: {
    defaultValue:
      'var(--token-280bd9a0-bf37-41b4-a3c3-9a122b679a65, rgb(255, 255, 255)) /* {"name":"White"} */',
    title: "Color",
    type: ControlType.Color,
  },
});
addFonts(
  FramerBbJbheibI,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Anton",
          source: "fontshare",
          style: "normal",
          uiFamilyName: "Anton",
          url: "https://framerusercontent.com/third-party-assets/fontshare/wf/TPY5PBRHOSXJ53WNSUYZQYX4FZUMAYNF/YHKM2QXXZHS7MS6DJUZXTGRXMIGWH7K5/PCXT6E5YCQO6SSVLT6UZPPGT7QKGXOUS.woff2",
          weight: "400",
        },
      ],
    },
    ...RollingLettersFonts,
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerBbJbheibI",
      slots: [],
      annotations: {
        framerComponentViewportWidth: "true",
        framerDisplayContentsDiv: "false",
        framerVariables:
          '{"u6m8yRtDy":"menuItem","BhFmKI_CC":"link","nhudf0dmF":"newTab","KKXBGp3Wv":"color"}',
        framerIntrinsicWidth: "398",
        framerAutoSizeImages: "true",
        framerColorSyntax: "true",
        framerImmutableVariables: "true",
        framerIntrinsicHeight: "96",
        framerContractVersion: "1",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"hnpGEkAvo":{"layout":["auto","auto"]}}}',
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./BbJbheibI.map
