// Generated by Framer (e0e363b)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getPropertyControls,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import PixelRevealOnAppear from "https://framerusercontent.com/modules/XJI2bJ8SPVUDX2JCB1jg/TwaADUwv1gxkm2ljmNdC/PixelRevealOnAppear.js";
const PixelRevealOnAppearFonts = getFonts(PixelRevealOnAppear);
const PixelRevealOnAppearControls = getPropertyControls(PixelRevealOnAppear);
const cycleOrder = ["hsLovB1mn", "dGJeCPINe"];
const serializationHash = "framer-ytTbr";
const variantClassNames = {
  dGJeCPINe: "framer-v-zp4zqu",
  hsLovB1mn: "framer-v-1iq7fso",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const vUNPVSzaR = undefined;
const ybORcgyou = undefined;
const Cuimim1um = undefined;
const transition1 = { duration: 0, type: "tween" };
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = { Image: "hsLovB1mn", Video: "dGJeCPINe" };
const Variants = motion.create(React.Fragment);
const getProps = ({ cellsRow, height, id, image, video, width, ...props }) => {
  return {
    ...props,
    Cuimim1um: cellsRow ?? props.Cuimim1um ?? 16,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "hsLovB1mn",
    vUNPVSzaR: image ??
      props.vUNPVSzaR ?? {
        pixelHeight: 1e3,
        pixelWidth: 1e3,
        src: "https://framerusercontent.com/images/22MQIF3epWgNnOHjtamot0mvL0.jpg?width=1000&height=1000",
        srcSet:
          "https://framerusercontent.com/images/22MQIF3epWgNnOHjtamot0mvL0.jpg?scale-down-to=512&width=1000&height=1000 512w,https://framerusercontent.com/images/22MQIF3epWgNnOHjtamot0mvL0.jpg?width=1000&height=1000 1000w",
      },
    ybORcgyou:
      video ??
      props.ybORcgyou ??
      "https://framerusercontent.com/assets/k18yp8YF66jcvHoVabiZmNkHmI.mp4",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    vUNPVSzaR,
    ybORcgyou,
    Cuimim1um,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "hsLovB1mn",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1iq7fso",
            className,
            classNames
          ),
          "data-framer-name": "Image",
          layoutDependency: layoutDependency,
          layoutId: "hsLovB1mn",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            { dGJeCPINe: { "data-framer-name": "Video" } },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
              className: "framer-1dabmf8-container",
              "data-code-component-plugin-id": "84d4c1",
              isAuthoredByUser: true,
              isModuleExternal: true,
              layoutDependency: layoutDependency,
              layoutId: "Z3TenHrwr-container",
              nodeId: "Z3TenHrwr",
              rendersWithMotion: true,
              scopeId: "GFSuRgwr2",
              children: /*#__PURE__*/ _jsx(PixelRevealOnAppear, {
                appearOnce: false,
                appearThreshold: 0.1,
                cellsPerRow: Cuimim1um,
                fillColor:
                  "var(--token-280bd9a0-bf37-41b4-a3c3-9a122b679a65, rgb(255, 255, 255))",
                height: "100%",
                id: "Z3TenHrwr",
                image: toResponsiveImage(vUNPVSzaR),
                layoutId: "Z3TenHrwr",
                mediaType: "image",
                pixelReveal: true,
                resetOnExit: false,
                revealDuration: 0.8,
                reverse: false,
                style: { width: "100%" },
                transitionLength: 1,
                videoFile: ybORcgyou,
                width: "100%",
                ...addPropertyOverrides(
                  { dGJeCPINe: { mediaType: "video" } },
                  baseVariant,
                  gestureVariant
                ),
              }),
            }),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-ytTbr.framer-1n718ec, .framer-ytTbr .framer-1n718ec { display: block; }",
  ".framer-ytTbr.framer-1iq7fso { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 300px; }",
  ".framer-ytTbr .framer-1dabmf8-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; z-index: 1; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 300
 * @framerIntrinsicWidth 300
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"dGJeCPINe":{"layout":["fixed","auto"]}}}
 * @framerVariables {"vUNPVSzaR":"image","ybORcgyou":"video","Cuimim1um":"cellsRow"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerGFSuRgwr2 = withCSS(Component, css, "framer-ytTbr");
export default FramerGFSuRgwr2;
FramerGFSuRgwr2.displayName = "CMS Media Component";
FramerGFSuRgwr2.defaultProps = { height: 300, width: 300 };
addPropertyControls(FramerGFSuRgwr2, {
  variant: {
    options: ["hsLovB1mn", "dGJeCPINe"],
    optionTitles: ["Image", "Video"],
    title: "Variant",
    type: ControlType.Enum,
  },
  vUNPVSzaR: {
    __defaultAssetReference:
      "data:framer/asset-reference,22MQIF3epWgNnOHjtamot0mvL0.jpg?originalFilename=image_placeholder.jpg&width=1000&height=1000",
    title: "Image",
    type: ControlType.ResponsiveImage,
  },
  ybORcgyou: PixelRevealOnAppearControls?.["videoFile"] && {
    ...PixelRevealOnAppearControls["videoFile"],
    __defaultAssetReference:
      "data:framer/asset-reference,k18yp8YF66jcvHoVabiZmNkHmI.mp4?originalFilename=video_placeholder.mp4",
    description: undefined,
    hidden: undefined,
    title: "Video",
  },
  onybORcgyouChange: { changes: "ybORcgyou", type: ControlType.ChangeHandler },
  Cuimim1um: {
    defaultValue: 16,
    max: 40,
    min: 1,
    step: 1,
    title: "Cells Row",
    type: ControlType.Number,
  },
  onCuimim1umChange: { changes: "Cuimim1um", type: ControlType.ChangeHandler },
});
addFonts(
  FramerGFSuRgwr2,
  [{ explicitInter: true, fonts: [] }, ...PixelRevealOnAppearFonts],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerGFSuRgwr2",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerImmutableVariables: "true",
        framerIntrinsicWidth: "300",
        framerVariables:
          '{"vUNPVSzaR":"image","ybORcgyou":"video","Cuimim1um":"cellsRow"}',
        framerIntrinsicHeight: "300",
        framerColorSyntax: "true",
        framerComponentViewportWidth: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"dGJeCPINe":{"layout":["fixed","auto"]}}}',
        framerDisplayContentsDiv: "false",
        framerAutoSizeImages: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./GFSuRgwr2.map
