// Generated by Framer (43e8337)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  ComponentViewportProvider,
  Container,
  cx,
  forwardLoader,
  GeneratedComponentContext,
  getFonts,
  PropertyOverrides,
  useComponentViewport,
  useCustomCursors,
  useHydratedBreakpointVariants,
  useIsOnFramerCanvas,
  useLocaleInfo,
  useMetadata,
  withCodeBoundaryForOverrides,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Page from "#framer/local/canvasComponent/HjCqDEKvH/HjCqDEKvH.js";
import CustomCursor from "#framer/local/canvasComponent/tDvkQwQu9/tDvkQwQu9.js";
import { withTargetElement } from "#framer/local/codeFile/EwMCwzI/Crazy_Navigation.js";
import metadataProvider from "#framer/local/webPageMetadata/DdnmDa6XO/DdnmDa6XO.js";
const PageFonts = getFonts(Page);
const MotionMainWithTargetElement15zbtf4 = withCodeBoundaryForOverrides(
  motion.main,
  { nodeId: "JcAyhoM51", override: withTargetElement, scopeId: "DdnmDa6XO" }
);
const CustomCursorFonts = getFonts(CustomCursor);
const breakpoints = {
  CZ3Cvb4_f: "(max-width: 809.98px)",
  l6SVL7vjd: "(min-width: 810px) and (max-width: 1199.98px)",
  Xxu1mTSkt: "(min-width: 1200px)",
};
const isBrowser = () => typeof document !== "undefined";
export const queryParamNames = [];
const serializationHash = "framer-PDKy4";
const variantClassNames = {
  CZ3Cvb4_f: "framer-v-1razu2j",
  l6SVL7vjd: "framer-v-qoc21j",
  Xxu1mTSkt: "framer-v-bqmlua",
};
const getRootLayoutProp = (
  hasLayoutTemplate,
  hasInheritedFlowEffect,
  fallback
) => {
  if (!hasLayoutTemplate) return fallback;
  return hasInheritedFlowEffect ? "position" : fallback;
};
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const humanReadableVariantMap = {
  Desktop: "Xxu1mTSkt",
  Phone: "CZ3Cvb4_f",
  Tablet: "l6SVL7vjd",
};
const HTMLStyle = ({ value }) => {
  const onCanvas = useIsOnFramerCanvas();
  if (onCanvas) return null;
  return /*#__PURE__*/ _jsx("style", {
    dangerouslySetInnerHTML: { __html: value },
    "data-framer-html-style": "",
  });
};
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "Xxu1mTSkt",
  };
};
const transition1 = {
  damping: 60,
  delay: 0,
  mass: 1,
  stiffness: 340,
  type: "spring",
};
const cursor = {
  alignment: "center",
  component: CustomCursor,
  offset: { x: 0, y: -5 },
  placement: "bottom",
  transition: transition1,
  variant: "tygU5dV70",
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const metadata = React.useMemo(
    () => metadataProvider({}, activeLocale),
    [activeLocale]
  );
  useMetadata(metadata);
  const [baseVariant, hydratedBaseVariant] = useHydratedBreakpointVariants(
    variant,
    breakpoints,
    false
  );
  const gestureVariant = undefined;
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const hasLayoutTemplate = React.useContext(
    GeneratedComponentContext
  )?.isLayoutTemplate;
  const hasInheritedFlowEffect = Boolean(
    React.useContext(MotionConfigContext)?.transition?.layout
  );
  const motionLayout = getRootLayoutProp(
    hasLayoutTemplate,
    hasInheritedFlowEffect
  );
  useCustomCursors({ lgbmwx: cursor });
  return /*#__PURE__*/ _jsx(GeneratedComponentContext.Provider, {
    value: {
      activeVariantId: baseVariant,
      humanReadableVariantMap,
      primaryVariantId: "Xxu1mTSkt",
      variantClassNames,
    },
    children: /*#__PURE__*/ _jsxs(LayoutGroup, {
      id: layoutId ?? defaultLayoutId,
      children: [
        /*#__PURE__*/ _jsx(HTMLStyle, {
          value:
            "html body { background: var(--token-280bd9a0-bf37-41b4-a3c3-9a122b679a65, rgb(255, 255, 255)); }",
        }),
        /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          className: cx(scopingClassNames, "framer-bqmlua", className),
          ref: refBinding,
          style: { ...style },
          children: /*#__PURE__*/ _jsx(MotionMainWithTargetElement15zbtf4, {
            className: "framer-15zbtf4",
            "data-framer-name": "Main Container",
            "data-hide-scrollbars": true,
            layout: motionLayout,
            children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 1286,
              width: componentViewport?.width || "100vw",
              y: (componentViewport?.y || 0) + 0 + 0 + 0 + 0,
              children: /*#__PURE__*/ _jsx(Container, {
                className: "framer-glkht5-container",
                nodeId: "UXgtoei7z",
                rendersWithMotion: true,
                scopeId: "DdnmDa6XO",
                children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                  breakpoint: baseVariant,
                  overrides: {
                    CZ3Cvb4_f: { variant: matchVariant("F81V8jesk") },
                    l6SVL7vjd: { variant: matchVariant("JbzXxdoSX") },
                  },
                  children: /*#__PURE__*/ _jsx(Page, {
                    height: "100%",
                    id: "UXgtoei7z",
                    layoutId: "UXgtoei7z",
                    style: { width: "100%" },
                    variant: matchVariant("c2r5LdRrQ"),
                    width: "100%",
                    WVdLsyu8b: "lgbmwx",
                  }),
                }),
              }),
            }),
          }),
        }),
        /*#__PURE__*/ _jsx("div", { id: "overlay" }),
      ],
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-PDKy4.framer-rhapsh, .framer-PDKy4 .framer-rhapsh { display: block; }",
  ".framer-PDKy4.framer-bqmlua { align-content: center; align-items: center; background-color: var(--token-280bd9a0-bf37-41b4-a3c3-9a122b679a65, #ffffff); display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 1080px; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1200px; }",
  ".framer-PDKy4 .framer-15zbtf4 { align-content: center; align-items: center; background-color: var(--token-280bd9a0-bf37-41b4-a3c3-9a122b679a65, #ffffff); display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 100vh; justify-content: flex-start; overflow: auto; padding: 0px; position: relative; width: 100%; }",
  ".framer-PDKy4 .framer-glkht5-container { flex: none; height: auto; position: relative; width: 100%; z-index: 2; }",
  '.framer-PDKy4[data-hide-scrollbars="true"]::-webkit-scrollbar, .framer-PDKy4 [data-hide-scrollbars="true"]::-webkit-scrollbar { width: 0px; height: 0px; }',
  '.framer-PDKy4[data-hide-scrollbars="true"]::-webkit-scrollbar-thumb, .framer-PDKy4 [data-hide-scrollbars="true"]::-webkit-scrollbar-thumb { background: transparent; }',
  '.framer-PDKy4[data-hide-scrollbars="true"], .framer-PDKy4 [data-hide-scrollbars="true"] { scrollbar-width: none; }',
  "@media (min-width: 810px) and (max-width: 1199.98px) { .framer-PDKy4.framer-bqmlua { width: 810px; }}",
  "@media (max-width: 809.98px) { .framer-PDKy4.framer-bqmlua { width: 390px; }}",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 1293
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"l6SVL7vjd":{"layout":["fixed","fixed"]},"CZ3Cvb4_f":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerAcceptsLayoutTemplate true
 * @framerScrollSections false
 * @framerResponsiveScreen true
 * @framerLayoutTemplateFlowEffect true
 */ const FramerDdnmDa6XO = withCSS(Component, css, "framer-PDKy4");
export default FramerDdnmDa6XO;
FramerDdnmDa6XO.displayName = "404";
FramerDdnmDa6XO.defaultProps = { height: 1293, width: 1200 };
addFonts(
  FramerDdnmDa6XO,
  [{ explicitInter: true, fonts: [] }, ...PageFonts, ...CustomCursorFonts],
  { supportsExplicitInterCodegen: true }
);
FramerDdnmDa6XO.loader = {
  load: (props, context) => {
    const locale = context.locale;
    return Promise.allSettled([forwardLoader(Page, {}, context)]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerDdnmDa6XO",
      slots: [],
      annotations: {
        framerAutoSizeImages: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"l6SVL7vjd":{"layout":["fixed","fixed"]},"CZ3Cvb4_f":{"layout":["fixed","fixed"]}}}',
        framerColorSyntax: "true",
        framerResponsiveScreen: "true",
        framerIntrinsicWidth: "1200",
        framerScrollSections: "false",
        framerImmutableVariables: "true",
        framerContractVersion: "1",
        framerLayoutTemplateFlowEffect: "true",
        framerDisplayContentsDiv: "false",
        framerIntrinsicHeight: "1293",
        framerAcceptsLayoutTemplate: "true",
        framerComponentViewportWidth: "true",
      },
    },
    queryParamNames: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
