// Generated by Framer (e0e363b)
import {
  jsx as _jsx,
  jsxs as _jsxs,
  Fragment as _Fragment,
} from "react/jsx-runtime";
import {
  addFonts,
  ChildrenCanSuspend,
  ComponentViewportProvider,
  Container,
  cx,
  forwardLoader,
  GeneratedComponentContext,
  getFonts,
  Link,
  PathVariablesContext,
  PropertyOverrides,
  queryCache,
  useComponentViewport,
  useCustomCursors,
  useHydratedBreakpointVariants,
  useIsOnFramerCanvas,
  useLocaleInfo,
  useMetadata,
  useQueryData,
  withCodeBoundaryForOverrides,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import TickerScroll from "https://framerusercontent.com/modules/WVXJ5gQDkQ5V8fm9KUVE/y8KgG1vt8zaeurXgrJqu/TickerScroll_Prod.js";
import ProjectInfoListView from "#framer/local/canvasComponent/ACx_WmG6E/ACx_WmG6E.js";
import HR from "#framer/local/canvasComponent/E_eUSw7wp/E_eUSw7wp.js";
import Projects from "#framer/local/canvasComponent/jxiVqPrvu/jxiVqPrvu.js";
import CustomCursor from "#framer/local/canvasComponent/tDvkQwQu9/tDvkQwQu9.js";
import BigLogo from "#framer/local/canvasComponent/VfTTeRCeX/VfTTeRCeX.js";
import Footer from "#framer/local/canvasComponent/xNVv5vbzH/xNVv5vbzH.js";
import {
  withInstantReset,
  withTargetElement,
} from "#framer/local/codeFile/EwMCwzI/Crazy_Navigation.js";
import Projects1 from "#framer/local/collection/SgW7VFB0v/SgW7VFB0v.js";
import metadataProvider from "#framer/local/webPageMetadata/augiA20Il/augiA20Il.js";
const ProjectsFonts = getFonts(Projects);
const ProjectInfoListViewFonts = getFonts(ProjectInfoListView);
const MotionAWithInstantReset1vx9gti = withCodeBoundaryForOverrides(motion.a, {
  inComponentSlot: true,
  nodeId: "cAaU2jT4D",
  override: withInstantReset,
  scopeId: "augiA20Il",
});
const MotionAWithInstantReset1kr9bvu = withCodeBoundaryForOverrides(motion.a, {
  inComponentSlot: true,
  nodeId: "zMs1M_qCZ",
  override: withInstantReset,
  scopeId: "augiA20Il",
});
const MotionAWithInstantResetfq721s = withCodeBoundaryForOverrides(motion.a, {
  inComponentSlot: true,
  nodeId: "S4AItlHWu",
  override: withInstantReset,
  scopeId: "augiA20Il",
});
const MotionAWithInstantResetrbbuic = withCodeBoundaryForOverrides(motion.a, {
  inComponentSlot: true,
  nodeId: "GoC9pzuR4",
  override: withInstantReset,
  scopeId: "augiA20Il",
});
const MotionAWithInstantResetpxj2pe = withCodeBoundaryForOverrides(motion.a, {
  inComponentSlot: true,
  nodeId: "EGmYjpszi",
  override: withInstantReset,
  scopeId: "augiA20Il",
});
const MotionAWithInstantReset1k2424s = withCodeBoundaryForOverrides(motion.a, {
  inComponentSlot: true,
  nodeId: "UdRZXnO7O",
  override: withInstantReset,
  scopeId: "augiA20Il",
});
const MotionAWithInstantReset1n6m2ma = withCodeBoundaryForOverrides(motion.a, {
  inComponentSlot: true,
  nodeId: "TGNYODxr5",
  override: withInstantReset,
  scopeId: "augiA20Il",
});
const TickerScrollFonts = getFonts(TickerScroll);
const BigLogoFonts = getFonts(BigLogo);
const HRFonts = getFonts(HR);
const FooterFonts = getFonts(Footer);
const MotionMainWithTargetElementtnt2m9 = withCodeBoundaryForOverrides(
  motion.main,
  { nodeId: "wIwn6fNPp", override: withTargetElement, scopeId: "augiA20Il" }
);
const CustomCursorFonts = getFonts(CustomCursor);
const breakpoints = {
  SiriE49rh: "(max-width: 809.98px)",
  wjo_zo7q7: "(min-width: 810px) and (max-width: 1199.98px)",
  WQLkyLRf1: "(min-width: 1200px)",
};
const isBrowser = () => typeof document !== "undefined";
export const queryParamNames = [];
const serializationHash = "framer-JHLJv";
const variantClassNames = {
  SiriE49rh: "framer-v-13fje81",
  wjo_zo7q7: "framer-v-yk56x6",
  WQLkyLRf1: "framer-v-72rtr7",
};
const OFm2bD2OmCdcBZuV5_ = undefined;
const d3BtWDjWlCdcBZuV5_ = undefined;
const KcGyxLZIQCdcBZuV5_ = undefined;
const UbKku4qCvCdcBZuV5_ = undefined;
const idCdcBZuV5_ = undefined;
const OFm2bD2Omv3TXy3rtq = undefined;
const d3BtWDjWlv3TXy3rtq = undefined;
const KcGyxLZIQv3TXy3rtq = undefined;
const UbKku4qCvv3TXy3rtq = undefined;
const idv3TXy3rtq = undefined;
const OFm2bD2OmkjJWIIsgf = undefined;
const d3BtWDjWlkjJWIIsgf = undefined;
const KcGyxLZIQkjJWIIsgf = undefined;
const UbKku4qCvkjJWIIsgf = undefined;
const idkjJWIIsgf = undefined;
const OFm2bD2OmBb3KDoBgs = undefined;
const d3BtWDjWlBb3KDoBgs = undefined;
const KcGyxLZIQBb3KDoBgs = undefined;
const UbKku4qCvBb3KDoBgs = undefined;
const idBb3KDoBgs = undefined;
const OFm2bD2OmJz7TssHlT = undefined;
const d3BtWDjWlJz7TssHlT = undefined;
const KcGyxLZIQJz7TssHlT = undefined;
const UbKku4qCvJz7TssHlT = undefined;
const idJz7TssHlT = undefined;
const OFm2bD2OmINIECR1yQ = undefined;
const d3BtWDjWlINIECR1yQ = undefined;
const KcGyxLZIQINIECR1yQ = undefined;
const UbKku4qCvINIECR1yQ = undefined;
const idINIECR1yQ = undefined;
const OFm2bD2OmfnMTRDHB6 = undefined;
const d3BtWDjWlfnMTRDHB6 = undefined;
const KcGyxLZIQfnMTRDHB6 = undefined;
const UbKku4qCvfnMTRDHB6 = undefined;
const idfnMTRDHB6 = undefined;
const getRootLayoutProp = (
  hasLayoutTemplate,
  hasInheritedFlowEffect,
  fallback
) => {
  if (!hasLayoutTemplate) return fallback;
  return hasInheritedFlowEffect ? "position" : fallback;
};
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const query = () => ({
  from: { alias: "CdcBZuV5_", data: Projects1, type: "Collection" },
  limit: { type: "LiteralValue", value: 1 },
  offset: { type: "LiteralValue", value: 0 },
  select: [
    { collection: "CdcBZuV5_", name: "OFm2bD2Om", type: "Identifier" },
    { collection: "CdcBZuV5_", name: "d3BtWDjWl", type: "Identifier" },
    { collection: "CdcBZuV5_", name: "KcGyxLZIQ", type: "Identifier" },
    { collection: "CdcBZuV5_", name: "UbKku4qCv", type: "Identifier" },
    { collection: "CdcBZuV5_", name: "id", type: "Identifier" },
  ],
});
const QueryData = ({ query, pageSize, children }) => {
  const data = useQueryData(query);
  return children(data);
};
const query1 = () => ({
  from: { alias: "v3TXy3rtq", data: Projects1, type: "Collection" },
  limit: { type: "LiteralValue", value: 1 },
  offset: { type: "LiteralValue", value: 1 },
  select: [
    { collection: "v3TXy3rtq", name: "OFm2bD2Om", type: "Identifier" },
    { collection: "v3TXy3rtq", name: "d3BtWDjWl", type: "Identifier" },
    { collection: "v3TXy3rtq", name: "KcGyxLZIQ", type: "Identifier" },
    { collection: "v3TXy3rtq", name: "UbKku4qCv", type: "Identifier" },
    { collection: "v3TXy3rtq", name: "id", type: "Identifier" },
  ],
});
const query2 = () => ({
  from: { alias: "kjJWIIsgf", data: Projects1, type: "Collection" },
  limit: { type: "LiteralValue", value: 1 },
  offset: { type: "LiteralValue", value: 2 },
  select: [
    { collection: "kjJWIIsgf", name: "OFm2bD2Om", type: "Identifier" },
    { collection: "kjJWIIsgf", name: "d3BtWDjWl", type: "Identifier" },
    { collection: "kjJWIIsgf", name: "KcGyxLZIQ", type: "Identifier" },
    { collection: "kjJWIIsgf", name: "UbKku4qCv", type: "Identifier" },
    { collection: "kjJWIIsgf", name: "id", type: "Identifier" },
  ],
});
const query3 = () => ({
  from: { alias: "Bb3KDoBgs", data: Projects1, type: "Collection" },
  limit: { type: "LiteralValue", value: 1 },
  offset: { type: "LiteralValue", value: 3 },
  select: [
    { collection: "Bb3KDoBgs", name: "OFm2bD2Om", type: "Identifier" },
    { collection: "Bb3KDoBgs", name: "d3BtWDjWl", type: "Identifier" },
    { collection: "Bb3KDoBgs", name: "KcGyxLZIQ", type: "Identifier" },
    { collection: "Bb3KDoBgs", name: "UbKku4qCv", type: "Identifier" },
    { collection: "Bb3KDoBgs", name: "id", type: "Identifier" },
  ],
});
const query4 = () => ({
  from: { alias: "Jz7TssHlT", data: Projects1, type: "Collection" },
  limit: { type: "LiteralValue", value: 1 },
  offset: { type: "LiteralValue", value: 4 },
  select: [
    { collection: "Jz7TssHlT", name: "OFm2bD2Om", type: "Identifier" },
    { collection: "Jz7TssHlT", name: "d3BtWDjWl", type: "Identifier" },
    { collection: "Jz7TssHlT", name: "KcGyxLZIQ", type: "Identifier" },
    { collection: "Jz7TssHlT", name: "UbKku4qCv", type: "Identifier" },
    { collection: "Jz7TssHlT", name: "id", type: "Identifier" },
  ],
});
const query5 = () => ({
  from: { alias: "INIECR1yQ", data: Projects1, type: "Collection" },
  limit: { type: "LiteralValue", value: 1 },
  offset: { type: "LiteralValue", value: 5 },
  select: [
    { collection: "INIECR1yQ", name: "OFm2bD2Om", type: "Identifier" },
    { collection: "INIECR1yQ", name: "d3BtWDjWl", type: "Identifier" },
    { collection: "INIECR1yQ", name: "KcGyxLZIQ", type: "Identifier" },
    { collection: "INIECR1yQ", name: "UbKku4qCv", type: "Identifier" },
    { collection: "INIECR1yQ", name: "id", type: "Identifier" },
  ],
});
const query6 = () => ({
  from: { alias: "fnMTRDHB6", data: Projects1, type: "Collection" },
  limit: { type: "LiteralValue", value: 1 },
  offset: { type: "LiteralValue", value: 6 },
  select: [
    { collection: "fnMTRDHB6", name: "OFm2bD2Om", type: "Identifier" },
    { collection: "fnMTRDHB6", name: "d3BtWDjWl", type: "Identifier" },
    { collection: "fnMTRDHB6", name: "KcGyxLZIQ", type: "Identifier" },
    { collection: "fnMTRDHB6", name: "UbKku4qCv", type: "Identifier" },
    { collection: "fnMTRDHB6", name: "id", type: "Identifier" },
  ],
});
const humanReadableVariantMap = {
  Desktop: "WQLkyLRf1",
  Phone: "SiriE49rh",
  Tablet: "wjo_zo7q7",
};
const HTMLStyle = ({ value }) => {
  const onCanvas = useIsOnFramerCanvas();
  if (onCanvas) return null;
  return /*#__PURE__*/ _jsx("style", {
    dangerouslySetInnerHTML: { __html: value },
    "data-framer-html-style": "",
  });
};
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "WQLkyLRf1",
  };
};
const transition1 = {
  damping: 60,
  delay: 0,
  mass: 1,
  stiffness: 340,
  type: "spring",
};
const cursor = {
  alignment: "center",
  component: CustomCursor,
  offset: { x: 0, y: -5 },
  placement: "bottom",
  transition: transition1,
  variant: "V3WmbR0E9",
};
const cursor1 = {
  alignment: "center",
  component: CustomCursor,
  offset: { x: 0, y: -5 },
  placement: "bottom",
  transition: transition1,
  variant: "xybjdzTmO",
};
const cursor2 = {
  alignment: "center",
  component: CustomCursor,
  offset: { x: 0, y: -5 },
  placement: "bottom",
  transition: transition1,
  variant: "d0gSpyQ9g",
};
const cursor3 = {
  alignment: "center",
  component: CustomCursor,
  offset: { x: 0, y: -5 },
  placement: "bottom",
  transition: transition1,
  variant: "ZZXwMCEBJ",
};
const cursor4 = {
  alignment: "center",
  component: CustomCursor,
  offset: { x: 0, y: -5 },
  placement: "bottom",
  transition: transition1,
  variant: "Tb_7LPZoM",
};
const cursor5 = {
  alignment: "center",
  component: CustomCursor,
  offset: { x: 0, y: -5 },
  placement: "bottom",
  transition: transition1,
  variant: "w2P9sMrIS",
};
const cursor6 = {
  alignment: "center",
  component: CustomCursor,
  offset: { x: 0, y: -5 },
  placement: "bottom",
  transition: transition1,
  variant: "e52dTFtrn",
};
const cursor7 = {
  alignment: "center",
  component: CustomCursor,
  offset: { x: 0, y: -5 },
  placement: "bottom",
  transition: transition1,
  variant: "jXFQ8g9op",
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const metadata = React.useMemo(
    () => metadataProvider({}, activeLocale),
    [activeLocale]
  );
  useMetadata(metadata);
  const [baseVariant, hydratedBaseVariant] = useHydratedBreakpointVariants(
    variant,
    breakpoints,
    false
  );
  const gestureVariant = undefined;
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const hasLayoutTemplate = React.useContext(
    GeneratedComponentContext
  )?.isLayoutTemplate;
  const hasInheritedFlowEffect = Boolean(
    React.useContext(MotionConfigContext)?.transition?.layout
  );
  const motionLayout = getRootLayoutProp(
    hasLayoutTemplate,
    hasInheritedFlowEffect
  );
  const isDisplayed = () => {
    if (!isBrowser()) return true;
    if (["wjo_zo7q7", "SiriE49rh"].includes(baseVariant)) return false;
    return true;
  };
  const isDisplayed1 = () => {
    if (!isBrowser()) return true;
    if (["wjo_zo7q7", "SiriE49rh"].includes(baseVariant)) return true;
    return false;
  };
  useCustomCursors({
    "158va0j": cursor5,
    "15k4dvt": cursor2,
    "18hf8sl": cursor4,
    "1f7neft": cursor7,
    "1ipmc3b": cursor1,
    "1rcuw83": cursor6,
    e5w7i9: cursor3,
    or2vl9: cursor,
  });
  return /*#__PURE__*/ _jsx(GeneratedComponentContext.Provider, {
    value: {
      activeVariantId: baseVariant,
      humanReadableVariantMap,
      primaryVariantId: "WQLkyLRf1",
      variantClassNames,
    },
    children: /*#__PURE__*/ _jsxs(LayoutGroup, {
      id: layoutId ?? defaultLayoutId,
      children: [
        /*#__PURE__*/ _jsx(HTMLStyle, {
          value:
            "html body { background: var(--token-280bd9a0-bf37-41b4-a3c3-9a122b679a65, rgb(255, 255, 255)); }",
        }),
        /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          className: cx(scopingClassNames, "framer-72rtr7", className),
          ref: refBinding,
          style: { ...style },
          children: /*#__PURE__*/ _jsxs(MotionMainWithTargetElementtnt2m9, {
            className: "framer-tnt2m9",
            "data-framer-name": "Main Container",
            "data-hide-scrollbars": true,
            layout: motionLayout,
            children: [
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-6f8bvo",
                "data-framer-name": "Projects Container",
                children: [
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 5475,
                    width: componentViewport?.width || "100vw",
                    y: (componentViewport?.y || 0) + 0 + 0 + 0 + 0 + 0 + 0,
                    children: /*#__PURE__*/ _jsx(Container, {
                      className: "framer-4ep70i-container",
                      nodeId: "YfNrsp4Ki",
                      rendersWithMotion: true,
                      scopeId: "augiA20Il",
                      children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                        breakpoint: baseVariant,
                        overrides: {
                          SiriE49rh: { variant: matchVariant("A71eV9VW0") },
                          wjo_zo7q7: { variant: matchVariant("KIeh494tn") },
                        },
                        children: /*#__PURE__*/ _jsx(Projects, {
                          height: "100%",
                          id: "YfNrsp4Ki",
                          layoutId: "YfNrsp4Ki",
                          style: { width: "100%" },
                          variant: matchVariant("c8axusPUs"),
                          width: "100%",
                        }),
                      }),
                    }),
                  }),
                  isDisplayed() &&
                    /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      children: /*#__PURE__*/ _jsx(Container, {
                        className:
                          "framer-1hn0e1z-container hidden-yk56x6 hidden-13fje81",
                        "data-framer-cursor": "or2vl9",
                        isAuthoredByUser: true,
                        isModuleExternal: true,
                        nodeId: "QZxApegcD",
                        rendersWithMotion: true,
                        scopeId: "augiA20Il",
                        children: /*#__PURE__*/ _jsx(TickerScroll, {
                          alignment: "center",
                          direction: "top",
                          fadeOptions: {
                            fadeAlpha: 0,
                            fadeContent: false,
                            fadeInset: 0,
                            fadeWidth: 25,
                            overflow: false,
                          },
                          gap: 0,
                          height: "100%",
                          id: "QZxApegcD",
                          layoutId: "QZxApegcD",
                          padding: 0,
                          paddingBottom: 0,
                          paddingLeft: 0,
                          paddingPerSide: false,
                          paddingRight: 0,
                          paddingTop: 0,
                          sizingOptions: { heightType: true, widthType: false },
                          slots: [
                            /*#__PURE__*/ _jsxs(motion.div, {
                              className: "framer-ui7c8f",
                              "data-framer-name": "Projects",
                              children: [
                                /*#__PURE__*/ _jsx(motion.div, {
                                  className: "framer-1qrqp9n",
                                  children: /*#__PURE__*/ _jsx(
                                    ChildrenCanSuspend,
                                    {
                                      children: /*#__PURE__*/ _jsx(QueryData, {
                                        query: query(),
                                        children: (
                                          collection,
                                          paginationInfo,
                                          loadMore
                                        ) => {
                                          return /*#__PURE__*/ _jsx(_Fragment, {
                                            children: collection?.map(
                                              (
                                                {
                                                  d3BtWDjWl: d3BtWDjWlCdcBZuV5_,
                                                  id: idCdcBZuV5_,
                                                  KcGyxLZIQ: KcGyxLZIQCdcBZuV5_,
                                                  OFm2bD2Om: OFm2bD2OmCdcBZuV5_,
                                                  UbKku4qCv: UbKku4qCvCdcBZuV5_,
                                                },
                                                index
                                              ) => {
                                                OFm2bD2OmCdcBZuV5_ ??= "";
                                                d3BtWDjWlCdcBZuV5_ ??= "";
                                                KcGyxLZIQCdcBZuV5_ ??= "";
                                                UbKku4qCvCdcBZuV5_ ??= "";
                                                return /*#__PURE__*/ _jsx(
                                                  LayoutGroup,
                                                  {
                                                    id: `CdcBZuV5_-${idCdcBZuV5_}`,
                                                    children:
                                                      /*#__PURE__*/ _jsx(
                                                        PathVariablesContext.Provider,
                                                        {
                                                          value: {
                                                            OFm2bD2Om:
                                                              OFm2bD2OmCdcBZuV5_,
                                                          },
                                                          children:
                                                            /*#__PURE__*/ _jsx(
                                                              Link,
                                                              {
                                                                href: {
                                                                  pathVariables:
                                                                    {
                                                                      OFm2bD2Om:
                                                                        OFm2bD2OmCdcBZuV5_,
                                                                    },
                                                                  webPageId:
                                                                    "eibvSHdOT",
                                                                },
                                                                motionChild: true,
                                                                nodeId:
                                                                  "cAaU2jT4D",
                                                                openInNewTab: false,
                                                                scopeId:
                                                                  "augiA20Il",
                                                                children:
                                                                  /*#__PURE__*/ _jsx(
                                                                    MotionAWithInstantReset1vx9gti,
                                                                    {
                                                                      className:
                                                                        "framer-1vx9gti framer-lux5qc",
                                                                      "data-framer-cursor":
                                                                        "1ipmc3b",
                                                                      children:
                                                                        /*#__PURE__*/ _jsx(
                                                                          ComponentViewportProvider,
                                                                          {
                                                                            height: 192,
                                                                            width:
                                                                              "720px",
                                                                            children:
                                                                              /*#__PURE__*/ _jsx(
                                                                                Container,
                                                                                {
                                                                                  className:
                                                                                    "framer-1051aht-container",
                                                                                  inComponentSlot: true,
                                                                                  nodeId:
                                                                                    "Rp2y6ocl6",
                                                                                  rendersWithMotion: true,
                                                                                  scopeId:
                                                                                    "augiA20Il",
                                                                                  children:
                                                                                    /*#__PURE__*/ _jsx(
                                                                                      ProjectInfoListView,
                                                                                      {
                                                                                        height:
                                                                                          "100%",
                                                                                        id: "Rp2y6ocl6",
                                                                                        layoutId:
                                                                                          "Rp2y6ocl6",
                                                                                        Lj_GWxxRQ:
                                                                                          UbKku4qCvCdcBZuV5_,
                                                                                        OtyT0gRza:
                                                                                          KcGyxLZIQCdcBZuV5_,
                                                                                        style:
                                                                                          {
                                                                                            width:
                                                                                              "100%",
                                                                                          },
                                                                                        UHgttF2ZR:
                                                                                          d3BtWDjWlCdcBZuV5_,
                                                                                        width:
                                                                                          "100%",
                                                                                      }
                                                                                    ),
                                                                                }
                                                                              ),
                                                                          }
                                                                        ),
                                                                    }
                                                                  ),
                                                              }
                                                            ),
                                                        }
                                                      ),
                                                  },
                                                  idCdcBZuV5_
                                                );
                                              }
                                            ),
                                          });
                                        },
                                      }),
                                    }
                                  ),
                                }),
                                /*#__PURE__*/ _jsx(motion.div, {
                                  className: "framer-10kdk2o",
                                  children: /*#__PURE__*/ _jsx(
                                    ChildrenCanSuspend,
                                    {
                                      children: /*#__PURE__*/ _jsx(QueryData, {
                                        query: query1(),
                                        children: (
                                          collection1,
                                          paginationInfo1,
                                          loadMore1
                                        ) => {
                                          return /*#__PURE__*/ _jsx(_Fragment, {
                                            children: collection1?.map(
                                              (
                                                {
                                                  d3BtWDjWl: d3BtWDjWlv3TXy3rtq,
                                                  id: idv3TXy3rtq,
                                                  KcGyxLZIQ: KcGyxLZIQv3TXy3rtq,
                                                  OFm2bD2Om: OFm2bD2Omv3TXy3rtq,
                                                  UbKku4qCv: UbKku4qCvv3TXy3rtq,
                                                },
                                                index1
                                              ) => {
                                                OFm2bD2Omv3TXy3rtq ??= "";
                                                d3BtWDjWlv3TXy3rtq ??= "";
                                                KcGyxLZIQv3TXy3rtq ??= "";
                                                UbKku4qCvv3TXy3rtq ??= "";
                                                return /*#__PURE__*/ _jsx(
                                                  LayoutGroup,
                                                  {
                                                    id: `v3TXy3rtq-${idv3TXy3rtq}`,
                                                    children:
                                                      /*#__PURE__*/ _jsx(
                                                        PathVariablesContext.Provider,
                                                        {
                                                          value: {
                                                            OFm2bD2Om:
                                                              OFm2bD2Omv3TXy3rtq,
                                                          },
                                                          children:
                                                            /*#__PURE__*/ _jsx(
                                                              Link,
                                                              {
                                                                href: {
                                                                  pathVariables:
                                                                    {
                                                                      OFm2bD2Om:
                                                                        OFm2bD2Omv3TXy3rtq,
                                                                    },
                                                                  webPageId:
                                                                    "eibvSHdOT",
                                                                },
                                                                motionChild: true,
                                                                nodeId:
                                                                  "zMs1M_qCZ",
                                                                openInNewTab: false,
                                                                scopeId:
                                                                  "augiA20Il",
                                                                children:
                                                                  /*#__PURE__*/ _jsx(
                                                                    MotionAWithInstantReset1kr9bvu,
                                                                    {
                                                                      className:
                                                                        "framer-1kr9bvu framer-lux5qc",
                                                                      "data-framer-cursor":
                                                                        "15k4dvt",
                                                                      children:
                                                                        /*#__PURE__*/ _jsx(
                                                                          ComponentViewportProvider,
                                                                          {
                                                                            height: 192,
                                                                            width:
                                                                              "720px",
                                                                            children:
                                                                              /*#__PURE__*/ _jsx(
                                                                                Container,
                                                                                {
                                                                                  className:
                                                                                    "framer-14crwuo-container",
                                                                                  inComponentSlot: true,
                                                                                  nodeId:
                                                                                    "oKuDPblWx",
                                                                                  rendersWithMotion: true,
                                                                                  scopeId:
                                                                                    "augiA20Il",
                                                                                  children:
                                                                                    /*#__PURE__*/ _jsx(
                                                                                      ProjectInfoListView,
                                                                                      {
                                                                                        height:
                                                                                          "100%",
                                                                                        id: "oKuDPblWx",
                                                                                        layoutId:
                                                                                          "oKuDPblWx",
                                                                                        Lj_GWxxRQ:
                                                                                          UbKku4qCvv3TXy3rtq,
                                                                                        OtyT0gRza:
                                                                                          KcGyxLZIQv3TXy3rtq,
                                                                                        style:
                                                                                          {
                                                                                            width:
                                                                                              "100%",
                                                                                          },
                                                                                        UHgttF2ZR:
                                                                                          d3BtWDjWlv3TXy3rtq,
                                                                                        width:
                                                                                          "100%",
                                                                                      }
                                                                                    ),
                                                                                }
                                                                              ),
                                                                          }
                                                                        ),
                                                                    }
                                                                  ),
                                                              }
                                                            ),
                                                        }
                                                      ),
                                                  },
                                                  idv3TXy3rtq
                                                );
                                              }
                                            ),
                                          });
                                        },
                                      }),
                                    }
                                  ),
                                }),
                                /*#__PURE__*/ _jsx(motion.div, {
                                  className: "framer-cp1dyt",
                                  children: /*#__PURE__*/ _jsx(
                                    ChildrenCanSuspend,
                                    {
                                      children: /*#__PURE__*/ _jsx(QueryData, {
                                        query: query2(),
                                        children: (
                                          collection2,
                                          paginationInfo2,
                                          loadMore2
                                        ) => {
                                          return /*#__PURE__*/ _jsx(_Fragment, {
                                            children: collection2?.map(
                                              (
                                                {
                                                  d3BtWDjWl: d3BtWDjWlkjJWIIsgf,
                                                  id: idkjJWIIsgf,
                                                  KcGyxLZIQ: KcGyxLZIQkjJWIIsgf,
                                                  OFm2bD2Om: OFm2bD2OmkjJWIIsgf,
                                                  UbKku4qCv: UbKku4qCvkjJWIIsgf,
                                                },
                                                index2
                                              ) => {
                                                OFm2bD2OmkjJWIIsgf ??= "";
                                                d3BtWDjWlkjJWIIsgf ??= "";
                                                KcGyxLZIQkjJWIIsgf ??= "";
                                                UbKku4qCvkjJWIIsgf ??= "";
                                                return /*#__PURE__*/ _jsx(
                                                  LayoutGroup,
                                                  {
                                                    id: `kjJWIIsgf-${idkjJWIIsgf}`,
                                                    children:
                                                      /*#__PURE__*/ _jsx(
                                                        PathVariablesContext.Provider,
                                                        {
                                                          value: {
                                                            OFm2bD2Om:
                                                              OFm2bD2OmkjJWIIsgf,
                                                          },
                                                          children:
                                                            /*#__PURE__*/ _jsx(
                                                              Link,
                                                              {
                                                                href: {
                                                                  pathVariables:
                                                                    {
                                                                      OFm2bD2Om:
                                                                        OFm2bD2OmkjJWIIsgf,
                                                                    },
                                                                  webPageId:
                                                                    "eibvSHdOT",
                                                                },
                                                                motionChild: true,
                                                                nodeId:
                                                                  "S4AItlHWu",
                                                                openInNewTab: false,
                                                                scopeId:
                                                                  "augiA20Il",
                                                                children:
                                                                  /*#__PURE__*/ _jsx(
                                                                    MotionAWithInstantResetfq721s,
                                                                    {
                                                                      className:
                                                                        "framer-fq721s framer-lux5qc",
                                                                      "data-framer-cursor":
                                                                        "e5w7i9",
                                                                      children:
                                                                        /*#__PURE__*/ _jsx(
                                                                          ComponentViewportProvider,
                                                                          {
                                                                            height: 192,
                                                                            width:
                                                                              "720px",
                                                                            children:
                                                                              /*#__PURE__*/ _jsx(
                                                                                Container,
                                                                                {
                                                                                  className:
                                                                                    "framer-1rgftvz-container",
                                                                                  inComponentSlot: true,
                                                                                  nodeId:
                                                                                    "yRd4tmeq0",
                                                                                  rendersWithMotion: true,
                                                                                  scopeId:
                                                                                    "augiA20Il",
                                                                                  children:
                                                                                    /*#__PURE__*/ _jsx(
                                                                                      ProjectInfoListView,
                                                                                      {
                                                                                        height:
                                                                                          "100%",
                                                                                        id: "yRd4tmeq0",
                                                                                        layoutId:
                                                                                          "yRd4tmeq0",
                                                                                        Lj_GWxxRQ:
                                                                                          UbKku4qCvkjJWIIsgf,
                                                                                        OtyT0gRza:
                                                                                          KcGyxLZIQkjJWIIsgf,
                                                                                        style:
                                                                                          {
                                                                                            width:
                                                                                              "100%",
                                                                                          },
                                                                                        UHgttF2ZR:
                                                                                          d3BtWDjWlkjJWIIsgf,
                                                                                        width:
                                                                                          "100%",
                                                                                      }
                                                                                    ),
                                                                                }
                                                                              ),
                                                                          }
                                                                        ),
                                                                    }
                                                                  ),
                                                              }
                                                            ),
                                                        }
                                                      ),
                                                  },
                                                  idkjJWIIsgf
                                                );
                                              }
                                            ),
                                          });
                                        },
                                      }),
                                    }
                                  ),
                                }),
                                /*#__PURE__*/ _jsx(motion.div, {
                                  className: "framer-1693g9e",
                                  children: /*#__PURE__*/ _jsx(
                                    ChildrenCanSuspend,
                                    {
                                      children: /*#__PURE__*/ _jsx(QueryData, {
                                        query: query3(),
                                        children: (
                                          collection3,
                                          paginationInfo3,
                                          loadMore3
                                        ) => {
                                          return /*#__PURE__*/ _jsx(_Fragment, {
                                            children: collection3?.map(
                                              (
                                                {
                                                  d3BtWDjWl: d3BtWDjWlBb3KDoBgs,
                                                  id: idBb3KDoBgs,
                                                  KcGyxLZIQ: KcGyxLZIQBb3KDoBgs,
                                                  OFm2bD2Om: OFm2bD2OmBb3KDoBgs,
                                                  UbKku4qCv: UbKku4qCvBb3KDoBgs,
                                                },
                                                index3
                                              ) => {
                                                OFm2bD2OmBb3KDoBgs ??= "";
                                                d3BtWDjWlBb3KDoBgs ??= "";
                                                KcGyxLZIQBb3KDoBgs ??= "";
                                                UbKku4qCvBb3KDoBgs ??= "";
                                                return /*#__PURE__*/ _jsx(
                                                  LayoutGroup,
                                                  {
                                                    id: `Bb3KDoBgs-${idBb3KDoBgs}`,
                                                    children:
                                                      /*#__PURE__*/ _jsx(
                                                        PathVariablesContext.Provider,
                                                        {
                                                          value: {
                                                            OFm2bD2Om:
                                                              OFm2bD2OmBb3KDoBgs,
                                                          },
                                                          children:
                                                            /*#__PURE__*/ _jsx(
                                                              Link,
                                                              {
                                                                href: {
                                                                  pathVariables:
                                                                    {
                                                                      OFm2bD2Om:
                                                                        OFm2bD2OmBb3KDoBgs,
                                                                    },
                                                                  webPageId:
                                                                    "eibvSHdOT",
                                                                },
                                                                motionChild: true,
                                                                nodeId:
                                                                  "GoC9pzuR4",
                                                                openInNewTab: false,
                                                                scopeId:
                                                                  "augiA20Il",
                                                                children:
                                                                  /*#__PURE__*/ _jsx(
                                                                    MotionAWithInstantResetrbbuic,
                                                                    {
                                                                      className:
                                                                        "framer-rbbuic framer-lux5qc",
                                                                      "data-framer-cursor":
                                                                        "18hf8sl",
                                                                      children:
                                                                        /*#__PURE__*/ _jsx(
                                                                          ComponentViewportProvider,
                                                                          {
                                                                            height: 192,
                                                                            width:
                                                                              "720px",
                                                                            children:
                                                                              /*#__PURE__*/ _jsx(
                                                                                Container,
                                                                                {
                                                                                  className:
                                                                                    "framer-133y9yx-container",
                                                                                  inComponentSlot: true,
                                                                                  nodeId:
                                                                                    "L2mxDvl0n",
                                                                                  rendersWithMotion: true,
                                                                                  scopeId:
                                                                                    "augiA20Il",
                                                                                  children:
                                                                                    /*#__PURE__*/ _jsx(
                                                                                      ProjectInfoListView,
                                                                                      {
                                                                                        height:
                                                                                          "100%",
                                                                                        id: "L2mxDvl0n",
                                                                                        layoutId:
                                                                                          "L2mxDvl0n",
                                                                                        Lj_GWxxRQ:
                                                                                          UbKku4qCvBb3KDoBgs,
                                                                                        OtyT0gRza:
                                                                                          KcGyxLZIQBb3KDoBgs,
                                                                                        style:
                                                                                          {
                                                                                            width:
                                                                                              "100%",
                                                                                          },
                                                                                        UHgttF2ZR:
                                                                                          d3BtWDjWlBb3KDoBgs,
                                                                                        width:
                                                                                          "100%",
                                                                                      }
                                                                                    ),
                                                                                }
                                                                              ),
                                                                          }
                                                                        ),
                                                                    }
                                                                  ),
                                                              }
                                                            ),
                                                        }
                                                      ),
                                                  },
                                                  idBb3KDoBgs
                                                );
                                              }
                                            ),
                                          });
                                        },
                                      }),
                                    }
                                  ),
                                }),
                                
                              ],
                            }),
                          ],
                          speed: 0.6,
                          style: { height: "100%", width: "100%" },
                          width: "100%",
                        }),
                      }),
                    }),
                ],
              }),
              isDisplayed1() &&
                /*#__PURE__*/ _jsx(PropertyOverrides, {
                  breakpoint: baseVariant,
                  overrides: {
                    SiriE49rh: {
                      height: 639,
                      width: componentViewport?.width || "100vw",
                      y: (componentViewport?.y || 0) + 0 + 0 + 0 + 5475,
                    },
                    wjo_zo7q7: {
                      height: 639,
                      width: componentViewport?.width || "100vw",
                      y: (componentViewport?.y || 0) + 0 + 0 + 0 + 5475,
                    },
                  },
                  children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    children: /*#__PURE__*/ _jsx(Container, {
                      className: "framer-1f7zz0w-container hidden-72rtr7",
                      nodeId: "AjyFtsQ9D",
                      rendersWithMotion: true,
                      scopeId: "augiA20Il",
                      children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                        breakpoint: baseVariant,
                        overrides: {
                          SiriE49rh: { variant: matchVariant("B30ALooui") },
                          wjo_zo7q7: { variant: matchVariant("STYxvlWAm") },
                        },
                        children: /*#__PURE__*/ _jsx(BigLogo, {
                          height: "100%",
                          id: "AjyFtsQ9D",
                          layoutId: "AjyFtsQ9D",
                          style: { width: "100%" },
                          variant: matchVariant("FoP8lNZ1m"),
                          width: "100%",
                        }),
                      }),
                    }),
                  }),
                }),
              isDisplayed1() &&
                /*#__PURE__*/ _jsx(PropertyOverrides, {
                  breakpoint: baseVariant,
                  overrides: {
                    SiriE49rh: {
                      height: 1,
                      width: componentViewport?.width || "100vw",
                      y: (componentViewport?.y || 0) + 0 + 0 + 0 + 6114,
                    },
                    wjo_zo7q7: {
                      height: 1,
                      width: componentViewport?.width || "100vw",
                      y: (componentViewport?.y || 0) + 0 + 0 + 0 + 6114,
                    },
                  },
                  children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    children: /*#__PURE__*/ _jsx(Container, {
                      className: "framer-mfyutm-container hidden-72rtr7",
                      nodeId: "ozXx4PikC",
                      rendersWithMotion: true,
                      scopeId: "augiA20Il",
                      children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                        breakpoint: baseVariant,
                        overrides: {
                          SiriE49rh: { variant: matchVariant("bDu_rpRlI") },
                        },
                        children: /*#__PURE__*/ _jsx(HR, {
                          height: "100%",
                          id: "ozXx4PikC",
                          layoutId: "ozXx4PikC",
                          style: { width: "100%" },
                          variant: matchVariant("gYcI3A2jy"),
                          width: "100%",
                        }),
                      }),
                    }),
                  }),
                }),
              isDisplayed1() &&
                /*#__PURE__*/ _jsx(PropertyOverrides, {
                  breakpoint: baseVariant,
                  overrides: {
                    SiriE49rh: {
                      height: 485,
                      width: componentViewport?.width || "100vw",
                      y: (componentViewport?.y || 0) + 0 + 0 + 0 + 6115,
                    },
                    wjo_zo7q7: {
                      height: 485,
                      width: componentViewport?.width || "100vw",
                      y: (componentViewport?.y || 0) + 0 + 0 + 0 + 6115,
                    },
                  },
                  children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    children: /*#__PURE__*/ _jsx(Container, {
                      className: "framer-n0lf92-container hidden-72rtr7",
                      nodeId: "cOKCfa0jY",
                      rendersWithMotion: true,
                      scopeId: "augiA20Il",
                      children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                        breakpoint: baseVariant,
                        overrides: {
                          SiriE49rh: {
                            variant: matchVariant("zLkwbJJ3P"),
                            X8QILq4Jp: false,
                          },
                          wjo_zo7q7: { X8QILq4Jp: false },
                        },
                        children: /*#__PURE__*/ _jsx(Footer, {
                          height: "100%",
                          id: "cOKCfa0jY",
                          layoutId: "cOKCfa0jY",
                          style: { width: "100%" },
                          variant: matchVariant("Y4qJMr6hn"),
                          width: "100%",
                          X8QILq4Jp: true,
                        }),
                      }),
                    }),
                  }),
                }),
            ],
          }),
        }),
        /*#__PURE__*/ _jsx("div", { id: "overlay" }),
      ],
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-JHLJv.framer-lux5qc, .framer-JHLJv .framer-lux5qc { display: block; }",
  ".framer-JHLJv.framer-72rtr7 { align-content: center; align-items: center; background-color: var(--token-280bd9a0-bf37-41b4-a3c3-9a122b679a65, #ffffff); display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1200px; }",
  ".framer-JHLJv .framer-tnt2m9 { align-content: center; align-items: center; background-color: var(--token-280bd9a0-bf37-41b4-a3c3-9a122b679a65, #ffffff); display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 100vh; justify-content: flex-start; overflow: auto; padding: 0px; position: relative; width: 100%; }",
  ".framer-JHLJv .framer-6f8bvo { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 100vh; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
  ".framer-JHLJv .framer-4ep70i-container { flex: none; height: auto; position: relative; width: 100%; }",
  ".framer-JHLJv .framer-1hn0e1z-container { flex: none; height: 100vh; left: 0px; position: absolute; right: 0px; top: 0px; z-index: 1; }",
  ".framer-JHLJv .framer-ui7c8f { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px 240px 0px 240px; position: relative; width: 1200px; }",
  ".framer-JHLJv .framer-1qrqp9n, .framer-JHLJv .framer-10kdk2o, .framer-JHLJv .framer-cp1dyt, .framer-JHLJv .framer-1693g9e, .framer-JHLJv .framer-rjguy, .framer-JHLJv .framer-rcym12, .framer-JHLJv .framer-1ixs3tg { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; padding: 0px; position: relative; width: 100%; }",
  ".framer-JHLJv .framer-1vx9gti, .framer-JHLJv .framer-1kr9bvu, .framer-JHLJv .framer-fq721s, .framer-JHLJv .framer-rbbuic, .framer-JHLJv .framer-pxj2pe, .framer-JHLJv .framer-1k2424s, .framer-JHLJv .framer-1n6m2ma { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; text-decoration: none; width: 100%; }",
  ".framer-JHLJv .framer-1051aht-container, .framer-JHLJv .framer-14crwuo-container, .framer-JHLJv .framer-1rgftvz-container, .framer-JHLJv .framer-133y9yx-container, .framer-JHLJv .framer-1fyi9v9-container, .framer-JHLJv .framer-n49ur-container, .framer-JHLJv .framer-1vt85ms-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
  ".framer-JHLJv .framer-1f7zz0w-container, .framer-JHLJv .framer-mfyutm-container { flex: none; height: auto; position: relative; width: 100%; z-index: 2; }",
  ".framer-JHLJv .framer-n0lf92-container { flex: none; height: auto; position: relative; width: 100%; z-index: 0; }",
  '.framer-JHLJv[data-hide-scrollbars="true"]::-webkit-scrollbar, .framer-JHLJv [data-hide-scrollbars="true"]::-webkit-scrollbar { width: 0px; height: 0px; }',
  '.framer-JHLJv[data-hide-scrollbars="true"]::-webkit-scrollbar-thumb, .framer-JHLJv [data-hide-scrollbars="true"]::-webkit-scrollbar-thumb { background: transparent; }',
  '.framer-JHLJv[data-hide-scrollbars="true"], .framer-JHLJv [data-hide-scrollbars="true"] { scrollbar-width: none; }',
  "@media (min-width: 810px) and (max-width: 1199.98px) { .framer-JHLJv.framer-72rtr7 { width: 810px; } .framer-JHLJv .framer-6f8bvo { height: min-content; } .framer-JHLJv .framer-4ep70i-container { order: 0; }}",
  "@media (max-width: 809.98px) { .framer-JHLJv.framer-72rtr7 { width: 390px; } .framer-JHLJv .framer-6f8bvo { height: min-content; }}",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 1293
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"wjo_zo7q7":{"layout":["fixed","auto"]},"SiriE49rh":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerAcceptsLayoutTemplate true
 * @framerScrollSections false
 * @framerResponsiveScreen true
 * @framerLayoutTemplateFlowEffect true
 */ const FrameraugiA20Il = withCSS(Component, css, "framer-JHLJv");
export default FrameraugiA20Il;
FrameraugiA20Il.displayName = "Home";
FrameraugiA20Il.defaultProps = { height: 1293, width: 1200 };
addFonts(
  FrameraugiA20Il,
  [
    { explicitInter: true, fonts: [] },
    ...ProjectsFonts,
    ...ProjectInfoListViewFonts,
    ...TickerScrollFonts,
    ...BigLogoFonts,
    ...HRFonts,
    ...FooterFonts,
    ...CustomCursorFonts,
  ],
  { supportsExplicitInterCodegen: true }
);
FrameraugiA20Il.loader = {
  load: (props, context) => {
    const locale = context.locale;
    const queryCacheEntry = queryCache.get(query(), locale);
    const queryCacheEntry1 = queryCache.get(query1(), locale);
    const queryCacheEntry2 = queryCache.get(query2(), locale);
    const queryCacheEntry3 = queryCache.get(query3(), locale);
    const queryCacheEntry4 = queryCache.get(query4(), locale);
    const queryCacheEntry5 = queryCache.get(query5(), locale);
    const queryCacheEntry6 = queryCache.get(query6(), locale);
    return Promise.allSettled([
      queryCacheEntry.preload(),
      queryCacheEntry1.preload(),
      queryCacheEntry2.preload(),
      queryCacheEntry3.preload(),
      queryCacheEntry4.preload(),
      queryCacheEntry5.preload(),
      queryCacheEntry6.preload(),
      forwardLoader(Projects, {}, context),
      forwardLoader(BigLogo, {}, context),
      forwardLoader(HR, {}, context),
      forwardLoader(Footer, {}, context),
      (async () => {
        const parentData = (await queryCacheEntry.readMaybeAsync()) ?? [];
        return Promise.allSettled(
          parentData.flatMap((item) =>
            forwardLoader(ProjectInfoListView, {}, context)
          )
        );
      })(),
      (async () => {
        const parentData = (await queryCacheEntry1.readMaybeAsync()) ?? [];
        return Promise.allSettled(
          parentData.flatMap((item) =>
            forwardLoader(ProjectInfoListView, {}, context)
          )
        );
      })(),
      (async () => {
        const parentData = (await queryCacheEntry2.readMaybeAsync()) ?? [];
        return Promise.allSettled(
          parentData.flatMap((item) =>
            forwardLoader(ProjectInfoListView, {}, context)
          )
        );
      })(),
      (async () => {
        const parentData = (await queryCacheEntry3.readMaybeAsync()) ?? [];
        return Promise.allSettled(
          parentData.flatMap((item) =>
            forwardLoader(ProjectInfoListView, {}, context)
          )
        );
      })(),
      (async () => {
        const parentData = (await queryCacheEntry4.readMaybeAsync()) ?? [];
        return Promise.allSettled(
          parentData.flatMap((item) =>
            forwardLoader(ProjectInfoListView, {}, context)
          )
        );
      })(),
      (async () => {
        const parentData = (await queryCacheEntry5.readMaybeAsync()) ?? [];
        return Promise.allSettled(
          parentData.flatMap((item) =>
            forwardLoader(ProjectInfoListView, {}, context)
          )
        );
      })(),
      (async () => {
        const parentData = (await queryCacheEntry6.readMaybeAsync()) ?? [];
        return Promise.allSettled(
          parentData.flatMap((item) =>
            forwardLoader(ProjectInfoListView, {}, context)
          )
        );
      })(),
    ]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    queryParamNames: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FrameraugiA20Il",
      slots: [],
      annotations: {
        framerScrollSections: "false",
        framerComponentViewportWidth: "true",
        framerIntrinsicWidth: "1200",
        framerColorSyntax: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"wjo_zo7q7":{"layout":["fixed","auto"]},"SiriE49rh":{"layout":["fixed","auto"]}}}',
        framerContractVersion: "1",
        framerIntrinsicHeight: "1293",
        framerImmutableVariables: "true",
        framerDisplayContentsDiv: "false",
        framerAutoSizeImages: "true",
        framerLayoutTemplateFlowEffect: "true",
        framerAcceptsLayoutTemplate: "true",
        framerResponsiveScreen: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
