// Generated by Framer (7bfce40)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  ComponentViewportProvider,
  Container,
  cx,
  forwardLoader,
  GeneratedComponentContext,
  getFonts,
  PropertyOverrides,
  useComponentViewport,
  useCustomCursors,
  useHydratedBreakpointVariants,
  useIsOnFramerCanvas,
  useLocaleInfo,
  useMetadata,
  withCodeBoundaryForOverrides,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import CustomCursor from "#framer/local/canvasComponent/tDvkQwQu9/tDvkQwQu9.js";
import StudioPage from "#framer/local/canvasComponent/TZHn0ZDL7/TZHn0ZDL7.js";
import { withTargetElement } from "#framer/local/codeFile/EwMCwzI/Crazy_Navigation.js";
import metadataProvider from "#framer/local/webPageMetadata/ybNXXBVS7/ybNXXBVS7.js";
const StudioPageFonts = getFonts(StudioPage);
const MotionMainWithTargetElementc5jmkb = withCodeBoundaryForOverrides(
  motion.main,
  { nodeId: "cEgJ8Ndxk", override: withTargetElement, scopeId: "ybNXXBVS7" }
);
const CustomCursorFonts = getFonts(CustomCursor);
const breakpoints = {
  DQBzVE1h4: "(min-width: 1200px)",
  jgnTyzNJG: "(max-width: 809.98px)",
  P75KikInj: "(min-width: 810px) and (max-width: 1199.98px)",
};
const isBrowser = () => typeof document !== "undefined";
export const queryParamNames = [];
const serializationHash = "framer-TZXOk";
const variantClassNames = {
  DQBzVE1h4: "framer-v-1oqm9gd",
  jgnTyzNJG: "framer-v-1vt8rfa",
  P75KikInj: "framer-v-h3tm0p",
};
const getRootLayoutProp = (
  hasLayoutTemplate,
  hasInheritedFlowEffect,
  fallback
) => {
  if (!hasLayoutTemplate) return fallback;
  return hasInheritedFlowEffect ? "position" : fallback;
};
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const humanReadableVariantMap = {
  Desktop: "DQBzVE1h4",
  Phone: "jgnTyzNJG",
  Tablet: "P75KikInj",
};
const HTMLStyle = ({ value }) => {
  const onCanvas = useIsOnFramerCanvas();
  if (onCanvas) return null;
  return /*#__PURE__*/ _jsx("style", {
    dangerouslySetInnerHTML: { __html: value },
    "data-framer-html-style": "",
  });
};
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "DQBzVE1h4",
  };
};
const transition1 = {
  damping: 60,
  delay: 0,
  mass: 1,
  stiffness: 340,
  type: "spring",
};
const cursor = {
  alignment: "center",
  component: CustomCursor,
  offset: { x: 0, y: -5 },
  placement: "bottom",
  transition: transition1,
  variant: "tygU5dV70",
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const metadata = React.useMemo(
    () => metadataProvider({}, activeLocale),
    [activeLocale]
  );
  useMetadata(metadata);
  const [baseVariant, hydratedBaseVariant] = useHydratedBreakpointVariants(
    variant,
    breakpoints,
    false
  );
  const gestureVariant = undefined;
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const hasLayoutTemplate = React.useContext(
    GeneratedComponentContext
  )?.isLayoutTemplate;
  const hasInheritedFlowEffect = Boolean(
    React.useContext(MotionConfigContext)?.transition?.layout
  );
  const motionLayout = getRootLayoutProp(
    hasLayoutTemplate,
    hasInheritedFlowEffect
  );
  useCustomCursors({ lgbmwx: cursor });
  return /*#__PURE__*/ _jsx(GeneratedComponentContext.Provider, {
    value: {
      activeVariantId: baseVariant,
      humanReadableVariantMap,
      primaryVariantId: "DQBzVE1h4",
      variantClassNames,
    },
    children: /*#__PURE__*/ _jsxs(LayoutGroup, {
      id: layoutId ?? defaultLayoutId,
      children: [
        /*#__PURE__*/ _jsx(HTMLStyle, {
          value:
            "html body { background: var(--token-280bd9a0-bf37-41b4-a3c3-9a122b679a65, rgb(255, 255, 255)); }",
        }),
        /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          className: cx(scopingClassNames, "framer-1oqm9gd", className),
          ref: refBinding,
          style: { ...style },
          children: /*#__PURE__*/ _jsx(MotionMainWithTargetElementc5jmkb, {
            className: "framer-c5jmkb",
            "data-framer-name": "Main Container",
            layout: motionLayout,
            children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 11342,
              width: componentViewport?.width || "100vw",
              y: (componentViewport?.y || 0) + 0 + 0 + 0 + 0,
              children: /*#__PURE__*/ _jsx(Container, {
                className: "framer-vyiolc-container",
                nodeId: "L1K6S_saf",
                rendersWithMotion: true,
                scopeId: "ybNXXBVS7",
                children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                  breakpoint: baseVariant,
                  overrides: {
                    jgnTyzNJG: { variant: matchVariant("a3Ksy2Aey") },
                    P75KikInj: { variant: matchVariant("LfaNWMMU0") },
                  },
                  children: /*#__PURE__*/ _jsx(StudioPage, {
                    fXZZgO5sJ: "lgbmwx",
                    height: "100%",
                    id: "L1K6S_saf",
                    layoutId: "L1K6S_saf",
                    style: { width: "100%" },
                    variant: matchVariant("nq0MjF15D"),
                    width: "100%",
                  }),
                }),
              }),
            }),
          }),
        }),
        /*#__PURE__*/ _jsx("div", { id: "overlay" }),
      ],
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-TZXOk.framer-1v4ooqs, .framer-TZXOk .framer-1v4ooqs { display: block; }",
  ".framer-TZXOk.framer-1oqm9gd { align-content: center; align-items: center; background-color: var(--token-280bd9a0-bf37-41b4-a3c3-9a122b679a65, #ffffff); display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1200px; }",
  ".framer-TZXOk .framer-c5jmkb { align-content: flex-start; align-items: flex-start; background-color: var(--token-280bd9a0-bf37-41b4-a3c3-9a122b679a65, #ffffff); display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 100vh; justify-content: flex-start; overflow: auto; padding: 0px; position: relative; width: 100%; }",
  ".framer-TZXOk .framer-vyiolc-container { flex: none; height: auto; position: relative; width: 100%; }",
  "@media (min-width: 810px) and (max-width: 1199.98px) { .framer-TZXOk.framer-1oqm9gd { width: 810px; }}",
  "@media (max-width: 809.98px) { .framer-TZXOk.framer-1oqm9gd { width: 390px; }}",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 1293
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"P75KikInj":{"layout":["fixed","auto"]},"jgnTyzNJG":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerAcceptsLayoutTemplate true
 * @framerScrollSections false
 * @framerResponsiveScreen true
 * @framerLayoutTemplateFlowEffect true
 */ const FramerybNXXBVS7 = withCSS(Component, css, "framer-TZXOk");
export default FramerybNXXBVS7;
FramerybNXXBVS7.displayName = "Page";
FramerybNXXBVS7.defaultProps = { height: 1293, width: 1200 };
addFonts(
  FramerybNXXBVS7,
  [
    { explicitInter: true, fonts: [] },
    ...StudioPageFonts,
    ...CustomCursorFonts,
  ],
  { supportsExplicitInterCodegen: true }
);
FramerybNXXBVS7.loader = {
  load: (props, context) => {
    const locale = context.locale;
    return Promise.allSettled([forwardLoader(StudioPage, {}, context)]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    queryParamNames: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    default: {
      type: "reactComponent",
      name: "FramerybNXXBVS7",
      slots: [],
      annotations: {
        framerResponsiveScreen: "true",
        framerDisplayContentsDiv: "false",
        framerContractVersion: "1",
        framerComponentViewportWidth: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"P75KikInj":{"layout":["fixed","auto"]},"jgnTyzNJG":{"layout":["fixed","auto"]}}}',
        framerIntrinsicWidth: "1200",
        framerLayoutTemplateFlowEffect: "true",
        framerIntrinsicHeight: "1293",
        framerAutoSizeImages: "true",
        framerAcceptsLayoutTemplate: "true",
        framerImmutableVariables: "true",
        framerScrollSections: "false",
        framerColorSyntax: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
