// Generated by Framer (e0e363b)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  Link,
  RichText,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import PixelRevealOnAppear from "https://framerusercontent.com/modules/XJI2bJ8SPVUDX2JCB1jg/TwaADUwv1gxkm2ljmNdC/PixelRevealOnAppear.js";
import * as sharedStyle1 from "https://framerusercontent.com/modules/rF1p7PEbjm6gIBZEB1jH/qdOMyFKkAA8nd5UnQ2RY/i3WCJXRxw.js";
import * as sharedStyle from "https://framerusercontent.com/modules/GgteY8irBGfUzh8z4mh2/NzDgB7DilEKK0dJEeHtg/mMKAraaKM.js";
import * as sharedStyle2 from "https://framerusercontent.com/modules/kICQBgc7e5zUwiKdhF6P/ujkMYgogUnlWPxBynzgd/qxloupasW.js";
const PixelRevealOnAppearFonts = getFonts(PixelRevealOnAppear);
const serializationHash = "framer-xKLZq";
const variantClassNames = { Dbatgq_R8: "framer-v-l4htmj" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const QOqPfDD7W = undefined;
const SteQqNES0 = undefined;
const s_nDL4Vz7 = undefined;
const bOS4a1p0y = undefined;
const orNDvlMPt = undefined;
const W4O41DuMl = undefined;
const RETD21XoI = undefined;
const hMlkc5dQx = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const isSet = (value) => {
  if (Array.isArray(value)) return value.length > 0;
  return value !== undefined && value !== null && value !== "";
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
  cellsRow,
  height,
  hideCursor,
  id,
  image,
  instagramLink,
  linkedInLink,
  name1,
  role,
  width,
  xLink,
  ...props
}) => {
  return {
    ...props,
    bOS4a1p0y: name1 ?? props.bOS4a1p0y ?? "Name",
    hMlkc5dQx: instagramLink ?? props.hMlkc5dQx,
    orNDvlMPt: hideCursor ?? props.orNDvlMPt,
    QOqPfDD7W: image ??
      props.QOqPfDD7W ?? {
        pixelHeight: 1e3,
        pixelWidth: 1e3,
        src: "https://framerusercontent.com/images/22MQIF3epWgNnOHjtamot0mvL0.jpg?width=1000&height=1000",
        srcSet:
          "https://framerusercontent.com/images/22MQIF3epWgNnOHjtamot0mvL0.jpg?scale-down-to=512&width=1000&height=1000 512w,https://framerusercontent.com/images/22MQIF3epWgNnOHjtamot0mvL0.jpg?width=1000&height=1000 1000w",
      },
    RETD21XoI: xLink ?? props.RETD21XoI,
    s_nDL4Vz7: role ?? props.s_nDL4Vz7 ?? "Role",
    SteQqNES0: cellsRow ?? props.SteQqNES0 ?? 8,
    W4O41DuMl: linkedInLink ?? props.W4O41DuMl,
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    bOS4a1p0y,
    s_nDL4Vz7,
    QOqPfDD7W,
    W4O41DuMl,
    RETD21XoI,
    hMlkc5dQx,
    SteQqNES0,
    orNDvlMPt,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "Dbatgq_R8",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [
    sharedStyle.className,
    sharedStyle1.className,
    sharedStyle2.className,
  ];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const visible = isSet(W4O41DuMl);
  const visible1 = isSet(RETD21XoI);
  const visible2 = isSet(hMlkc5dQx);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-l4htmj",
            className,
            classNames
          ),
          "data-framer-name": "Variant 1",
          layoutDependency: layoutDependency,
          layoutId: "Dbatgq_R8",
          ref: refBinding,
          style: { ...style },
          children: [
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-b9pzo9-container",
                "data-code-component-plugin-id": "84d4c1",
                isAuthoredByUser: true,
                isModuleExternal: true,
                layoutDependency: layoutDependency,
                layoutId: "bQJI56muY-container",
                nodeId: "bQJI56muY",
                rendersWithMotion: true,
                scopeId: "cvb4XPm8F",
                children: /*#__PURE__*/ _jsx(PixelRevealOnAppear, {
                  appearOnce: false,
                  appearThreshold: 0.2,
                  cellsPerRow: SteQqNES0,
                  fillColor:
                    "var(--token-280bd9a0-bf37-41b4-a3c3-9a122b679a65, rgb(255, 255, 255))",
                  height: "100%",
                  id: "bQJI56muY",
                  image: toResponsiveImage(QOqPfDD7W),
                  layoutId: "bQJI56muY",
                  mediaType: "image",
                  pixelReveal: true,
                  resetOnExit: false,
                  revealDuration: 0.8,
                  reverse: false,
                  style: { width: "100%" },
                  transitionLength: 1,
                  width: "100%",
                }),
              }),
            }),
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-1yer2nk",
              "data-framer-name": "Info",
              layoutDependency: layoutDependency,
              layoutId: "f4tzN07zG",
              children: [
                /*#__PURE__*/ _jsxs(motion.div, {
                  className: "framer-4sz62f",
                  "data-framer-name": "Name and Role",
                  layoutDependency: layoutDependency,
                  layoutId: "fKfb1rvYK",
                  children: [
                    /*#__PURE__*/ _jsx(RichText, {
                      __fromCanvasComponent: true,
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                          className: "framer-styles-preset-1rymzzk",
                          "data-styles-preset": "mMKAraaKM",
                          dir: "auto",
                          children: "Role",
                        }),
                      }),
                      className: "framer-4bvni3",
                      fonts: ["Inter"],
                      layoutDependency: layoutDependency,
                      layoutId: "C8ANibLna",
                      style: {
                        "--framer-link-text-color": "rgb(0, 153, 255)",
                        "--framer-link-text-decoration": "underline",
                      },
                      text: s_nDL4Vz7,
                      verticalAlignment: "top",
                      withExternalLayout: true,
                    }),
                    /*#__PURE__*/ _jsx(RichText, {
                      __fromCanvasComponent: true,
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.h4, {
                          className: "framer-styles-preset-kb09o",
                          "data-styles-preset": "i3WCJXRxw",
                          dir: "auto",
                          children: "Name",
                        }),
                      }),
                      className: "framer-3e1dwu",
                      fonts: ["Inter"],
                      layoutDependency: layoutDependency,
                      layoutId: "GW2W73Pmq",
                      style: {
                        "--framer-link-text-color": "rgb(0, 153, 255)",
                        "--framer-link-text-decoration": "underline",
                      },
                      text: bOS4a1p0y,
                      verticalAlignment: "top",
                      withExternalLayout: true,
                    }),
                  ],
                }),
                /*#__PURE__*/ _jsxs(motion.div, {
                  className: "framer-13wex88",
                  "data-framer-cursor": orNDvlMPt,
                  "data-framer-name": "Links",
                  layoutDependency: layoutDependency,
                  layoutId: "mxlXpGR_M",
                  children: [
                    visible !== false &&
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            className: "framer-styles-preset-1rymzzk",
                            "data-styles-preset": "mMKAraaKM",
                            dir: "auto",
                            children: /*#__PURE__*/ _jsx(Link, {
                              href: W4O41DuMl,
                              motionChild: true,
                              nodeId: "ImEwI2rdd",
                              openInNewTab: true,
                              relValues: [],
                              scopeId: "cvb4XPm8F",
                              smoothScroll: false,
                              children: /*#__PURE__*/ _jsx(motion.a, {
                                className: "framer-styles-preset-17pmv6x",
                                "data-styles-preset": "qxloupasW",
                                children: "LI",
                              }),
                            }),
                          }),
                        }),
                        className: "framer-x989zq",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "ImEwI2rdd",
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }),
                    visible1 !== false &&
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            className: "framer-styles-preset-1rymzzk",
                            "data-styles-preset": "mMKAraaKM",
                            dir: "auto",
                            children: /*#__PURE__*/ _jsx(Link, {
                              href: RETD21XoI,
                              motionChild: true,
                              nodeId: "Ui7AESwfh",
                              openInNewTab: true,
                              relValues: [],
                              scopeId: "cvb4XPm8F",
                              smoothScroll: false,
                              children: /*#__PURE__*/ _jsx(motion.a, {
                                className: "framer-styles-preset-17pmv6x",
                                "data-styles-preset": "qxloupasW",
                                children: "X",
                              }),
                            }),
                          }),
                        }),
                        className: "framer-1nsc094",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "Ui7AESwfh",
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }),
                    visible2 !== false &&
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            className: "framer-styles-preset-1rymzzk",
                            "data-styles-preset": "mMKAraaKM",
                            dir: "auto",
                            children: /*#__PURE__*/ _jsx(Link, {
                              href: hMlkc5dQx,
                              motionChild: true,
                              nodeId: "WoGAozG1R",
                              openInNewTab: true,
                              relValues: [],
                              scopeId: "cvb4XPm8F",
                              smoothScroll: false,
                              children: /*#__PURE__*/ _jsx(motion.a, {
                                className: "framer-styles-preset-17pmv6x",
                                "data-styles-preset": "qxloupasW",
                                children: "Ig",
                              }),
                            }),
                          }),
                        }),
                        className: "framer-1hatccm",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "WoGAozG1R",
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }),
                  ],
                }),
              ],
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-xKLZq.framer-uqebdv, .framer-xKLZq .framer-uqebdv { display: block; }",
  ".framer-xKLZq.framer-l4htmj { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 290px; }",
  ".framer-xKLZq .framer-b9pzo9-container { flex: none; height: auto; position: relative; width: 100%; z-index: 1; }",
  ".framer-xKLZq .framer-1yer2nk { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-xKLZq .framer-4sz62f { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-xKLZq .framer-4bvni3, .framer-xKLZq .framer-3e1dwu { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-xKLZq .framer-13wex88 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-xKLZq .framer-x989zq, .framer-xKLZq .framer-1nsc094, .framer-xKLZq .framer-1hatccm { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  ...sharedStyle2.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 399
 * @framerIntrinsicWidth 290
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}
 * @framerVariables {"bOS4a1p0y":"name1","s_nDL4Vz7":"role","QOqPfDD7W":"image","W4O41DuMl":"linkedInLink","RETD21XoI":"xLink","hMlkc5dQx":"instagramLink","SteQqNES0":"cellsRow","orNDvlMPt":"hideCursor"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const Framercvb4XPm8F = withCSS(Component, css, "framer-xKLZq");
export default Framercvb4XPm8F;
Framercvb4XPm8F.displayName = "Team Card";
Framercvb4XPm8F.defaultProps = { height: 399, width: 290 };
addPropertyControls(Framercvb4XPm8F, {
  bOS4a1p0y: {
    defaultValue: "Name",
    displayTextArea: false,
    title: "Name",
    type: ControlType.String,
  },
  onbOS4a1p0yChange: { changes: "bOS4a1p0y", type: ControlType.ChangeHandler },
  s_nDL4Vz7: {
    defaultValue: "Role",
    displayTextArea: false,
    title: "Role",
    type: ControlType.String,
  },
  ons_nDL4Vz7Change: { changes: "s_nDL4Vz7", type: ControlType.ChangeHandler },
  QOqPfDD7W: {
    __defaultAssetReference:
      "data:framer/asset-reference,22MQIF3epWgNnOHjtamot0mvL0.jpg?originalFilename=image_placeholder.jpg&width=1000&height=1000",
    title: "Image",
    type: ControlType.ResponsiveImage,
  },
  W4O41DuMl: { title: "LinkedIn Link", type: ControlType.Link },
  RETD21XoI: { title: "X Link", type: ControlType.Link },
  hMlkc5dQx: { title: "Instagram Link", type: ControlType.Link },
  SteQqNES0: {
    defaultValue: 8,
    max: 40,
    min: 1,
    step: 1,
    title: "Cells Row",
    type: ControlType.Number,
  },
  onSteQqNES0Change: { changes: "SteQqNES0", type: ControlType.ChangeHandler },
  orNDvlMPt: { title: "Hide Cursor", type: ControlType.CustomCursor },
});
addFonts(
  Framercvb4XPm8F,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...PixelRevealOnAppearFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
    ...getFontsFromSharedStyle(sharedStyle2.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "Framercvb4XPm8F",
      slots: [],
      annotations: {
        framerImmutableVariables: "true",
        framerIntrinsicWidth: "290",
        framerAutoSizeImages: "true",
        framerDisplayContentsDiv: "false",
        framerIntrinsicHeight: "399",
        framerComponentViewportWidth: "true",
        framerVariables:
          '{"bOS4a1p0y":"name1","s_nDL4Vz7":"role","QOqPfDD7W":"image","W4O41DuMl":"linkedInLink","RETD21XoI":"xLink","hMlkc5dQx":"instagramLink","SteQqNES0":"cellsRow","orNDvlMPt":"hideCursor"}',
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}',
        framerColorSyntax: "true",
        framerContractVersion: "1",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./cvb4XPm8F.map
