// Generated by Framer (600e657)
import { fontStore } from "framer";
fontStore.loadFonts([]);
export const fonts = [{ explicitInter: true, fonts: [] }];
export const css = [
  ".framer-cMIBn .framer-styles-preset-17pmv6x:not(.rich-text-wrapper), .framer-cMIBn .framer-styles-preset-17pmv6x.rich-text-wrapper a { --framer-link-hover-text-decoration: none; --framer-link-text-decoration: underline; --framer-link-text-decoration-offset: 2px; }",
];
export const className = "framer-cMIBn";
export const __FramerMetadata__ = {
  exports: {
    className: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    css: { type: "variable", annotations: { framerContractVersion: "1" } },
    fonts: { type: "variable", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
