// Generated by Framer (7bfce40)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getLoadingLazyAtYPosition,
  Image as Image1,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const cycleOrder = ["Kwq6eWlOf", "rxEmfrTPu"];
const serializationHash = "framer-D0acp";
const variantClassNames = {
  Kwq6eWlOf: "framer-v-19e8fz4",
  rxEmfrTPu: "framer-v-8v8b4f",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const nOX820OBO = undefined;
const transition1 = { bounce: 0, delay: 0.1, duration: 0.8, type: "spring" };
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  "Variant 1": "Kwq6eWlOf",
  "Variant 2": "rxEmfrTPu",
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, image, width, ...props }) => {
  return {
    ...props,
    nOX820OBO: image ??
      props.nOX820OBO ?? {
        pixelHeight: 930,
        pixelWidth: 684,
        src: "https://framerusercontent.com/images/GArePE65xkIVpUNPf1rHwQPthQ.jpg?width=684&height=930",
        srcSet:
          "https://framerusercontent.com/images/GArePE65xkIVpUNPf1rHwQPthQ.jpg?width=684&height=930 684w",
      },
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "Kwq6eWlOf",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, nOX820OBO, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "Kwq6eWlOf",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-19e8fz4",
            className,
            classNames
          ),
          "data-framer-name": "Variant 1",
          layoutDependency: layoutDependency,
          layoutId: "Kwq6eWlOf",
          ref: refBinding,
          style: {
            mask: "linear-gradient(0deg, rgba(0,0,0,0) 100%, rgba(0,0,0,1) 100%) add",
            WebkitMask:
              "linear-gradient(0deg, rgba(0,0,0,0) 100%, rgba(0,0,0,1) 100%) add",
            ...style,
          },
          variants: {
            rxEmfrTPu: {
              mask: "linear-gradient(0deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 0%) add",
              WebkitMask:
                "linear-gradient(0deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 0%) add",
            },
          },
          ...addPropertyOverrides(
            { rxEmfrTPu: { "data-framer-name": "Variant 2" } },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsx(Image1, {
            background: {
              alt: "",
              fit: "fill",
              loading: getLoadingLazyAtYPosition(
                (componentViewport?.y || 0) +
                  ((componentViewport?.height || 300) * 0.5000000000000002 -
                    (((componentViewport?.height || 300) - 0) * 1) / 2)
              ),
              pixelHeight: 930,
              pixelWidth: 684,
              sizes: componentViewport?.width || "100vw",
              ...toResponsiveImage(nOX820OBO),
            },
            className: "framer-mpgdnx",
            layoutDependency: layoutDependency,
            layoutId: "Grk_JlbH9",
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-D0acp.framer-1j7qfas, .framer-D0acp .framer-1j7qfas { display: block; }",
  ".framer-D0acp.framer-19e8fz4 { height: 300px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 300px; }",
  ".framer-D0acp .framer-mpgdnx { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 300
 * @framerIntrinsicWidth 300
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"rxEmfrTPu":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"nOX820OBO":"image"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerPdKxBS9Yi = withCSS(Component, css, "framer-D0acp");
export default FramerPdKxBS9Yi;
FramerPdKxBS9Yi.displayName = "Image Reveal";
FramerPdKxBS9Yi.defaultProps = { height: 300, width: 300 };
addPropertyControls(FramerPdKxBS9Yi, {
  variant: {
    options: ["Kwq6eWlOf", "rxEmfrTPu"],
    optionTitles: ["Variant 1", "Variant 2"],
    title: "Variant",
    type: ControlType.Enum,
  },
  nOX820OBO: {
    __defaultAssetReference:
      "data:framer/asset-reference,GArePE65xkIVpUNPf1rHwQPthQ.jpg?originalFilename=2.jpg&width=684&height=930",
    title: "Image",
    type: ControlType.ResponsiveImage,
  },
});
addFonts(FramerPdKxBS9Yi, [{ explicitInter: true, fonts: [] }], {
  supportsExplicitInterCodegen: true,
});
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerPdKxBS9Yi",
      slots: [],
      annotations: {
        framerAutoSizeImages: "true",
        framerContractVersion: "1",
        framerVariables: '{"nOX820OBO":"image"}',
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"rxEmfrTPu":{"layout":["fixed","fixed"]}}}',
        framerImmutableVariables: "true",
        framerColorSyntax: "true",
        framerComponentViewportWidth: "true",
        framerIntrinsicWidth: "300",
        framerIntrinsicHeight: "300",
        framerDisplayContentsDiv: "false",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./PdKxBS9Yi.map
