// Generated by Framer (841fdc4)
import { fontStore } from "framer";
fontStore.loadFonts(["FS;Bebas Neue-regular"]);
export const fonts = [
  {
    explicitInter: true,
    fonts: [
      {
        cssFamilyName: "Bebas Neue",
        source: "fontshare",
        style: "normal",
        uiFamilyName: "Bebas Neue",
        url: "https://framerusercontent.com/third-party-assets/fontshare/wf/AWXLDXTI2CYJ5SHK74YUPGPFS5S5BWLL/M6ZJD4UOFNT4DPUXGTK7T46JZ3W3QW64/2TXZKBJMJVP3NQX7K7MGJDQFMD4ZMJR7.woff2",
        weight: "400",
      },
    ],
  },
];
export const css = [
  '.framer-VcHJa .framer-styles-preset-kb09o:not(.rich-text-wrapper), .framer-VcHJa .framer-styles-preset-kb09o.rich-text-wrapper h4 { --framer-font-family: "Bebas Neue", "Bebas Neue Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 30px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-letter-spacing: -0.01em; --framer-line-height: 120%; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
  '@media (max-width: 1599px) and (min-width: 0px) { .framer-VcHJa .framer-styles-preset-kb09o:not(.rich-text-wrapper), .framer-VcHJa .framer-styles-preset-kb09o.rich-text-wrapper h4 { --framer-font-family: "Bebas Neue", "Bebas Neue Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 26px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-letter-spacing: -0.01em; --framer-line-height: 120%; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
export const className = "framer-VcHJa";
export const __FramerMetadata__ = {
  exports: {
    className: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    css: { type: "variable", annotations: { framerContractVersion: "1" } },
    fonts: { type: "variable", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
