// Generated by Framer (e0e363b)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  forwardLoader,
  getFonts,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCodeBoundaryForOverrides,
  withCSS,
  withMappedReactProps,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import { withAccordion } from "https://framerusercontent.com/modules/w3qwoinWQHkX9TUd5499/DomhhXtHKn9gsPXPeu2u/WithExclusiveOpenState.js";
import ServiceItem, * as ServiceItemInfo from "https://framerusercontent.com/modules/kwq6OEwpaJ1LbSovC0tq/4S4w2KMLSj2o08gIvnZ1/XFGBi0GWJ.js";
const ServiceItemFonts = getFonts(ServiceItem);
const ServiceItemWithAccordion1tictylWithMappedReactPropsc2fyaj =
  withMappedReactProps(
    withCodeBoundaryForOverrides(ServiceItem, {
      nodeId: "hW1vKokF4",
      override: withAccordion,
      scopeId: "bbuFLz152",
    }),
    ServiceItemInfo
  );
const ServiceItemWithAccordion64aandWithMappedReactPropsc2fyaj =
  withMappedReactProps(
    withCodeBoundaryForOverrides(ServiceItem, {
      nodeId: "KQEG0GBOP",
      override: withAccordion,
      scopeId: "bbuFLz152",
    }),
    ServiceItemInfo
  );
const ServiceItemWithAccordion9gbeoxWithMappedReactPropsc2fyaj =
  withMappedReactProps(
    withCodeBoundaryForOverrides(ServiceItem, {
      nodeId: "wvHRMRkIY",
      override: withAccordion,
      scopeId: "bbuFLz152",
    }),
    ServiceItemInfo
  );
const ServiceItemWithAccordion1ol54j8WithMappedReactPropsc2fyaj =
  withMappedReactProps(
    withCodeBoundaryForOverrides(ServiceItem, {
      nodeId: "oBOogUFt8",
      override: withAccordion,
      scopeId: "bbuFLz152",
    }),
    ServiceItemInfo
  );
const cycleOrder = ["wRcHJFAqR", "WjWSCzSHH", "cqzn6zkeL"];
const serializationHash = "framer-GTvTv";
const variantClassNames = {
  cqzn6zkeL: "framer-v-bixv9y",
  WjWSCzSHH: "framer-v-zvy0eg",
  wRcHJFAqR: "framer-v-niak4a",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const ojSONopV0 = undefined;
const transition1 = { bounce: 0, delay: 0, duration: 0.6, type: "spring" };
const addImageAlt = (image, alt) => {
  if (!image || typeof image !== "object") {
    return;
  }
  return { ...image, alt };
};
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  Desktop: "wRcHJFAqR",
  Mobile: "cqzn6zkeL",
  Tablet: "WjWSCzSHH",
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, hideCursor, id, width, ...props }) => {
  return {
    ...props,
    ojSONopV0: hideCursor ?? props.ojSONopV0,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "wRcHJFAqR",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ojSONopV0, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "wRcHJFAqR",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-niak4a",
            className,
            classNames
          ),
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "wRcHJFAqR",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            {
              cqzn6zkeL: { "data-framer-name": "Mobile" },
              WjWSCzSHH: { "data-framer-name": "Tablet" },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 542,
              width: componentViewport?.width || "100vw",
              y:
                (componentViewport?.y || 0) +
                0 +
                (((componentViewport?.height || 1060) - 0 - 2168) / 2 + 0 + 0),
              ...addPropertyOverrides(
                {
                  cqzn6zkeL: {
                    y:
                      (componentViewport?.y || 0) +
                      0 +
                      (((componentViewport?.height || 2194.5) - 0 - 2228) / 2 +
                        0 +
                        0),
                  },
                  WjWSCzSHH: {
                    y:
                      (componentViewport?.y || 0) +
                      0 +
                      (((componentViewport?.height || 1712.5) - 0 - 2258) / 2 +
                        0 +
                        0),
                  },
                },
                baseVariant,
                gestureVariant
              ),
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-1tictyl-container",
                layoutDependency: layoutDependency,
                layoutId: "hW1vKokF4-container",
                nodeId: "hW1vKokF4",
                rendersWithMotion: true,
                scopeId: "bbuFLz152",
                children: /*#__PURE__*/ _jsx(
                  ServiceItemWithAccordion1tictylWithMappedReactPropsc2fyaj,
                  {
                    height: "100%",
                    id: "hW1vKokF4",
                    ivmchSjVy: addImageAlt(
                      {
                        pixelHeight: 1e3,
                        pixelWidth: 1783,
                        src: "https://framerusercontent.com/images/ZSJDDgWANPxNXwtfeXT7s3gc.jpg?width=1783&height=1000",
                        srcSet:
                          "https://framerusercontent.com/images/ZSJDDgWANPxNXwtfeXT7s3gc.jpg?scale-down-to=512&width=1783&height=1000 512w,https://framerusercontent.com/images/ZSJDDgWANPxNXwtfeXT7s3gc.jpg?scale-down-to=1024&width=1783&height=1000 1024w,https://framerusercontent.com/images/ZSJDDgWANPxNXwtfeXT7s3gc.jpg?width=1783&height=1000 1783w",
                      },
                      ""
                    ),
                    layoutId: "hW1vKokF4",
                    pFHMMwpKR: ojSONopV0,
                    pyALyOV5H: "Creative Direction",
                    qPoXD8dE0: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsxs("p", {
                        dir: "auto",
                        children: [
                          "We shape the visual direction behind campaigns, launches, identities, and digital work. ",
                          /*#__PURE__*/ _jsx("strong", {
                            children:
                              "From mood and tone to image language and overall feel",
                          }),
                          ", we help define what the project should become before the details take\xa0over.",
                        ],
                      }),
                    }),
                    style: { width: "100%" },
                    variant: matchVariant("eyoun1pOe"),
                    width: "100%",
                    ...addPropertyOverrides(
                      {
                        cqzn6zkeL: { variant: matchVariant("uuqzm7GA8") },
                        WjWSCzSHH: { variant: matchVariant("JUT8KXqta") },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }
                ),
              }),
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 542,
              width: componentViewport?.width || "100vw",
              y:
                (componentViewport?.y || 0) +
                0 +
                (((componentViewport?.height || 1060) - 0 - 2168) / 2 +
                  542 +
                  0),
              ...addPropertyOverrides(
                {
                  cqzn6zkeL: {
                    y:
                      (componentViewport?.y || 0) +
                      0 +
                      (((componentViewport?.height || 2194.5) - 0 - 2228) / 2 +
                        542 +
                        20),
                  },
                  WjWSCzSHH: {
                    y:
                      (componentViewport?.y || 0) +
                      0 +
                      (((componentViewport?.height || 1712.5) - 0 - 2258) / 2 +
                        542 +
                        30),
                  },
                },
                baseVariant,
                gestureVariant
              ),
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-64aand-container",
                layoutDependency: layoutDependency,
                layoutId: "KQEG0GBOP-container",
                nodeId: "KQEG0GBOP",
                rendersWithMotion: true,
                scopeId: "bbuFLz152",
                children: /*#__PURE__*/ _jsx(
                  ServiceItemWithAccordion64aandWithMappedReactPropsc2fyaj,
                  {
                    height: "100%",
                    id: "KQEG0GBOP",
                    ivmchSjVy: addImageAlt(
                      {
                        pixelHeight: 1346,
                        pixelWidth: 2400,
                        src: "https://framerusercontent.com/images/tYaiGczdETtWXnRbh3EJu8ZoY.jpg?width=2400&height=1346",
                        srcSet:
                          "https://framerusercontent.com/images/tYaiGczdETtWXnRbh3EJu8ZoY.jpg?scale-down-to=512&width=2400&height=1346 512w,https://framerusercontent.com/images/tYaiGczdETtWXnRbh3EJu8ZoY.jpg?scale-down-to=1024&width=2400&height=1346 1024w,https://framerusercontent.com/images/tYaiGczdETtWXnRbh3EJu8ZoY.jpg?scale-down-to=2048&width=2400&height=1346 2048w,https://framerusercontent.com/images/tYaiGczdETtWXnRbh3EJu8ZoY.jpg?width=2400&height=1346 2400w",
                      },
                      ""
                    ),
                    layoutId: "KQEG0GBOP",
                    pFHMMwpKR: ojSONopV0,
                    pyALyOV5H: "Campaign Design",
                    qPoXD8dE0: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsxs("p", {
                        dir: "auto",
                        children: [
                          "We create campaign systems for launches, drops, announcements, and brand moments. ",
                          /*#__PURE__*/ _jsx("strong", {
                            children:
                              "The goal is to make every asset feel sharp, recognizable, and strong",
                          }),
                          " enough to work across multiple\xa0touchpoints.",
                        ],
                      }),
                    }),
                    style: { width: "100%" },
                    variant: matchVariant("fHqEeJ78A"),
                    width: "100%",
                    ...addPropertyOverrides(
                      {
                        cqzn6zkeL: { variant: matchVariant("uuqzm7GA8") },
                        WjWSCzSHH: { variant: matchVariant("JUT8KXqta") },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }
                ),
              }),
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 542,
              width: componentViewport?.width || "100vw",
              y:
                (componentViewport?.y || 0) +
                0 +
                (((componentViewport?.height || 1060) - 0 - 2168) / 2 +
                  1084 +
                  0),
              ...addPropertyOverrides(
                {
                  cqzn6zkeL: {
                    y:
                      (componentViewport?.y || 0) +
                      0 +
                      (((componentViewport?.height || 2194.5) - 0 - 2228) / 2 +
                        1084 +
                        40),
                  },
                  WjWSCzSHH: {
                    y:
                      (componentViewport?.y || 0) +
                      0 +
                      (((componentViewport?.height || 1712.5) - 0 - 2258) / 2 +
                        1084 +
                        60),
                  },
                },
                baseVariant,
                gestureVariant
              ),
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-9gbeox-container",
                layoutDependency: layoutDependency,
                layoutId: "wvHRMRkIY-container",
                nodeId: "wvHRMRkIY",
                rendersWithMotion: true,
                scopeId: "bbuFLz152",
                children: /*#__PURE__*/ _jsx(
                  ServiceItemWithAccordion9gbeoxWithMappedReactPropsc2fyaj,
                  {
                    height: "100%",
                    id: "wvHRMRkIY",
                    ivmchSjVy: addImageAlt(
                      {
                        pixelHeight: 1e3,
                        pixelWidth: 1805,
                        src: "https://framerusercontent.com/images/urCLr50fjKCkEy5wuFQIRUY8k.jpg?width=1805&height=1000",
                        srcSet:
                          "https://framerusercontent.com/images/urCLr50fjKCkEy5wuFQIRUY8k.jpg?scale-down-to=512&width=1805&height=1000 512w,https://framerusercontent.com/images/urCLr50fjKCkEy5wuFQIRUY8k.jpg?scale-down-to=1024&width=1805&height=1000 1024w,https://framerusercontent.com/images/urCLr50fjKCkEy5wuFQIRUY8k.jpg?width=1805&height=1000 1805w",
                      },
                      ""
                    ),
                    layoutId: "wvHRMRkIY",
                    pFHMMwpKR: ojSONopV0,
                    pyALyOV5H: "Art Direction",
                    qPoXD8dE0: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsxs("p", {
                        dir: "auto",
                        children: [
                          "We build the look, rhythm, and atmosphere of the work. This\xa0includes references, image direction, layout logic, visual rules, and the ",
                          /*#__PURE__*/ _jsx("strong", {
                            children:
                              "creative decisions that make everything feel\xa0connected.",
                          }),
                        ],
                      }),
                    }),
                    style: { width: "100%" },
                    variant: matchVariant("eyoun1pOe"),
                    width: "100%",
                    ...addPropertyOverrides(
                      {
                        cqzn6zkeL: { variant: matchVariant("uuqzm7GA8") },
                        WjWSCzSHH: { variant: matchVariant("JUT8KXqta") },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }
                ),
              }),
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 542,
              width: componentViewport?.width || "100vw",
              y:
                (componentViewport?.y || 0) +
                0 +
                (((componentViewport?.height || 1060) - 0 - 2168) / 2 +
                  1626 +
                  0),
              ...addPropertyOverrides(
                {
                  cqzn6zkeL: {
                    y:
                      (componentViewport?.y || 0) +
                      0 +
                      (((componentViewport?.height || 2194.5) - 0 - 2228) / 2 +
                        1626 +
                        60),
                  },
                  WjWSCzSHH: {
                    y:
                      (componentViewport?.y || 0) +
                      0 +
                      (((componentViewport?.height || 1712.5) - 0 - 2258) / 2 +
                        1626 +
                        90),
                  },
                },
                baseVariant,
                gestureVariant
              ),
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-1ol54j8-container",
                layoutDependency: layoutDependency,
                layoutId: "oBOogUFt8-container",
                nodeId: "oBOogUFt8",
                rendersWithMotion: true,
                scopeId: "bbuFLz152",
                children: /*#__PURE__*/ _jsx(
                  ServiceItemWithAccordion1ol54j8WithMappedReactPropsc2fyaj,
                  {
                    height: "100%",
                    id: "oBOogUFt8",
                    ivmchSjVy: addImageAlt(
                      {
                        pixelHeight: 1e3,
                        pixelWidth: 1783,
                        src: "https://framerusercontent.com/images/Ou49khYJg5Vvn65oBvSUv5KExkM.jpg?width=1783&height=1000",
                        srcSet:
                          "https://framerusercontent.com/images/Ou49khYJg5Vvn65oBvSUv5KExkM.jpg?scale-down-to=512&width=1783&height=1000 512w,https://framerusercontent.com/images/Ou49khYJg5Vvn65oBvSUv5KExkM.jpg?scale-down-to=1024&width=1783&height=1000 1024w,https://framerusercontent.com/images/Ou49khYJg5Vvn65oBvSUv5KExkM.jpg?width=1783&height=1000 1783w",
                      },
                      ""
                    ),
                    layoutId: "oBOogUFt8",
                    pFHMMwpKR: ojSONopV0,
                    pyALyOV5H: "Digital Experience",
                    qPoXD8dE0: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsxs("p", {
                        dir: "auto",
                        children: [
                          "We design websites and ",
                          /*#__PURE__*/ _jsx("strong", {
                            children:
                              "digital spaces that give the work a stronger stage.",
                          }),
                          " Clear structure, visual rhythm, sharp presentation, and a better way to turn attention into\xa0action.",
                        ],
                      }),
                    }),
                    style: { width: "100%" },
                    variant: matchVariant("eyoun1pOe"),
                    width: "100%",
                    ...addPropertyOverrides(
                      {
                        cqzn6zkeL: { variant: matchVariant("uuqzm7GA8") },
                        WjWSCzSHH: { variant: matchVariant("JUT8KXqta") },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }
                ),
              }),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-GTvTv.framer-lgs3ib, .framer-GTvTv .framer-lgs3ib { display: block; }",
  ".framer-GTvTv.framer-niak4a { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 773px; }",
  ".framer-GTvTv .framer-1tictyl-container, .framer-GTvTv .framer-64aand-container, .framer-GTvTv .framer-9gbeox-container, .framer-GTvTv .framer-1ol54j8-container { flex: none; height: auto; position: relative; width: 100%; }",
  ".framer-GTvTv.framer-v-zvy0eg.framer-niak4a { gap: 30px; width: 640px; }",
  ".framer-GTvTv.framer-v-bixv9y.framer-niak4a { gap: 20px; width: 390px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 1060
 * @framerIntrinsicWidth 773
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"WjWSCzSHH":{"layout":["fixed","auto"]},"cqzn6zkeL":{"layout":["fixed","auto"]}}}
 * @framerVariables {"ojSONopV0":"hideCursor"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerbbuFLz152 = withCSS(Component, css, "framer-GTvTv");
export default FramerbbuFLz152;
FramerbbuFLz152.displayName = "Services";
FramerbbuFLz152.defaultProps = { height: 1060, width: 773 };
addPropertyControls(FramerbbuFLz152, {
  variant: {
    options: ["wRcHJFAqR", "WjWSCzSHH", "cqzn6zkeL"],
    optionTitles: ["Desktop", "Tablet", "Mobile"],
    title: "Variant",
    type: ControlType.Enum,
  },
  ojSONopV0: { title: "Hide Cursor", type: ControlType.CustomCursor },
});
addFonts(
  FramerbbuFLz152,
  [{ explicitInter: true, fonts: [] }, ...ServiceItemFonts],
  { supportsExplicitInterCodegen: true }
);
FramerbbuFLz152.loader = {
  load: (props, context) => {
    const locale = context.locale;
    return Promise.allSettled([forwardLoader(ServiceItem, {}, context)]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerbbuFLz152",
      slots: [],
      annotations: {
        framerVariables: '{"ojSONopV0":"hideCursor"}',
        framerColorSyntax: "true",
        framerComponentViewportWidth: "true",
        framerIntrinsicHeight: "1060",
        framerDisplayContentsDiv: "false",
        framerImmutableVariables: "true",
        framerAutoSizeImages: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"WjWSCzSHH":{"layout":["fixed","auto"]},"cqzn6zkeL":{"layout":["fixed","auto"]}}}',
        framerIntrinsicWidth: "773",
        framerContractVersion: "1",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./bbuFLz152.map
