// Generated by Framer (a7e392f)
import { jsx as _jsx } from "react/jsx-runtime";
import { cx, motion, withCSS } from "framer";
import * as React from "react";
import { forwardRef } from "react";
const mask =
  'url(\'data:image/svg+xml,<svg display="block" id="1447514560" role="presentation" viewBox="0 0 78 28" xmlns="http://www.w3.org/2000/svg"><path d="M 8.524 27.495 C 6.221 27.404 4.338 26.775 2.865 25.606 C 2.584 25.383 1.914 24.713 1.689 24.431 C 1.092 23.681 0.686 22.951 0.415 22.141 C -0.419 19.647 0.01 16.375 1.642 12.785 C 3.039 9.71 5.194 6.661 8.954 2.439 C 9.508 1.817 11.158 0 11.169 0 C 11.172 0 11.083 0.156 10.969 0.345 C 9.992 1.981 9.155 3.907 8.699 5.575 C 7.967 8.252 8.056 10.549 8.958 12.33 C 9.581 13.557 10.648 14.62 11.848 15.207 C 13.949 16.235 17.025 16.32 20.781 15.456 C 21.04 15.396 33.856 11.998 49.261 7.905 C 64.666 3.811 77.272 0.465 77.274 0.467 C 77.278 0.471 41.484 15.769 22.902 23.706 C 19.959 24.962 19.172 25.28 17.789 25.765 C 14.252 27.005 11.085 27.597 8.524 27.495 Z" fill="var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, rgb(0, 0, 0))" height="27.506482836452694px" id="FV2wvlmOg" transform="translate(0 0)" width="77.27420021571311px"/></svg>\') alpha no-repeat center / auto var(--framer-icon-mask-mode, add), var(--framer-icon-mask, none)';
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
  const { animated, layoutId, children, ...rest } = props;
  return animated
    ? /*#__PURE__*/ _jsx(motion.div, { ...rest, layoutId: layoutId, ref: ref })
    : /*#__PURE__*/ _jsx("div", { ...rest, ref: ref });
});
const getProps = ({ height, id, width, ...props }) => {
  return { ...props };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  return /*#__PURE__*/ _jsx(SVG, {
    ...restProps,
    className: cx("framer-1N9Yi", className),
    layoutId: layoutId,
    ref: ref,
    style: { ...style },
  });
});
const css = [
  `.framer-1N9Yi { -webkit-mask: ${mask}; aspect-ratio: 2.7857142857142856; background-color: var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, #000000); mask: ${mask}; width: 78px; }`,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 78
 * @framerIntrinsicHeight 28
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerImmutableVariables true
 * @framerVector {"name":"Nike","color":{"type":"static","value":"var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, rgb(0, 0, 0))"},"set":{"localId":"vectorSet/wNFSNYcoU","id":"wNFSNYcoU","moduleId":"h2k2A7Qrkj0oawcG2kgF"}}
 */ const Icon = withCSS(Component, css, "framer-1N9Yi");
Icon.displayName = "Nike";
export default Icon;
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Icon",
      slots: [],
      annotations: {
        framerVector:
          '{"name":"Nike","color":{"type":"static","value":"var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, rgb(0, 0, 0))"},"set":{"localId":"vectorSet/wNFSNYcoU","id":"wNFSNYcoU","moduleId":"h2k2A7Qrkj0oawcG2kgF"}}',
        framerIntrinsicHeight: "28",
        framerSupportedLayoutWidth: "any-prefer-fixed",
        framerSupportedLayoutHeight: "any-prefer-fixed",
        framerIntrinsicWidth: "78",
        framerImmutableVariables: "true",
        framerContractVersion: "1",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
