// Generated by Framer (43e8337)
import {
  addPropertyControls as e,
  ControlType as t,
  QueryEngine as l,
} from "framer";
import {
  DatabaseCollection as a,
  DatabaseDictionaryIndex as r,
} from "./TBKkMyqX4-0.js";
import { getRichTextJsonResolver as i } from "./TBKkMyqX4-1.js";
let o = {
    createdAt: { isNullable: !0, type: t.Date },
    GI_O5iwL7: { isNullable: !0, type: t.String },
    HlnUrNzwa: { isNullable: !0, type: t.RichText },
    id: { isNullable: !1, type: t.String },
    iVONskd1W: { isNullable: !0, type: t.String },
    lIk7B09Bk: { isNullable: !0, type: t.String },
    nextItemId: { isNullable: !0, type: t.String },
    previousItemId: { isNullable: !0, type: t.String },
    updatedAt: { isNullable: !0, type: t.Date },
  },
  m = ["id"],
  n = { type: 1 },
  d = ["previousItemId"],
  c = ["nextItemId"],
  u = ["id", "iVONskd1W"],
  s = ["iVONskd1W", "id"],
  f = ["GI_O5iwL7"],
  p = { type: 0 },
  y = ["lIk7B09Bk"],
  w = ["HlnUrNzwa"],
  N = ["iVONskd1W"],
  k = [],
  h = (e) => {
    let t = k[e];
    if (t) return t().then((e) => e.default);
  },
  I = {},
  g = i(I),
  B = new l(),
  S = {
    collectionByLocaleId: {
      default: new a({
        chunks: [
          new URL(
            "./TBKkMyqX4-chunk-default-0.framercms",
            import.meta.url
          ).href.replace("/modules/", "/cms/"),
        ],
        id: "20ec3d5b-2753-4ef9-a715-394d035abda4default",
        indexes: [
          new r({
            collation: n,
            collectionSchema: o,
            fieldNames: m,
            range: { from: 0, to: 73 },
            url: new URL(
              "./TBKkMyqX4-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: n,
            collectionSchema: o,
            fieldNames: d,
            range: { from: 73, to: 145 },
            url: new URL(
              "./TBKkMyqX4-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: n,
            collectionSchema: o,
            fieldNames: c,
            range: { from: 145, to: 213 },
            url: new URL(
              "./TBKkMyqX4-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: n,
            collectionSchema: o,
            fieldNames: u,
            range: { from: 213, to: 339 },
            url: new URL(
              "./TBKkMyqX4-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: n,
            collectionSchema: o,
            fieldNames: s,
            range: { from: 339, to: 465 },
            url: new URL(
              "./TBKkMyqX4-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: o,
            fieldNames: f,
            range: { from: 465, to: 557 },
            url: new URL(
              "./TBKkMyqX4-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: o,
            fieldNames: y,
            range: { from: 557, to: 977 },
            url: new URL(
              "./TBKkMyqX4-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: o,
            fieldNames: w,
            range: { from: 977, to: 10397 },
            url: new URL(
              "./TBKkMyqX4-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
          new r({
            collation: p,
            collectionSchema: o,
            fieldNames: N,
            range: { from: 10397, to: 10489 },
            url: new URL(
              "./TBKkMyqX4-indexes-default-0.framercms",
              import.meta.url
            ).href.replace("/modules/", "/cms/"),
          }),
        ],
        resolveRichText: g,
        resolveVectorSetItem: h,
        schema: o,
      }),
    },
    displayName: "Legal",
    id: "20ec3d5b-2753-4ef9-a715-394d035abda4",
  };
export default S;
e(S, {
  GI_O5iwL7: { defaultValue: "", title: "Title", type: t.String },
  lIk7B09Bk: { defaultValue: "", title: "Page Intro", type: t.String },
  HlnUrNzwa: { defaultValue: "", title: "Main Text", type: t.RichText },
  iVONskd1W: { preventLocalization: !1, title: "Slug", type: t.String },
  createdAt: { title: "Created", type: t.Date },
  updatedAt: { title: "Updated", type: t.Date },
  previousItemId: {
    dataIdentifier: "local-module:collection/TBKkMyqX4:default",
    title: "Previous",
    type: t.CollectionReference,
  },
  nextItemId: {
    dataIdentifier: "local-module:collection/TBKkMyqX4:default",
    title: "Next",
    type: t.CollectionReference,
  },
});
export const enumToDisplayNameFunctions = {};
export const utils = {
  async getSlugByRecordId(e, t) {
    let [l] = await B.query(
      {
        from: { data: S, type: "Collection" },
        limit: { type: "LiteralValue", value: 1 },
        select: [{ name: "iVONskd1W", type: "Identifier" }],
        where: {
          left: { name: "id", type: "Identifier" },
          operator: "==",
          right: { type: "LiteralValue", value: e },
          type: "BinaryOperation",
        },
      },
      t
    );
    return l?.iVONskd1W;
  },
  async getRecordIdBySlug(e, t) {
    let [l] = await B.query(
      {
        from: { data: S, type: "Collection" },
        limit: { type: "LiteralValue", value: 1 },
        select: [{ name: "id", type: "Identifier" }],
        where: {
          left: { name: "iVONskd1W", type: "Identifier" },
          operator: "==",
          right: { type: "LiteralValue", value: e },
          type: "BinaryOperation",
        },
      },
      t
    );
    return l?.id;
  },
};
export const __FramerMetadata__ = {
  exports: {
    enumToDisplayNameFunctions: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    utils: { type: "variable", annotations: { framerContractVersion: "1" } },
    default: {
      type: "data",
      name: "data",
      annotations: {
        framerEnumToDisplayNameUtils: "2",
        framerRecordIdKey: "id",
        framerCollectionId: "TBKkMyqX4",
        framerData: "true",
        framerCollectionUtils: "1",
        framerSlug: "iVONskd1W",
        framerColorSyntax: "false",
        framerContractVersion: "1",
        framerAutoSizeImages: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
