// Generated by Framer (46bf165)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const cycleOrder = ["EloeDt_Av", "gYcI3A2jy", "bDu_rpRlI"];
const serializationHash = "framer-DaGp9";
const variantClassNames = {
  bDu_rpRlI: "framer-v-dkj8c4",
  EloeDt_Av: "framer-v-j7175q",
  gYcI3A2jy: "framer-v-7ykwby",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  Desktop: "EloeDt_Av",
  Phone: "bDu_rpRlI",
  Tablet: "gYcI3A2jy",
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "EloeDt_Av",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "EloeDt_Av",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (["gYcI3A2jy", "bDu_rpRlI"].includes(baseVariant)) return false;
    return true;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-j7175q",
            className,
            classNames
          ),
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "EloeDt_Av",
          ref: refBinding,
          style: {
            backgroundColor:
              "var(--token-280bd9a0-bf37-41b4-a3c3-9a122b679a65, rgb(255, 255, 255))",
            ...style,
          },
          ...addPropertyOverrides(
            {
              bDu_rpRlI: { "data-framer-name": "Phone" },
              gYcI3A2jy: { "data-framer-name": "Tablet" },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-1687smq",
              "data-framer-name": "Section",
              layoutDependency: layoutDependency,
              layoutId: "XBhKsLDvC",
              children: /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-152379j",
                "data-framer-name": "Container",
                layoutDependency: layoutDependency,
                layoutId: "K7Q1QjPFP",
                children: /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-7qmj0h",
                  "data-framer-name": "hr",
                  layoutDependency: layoutDependency,
                  layoutId: "vZXh6d5AE",
                  style: {
                    backgroundColor:
                      "var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, rgb(0, 0, 0))",
                  },
                }),
              }),
            }),
            isDisplayed() &&
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-d36dxo",
                "data-framer-name": "Section",
                layoutDependency: layoutDependency,
                layoutId: "bYjTMyaou",
              }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-DaGp9.framer-8veet2, .framer-DaGp9 .framer-8veet2 { display: block; }",
  ".framer-DaGp9.framer-j7175q { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px 20px 0px 20px; position: relative; width: 1200px; }",
  ".framer-DaGp9 .framer-1687smq { align-content: center; align-items: center; display: flex; flex: 11 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1px; }",
  ".framer-DaGp9 .framer-152379j { -webkit-user-select: auto; align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: visible; padding: 0px 20px 0px 20px; pointer-events: auto; position: relative; user-select: auto; width: 100%; }",
  ".framer-DaGp9 .framer-7qmj0h { flex: none; height: 1px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 100%; }",
  ".framer-DaGp9 .framer-d36dxo { align-content: center; align-items: center; align-self: stretch; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 64px; height: auto; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1px; }",
  ".framer-DaGp9.framer-v-7ykwby.framer-j7175q { padding: 0px 15px 0px 15px; width: 810px; }",
  ".framer-DaGp9.framer-v-7ykwby .framer-1687smq, .framer-DaGp9.framer-v-dkj8c4 .framer-1687smq { flex: 1 0 0px; }",
  ".framer-DaGp9.framer-v-7ykwby .framer-152379j { padding: 0px 15px 0px 15px; }",
  ".framer-DaGp9.framer-v-dkj8c4.framer-j7175q { padding: 0px 10px 0px 10px; width: 390px; }",
  ".framer-DaGp9.framer-v-dkj8c4 .framer-152379j { padding: 0px 10px 0px 10px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 1
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"gYcI3A2jy":{"layout":["fixed","auto"]},"bDu_rpRlI":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerE_eUSw7wp = withCSS(Component, css, "framer-DaGp9");
export default FramerE_eUSw7wp;
FramerE_eUSw7wp.displayName = "HR";
FramerE_eUSw7wp.defaultProps = { height: 1, width: 1200 };
addPropertyControls(FramerE_eUSw7wp, {
  variant: {
    options: ["EloeDt_Av", "gYcI3A2jy", "bDu_rpRlI"],
    optionTitles: ["Desktop", "Tablet", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(FramerE_eUSw7wp, [{ explicitInter: true, fonts: [] }], {
  supportsExplicitInterCodegen: true,
});
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerE_eUSw7wp",
      slots: [],
      annotations: {
        framerAutoSizeImages: "true",
        framerContractVersion: "1",
        framerColorSyntax: "true",
        framerComponentViewportWidth: "true",
        framerImmutableVariables: "true",
        framerDisplayContentsDiv: "false",
        framerIntrinsicWidth: "1200",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"gYcI3A2jy":{"layout":["fixed","auto"]},"bDu_rpRlI":{"layout":["fixed","auto"]}}}',
        framerIntrinsicHeight: "1",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./E_eUSw7wp.map
