// Generated by Framer (b135809)
import { fontStore } from "framer";
fontStore.loadFonts([]);
export const fonts = [{ explicitInter: true, fonts: [] }];
export const css = [".framer-PloI1 .framer-styles-preset-nczjyy {  }"];
export const className = "framer-PloI1";
export const __FramerMetadata__ = {
  exports: {
    className: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    fonts: { type: "variable", annotations: { framerContractVersion: "1" } },
    css: { type: "variable", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
