// Generated by Framer (d22cd96)
import {
  addPropertyControls as e,
  ControlType as t,
  QueryEngine as l,
} from "framer";
import { DatabaseCollection as a } from "./UPVmP5DKV-0.js";
import { getRichTextJsonResolver as i } from "./UPVmP5DKV-1.js";
let r = {
    createdAt: { isNullable: !0, type: t.Date },
    GpN0g_2PT: { isNullable: !0, type: t.RichText },
    id: { isNullable: !1, type: t.String },
    JNInkEtta: { isNullable: !0, type: t.String },
    nextItemId: { isNullable: !0, type: t.String },
    previousItemId: { isNullable: !0, type: t.String },
    updatedAt: { isNullable: !0, type: t.Date },
    uy9J8iNeE: { isNullable: !0, type: t.Boolean },
    Vnj0TPTGl: { isNullable: !0, type: t.String },
  },
  n = [],
  o = (e) => {
    let t = n[e];
    if (t) return t().then((e) => e.default);
  },
  u = {},
  d = i(u),
  p = new l(),
  y = {
    collectionByLocaleId: {
      default: new a({
        chunks: [
          new URL(
            "./UPVmP5DKV-chunk-default-0.framercms",
            import.meta.url
          ).href.replace("/modules/", "/cms/"),
        ],
        id: "c8f5de84-ca2a-4539-9df5-db483305bf26default",
        indexes: [],
        resolveRichText: d,
        resolveVectorSetItem: o,
        schema: r,
      }),
    },
    displayName: "FAQ",
    id: "c8f5de84-ca2a-4539-9df5-db483305bf26",
  };
export default y;
e(y, {
  JNInkEtta: { defaultValue: "", title: "Question", type: t.String },
  GpN0g_2PT: {
    defaultValue: "",
    preventLocalization: !0,
    title: "Answer",
    type: t.RichText,
  },
  Vnj0TPTGl: { preventLocalization: !1, title: "Slug", type: t.String },
  uy9J8iNeE: { defaultValue: !1, title: "Open", type: t.Boolean },
  createdAt: { title: "Created", type: t.Date },
  updatedAt: { title: "Updated", type: t.Date },
  previousItemId: {
    dataIdentifier: "local-module:collection/UPVmP5DKV:default",
    title: "Previous",
    type: t.CollectionReference,
  },
  nextItemId: {
    dataIdentifier: "local-module:collection/UPVmP5DKV:default",
    title: "Next",
    type: t.CollectionReference,
  },
});
export const enumToDisplayNameFunctions = {};
export const utils = {
  async getSlugByRecordId(e, t) {
    let [l] = await p.query(
      {
        from: { data: y, type: "Collection" },
        limit: { type: "LiteralValue", value: 1 },
        select: [{ name: "Vnj0TPTGl", type: "Identifier" }],
        where: {
          left: { name: "id", type: "Identifier" },
          operator: "==",
          right: { type: "LiteralValue", value: e },
          type: "BinaryOperation",
        },
      },
      t
    );
    return l?.Vnj0TPTGl;
  },
  async getRecordIdBySlug(e, t) {
    let [l] = await p.query(
      {
        from: { data: y, type: "Collection" },
        limit: { type: "LiteralValue", value: 1 },
        select: [{ name: "id", type: "Identifier" }],
        where: {
          left: { name: "Vnj0TPTGl", type: "Identifier" },
          operator: "==",
          right: { type: "LiteralValue", value: e },
          type: "BinaryOperation",
        },
      },
      t
    );
    return l?.id;
  },
};
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "data",
      name: "data",
      annotations: {
        framerEnumToDisplayNameUtils: "2",
        framerCollectionUtils: "1",
        framerAutoSizeImages: "true",
        framerCollectionId: "UPVmP5DKV",
        framerColorSyntax: "false",
        framerSlug: "Vnj0TPTGl",
        framerRecordIdKey: "id",
        framerContractVersion: "1",
        framerData: "true",
      },
    },
    enumToDisplayNameFunctions: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    utils: { type: "variable", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
