// Generated by Framer (5cc8ebe)
import { fontStore } from "framer";
fontStore.loadFonts(["FS;Bebas Neue-regular"]);
export const fonts = [
  {
    explicitInter: true,
    fonts: [
      {
        cssFamilyName: "Bebas Neue",
        source: "fontshare",
        style: "normal",
        uiFamilyName: "Bebas Neue",
        url: "https://framerusercontent.com/third-party-assets/fontshare/wf/AWXLDXTI2CYJ5SHK74YUPGPFS5S5BWLL/M6ZJD4UOFNT4DPUXGTK7T46JZ3W3QW64/2TXZKBJMJVP3NQX7K7MGJDQFMD4ZMJR7.woff2",
        weight: "400",
      },
    ],
  },
];
export const css = [
  ".framer-fuUOe .framer-styles-preset-1qlraow:not(.rich-text-wrapper), .framer-fuUOe .framer-styles-preset-1qlraow.rich-text-wrapper p { --framer-font-family: \"Bebas Neue\", \"Bebas Neue Placeholder\", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv03' on, 'cv04' on, 'cv09' on, 'cv11' on; --framer-font-size: 34px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 90%; --framer-paragraph-spacing: 20px; --framer-text-alignment: center; --framer-text-color: var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }",
  "@media (max-width: 1599px) and (min-width: 0px) { .framer-fuUOe .framer-styles-preset-1qlraow:not(.rich-text-wrapper), .framer-fuUOe .framer-styles-preset-1qlraow.rich-text-wrapper p { --framer-font-family: \"Bebas Neue\", \"Bebas Neue Placeholder\", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv03' on, 'cv04' on, 'cv09' on, 'cv11' on; --framer-font-size: 30px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 90%; --framer-paragraph-spacing: 20px; --framer-text-alignment: center; --framer-text-color: var(--token-bb767153-5225-4c6b-b0ae-3d663b50e633, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }",
];
export const className = "framer-fuUOe";
export const __FramerMetadata__ = {
  exports: {
    fonts: { type: "variable", annotations: { framerContractVersion: "1" } },
    css: { type: "variable", annotations: { framerContractVersion: "1" } },
    className: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
